### ISSUE TITLE
Erweiterungsvorschlag: originäre Homekit-Geräte -> KNX

### ISSUE THREAD

**Issue by feanmg** [brutella/hkknx-public#10]
Ich fände es eine sinnvolle Erweiterung, wenn auch der "Rückweg" (Homekit->KNX) unterstützt würde.
Ich kann mir vorstellen, dass das ein interessanter Anwendungszweck ist, da viele Homekit-Geräte WLAN-fähig und deutlich günstiger zu kaufen sind, als KNX-RF-Geräte.

Hier denke ich persönlich an eher unkritische Anwendungen, wie Homekit-Funksteckdose für die Kaffeemaschine, die man trotzdem gerne am KNX-Wandschalter schalten möchte, an die Funksteckdose für den Christbaum oder mal einen Homekit-Funk-Wandschalter fürs Gartenhaus.

**Comment by brutella** [comment]
Die Idee finde ich ganz gut. 
Zurzeit aber liegt der Fokus die KNX Geräte für HomeKit zur Verfügung zu stellen.

Maybe in the future.

**Comment by rw71** [comment]
Das sollte sich mit der Automation in der Home-App einstellen lassen. "Wenn ein Sensor etwas entdeckt" heißt das da. Wenn ein KNX Gerät eingeschaltet wird, für HomeKit die entsprechende Konfiguration aus. Es muss aber für ein Ein- und ein Aus-Signal jeweils eine eigene Automation eingerichtet werden. Es funktionieren aber nur Sensoren (z.B. Fensterkontakte) und keine Lampen.

**Comment by ring-um** [comment]
...die Funktion wäre auch für mich sehr interessant..

**Comment by brutella** [comment]
Mit [Skripten](https://hochgatterer.me/de/hkknx/docs/scripts/) wird es möglich sein Nicht-HomeKit-Geräte bzw. Nicht-KNX-Geräte in den KNX Bus einzubinden. Sobald das Gerät mit KNX Gruppenadresse verbunden ist, können dafür auch HomeKit-Geräte erstellt werden.

Voraussetzung ist lediglich, dass das Nicht-HomeKit/KNX-Gerät mit einem Skript kommunizieren kann. Das hießt, das Protokoll muss entweder auf UDP, TCP oder HTTP basieren. Ein Beispiel dafür sind Shelly-Geräte. Diese Geräte haben eine eingebaute HTTP-API. Somit könnte man Shelly-Geräte mit dem KNX-Bus verbinden und basierend darauf HomeKit-Geräte erstellen.

**Comment by feanmg** [comment]
Hallo,

Das hört sich prima an!

Tatsächlich war mein Wunsch aber nur die einfache Integration von richtigen HomeKit-Geräten (kein Shelly oder so..) ins KNX. (Rückweg)

Am besten ohne Scripting/für einfache Anwender.

Kannst du das Ticket wieder öffnen?

Danke und bis dann!

**Comment by chef76** [comment]
Mit dem Umweg über Automation und ein bisschen Skripting funktioniert das ganz gut. Hab ich bei mir einiges im Einsatz. Schreib halt mal, was Du machen willst, dann kann Dir vielleicht geholfen werden.

**Comment by chriho135** [comment]
@brutella könntest du den Thread wieder aufmachen bitte?
Folgende Idee: Ich plane gerade eine Wohnung mit KNX auszustatten und in jedes Zimmer ein Homepod Mini zur Sprachsteuerung zu verwenden. Der Homepod Mini hat in Homekit bereits Temperatur und Luftfeuchtigkeit quasi gratis mit dabei. Ich könnte mir sehr teure KNX Sensoren sparen, wenn ich diese Werte über die hkknx bridge auf den KNX Bus (und in der ETS damit) zur Verfügung stelle. Siehst Du hier eine Möglichkeit?

**Comment by brutella** [comment]
@chriho135 Das ist leider nicht möglich, da nur Apple Zugriff auf dem HomePod hat. Keine App auf dem iPhone kann auf die HomePod-Sensoren zugreifen - auch nicht [Home+](https://hochgatterer.me/home+/).
