### ISSUE TITLE
Problem bei Gerätetyp „Sicherheitssystem“

### ISSUE THREAD

**Issue by Peyto79** [brutella/hkknx-public#100]
Hallo,

seit der neuesten Version funktioniert der Gerätetyp „Sicherheitssystem“ nicht mehr wie gewohnt.
Bisher konnte ich zwischen den Status Zuhause, Abwesend, Nacht und Aus hin und her schalten und die hinterlegten Funktionen wurden ausgeführt. 
Wenn ich jetzt mit der 1.3.0 auf beispielsweise Nacht schalte, springt er sofort zurück auf Zuhause oder wenn ich auf Aus klicke, dreht er ewig und springt nach einem Neustart der Home App zurück auf Nacht. 
Wenn ich mehrfach auf Zuhause klicke kann es sein, dass er irgendwann doch auf Zuhause bleibt, aber es werden keine Aktionen gestartet.

Viele Grüße
Christian

**Comment by brutella** [comment]
Wie sieht die Konfiguration des Sicherheitssytems in hkknx aus?

**Comment by brutella** [comment]
Tritt das Problem noch weiter auf?

**Comment by Peyto79** [comment]
Hast du was verändert? Dann würde ich es noch mal probieren. Falls nicht:
Ich habe das Gerät „Sicherheitssystem“ mittlerweile gelöscht und mir anderweitig beholfen. Ich würde daher das Ticket schliessen.
