### ISSUE TITLE
Temperaturreglung Klimaanlage

### ISSUE THREAD

**Issue by DomiCreation** [brutella/hkknx-public#103]
Hallo nochmal,

eben wollte ich noch meine Klimaanlage die am KNX Bus hängt ansteuern.
Dort ist mir bei der Temperaturreglung nur ein Punkt für das Heizungsventil aufgefallen.
Damit kann ich die Klima auch steuern wenn ich dort meine EIN/AUS Statuswerte drauflege und in HomeKit "HEIZUNG" auswähle. 
Wäre es möglich noch einen "KÜHLUNG" Status reinzubringen?

<img width="1172" alt="Bildschirmfoto 2021-06-08 um 13 15 24" src="https://user-images.githubusercontent.com/185418/121175655-9d34e280-c85b-11eb-8850-1b9ad10d53dd.png">

Viele Grüße
Dominic

**Comment by brutella** [comment]
Seit Version [2.7.0](https://github.com/brutella/hkknx-public/releases/tag/2.7.0) gibt es die Möglichkeit für die Status Kühlung eine Gruppenadresse anzugeben.
