### ISSUE TITLE
Temperatur auslesen

### ISSUE THREAD

**Issue by HollaTheWoodFairy** [brutella/hkknx-public#104]
Hallo,
allem Anschein nach funktioniert bei mir das auslesen der Temperatur nicht.
Ich habe verschiedene Glastaster von MDT und bei allen ist das selbe verhalten.
Der Gemessene Wert unterscheidet sich von dem der in HomeKit ankommt. Es sieht so aus, als wenn immer der Soll-Wert statt dem IST-Wert ausgelesen wird. Ich kann mir allerdings nicht erklären wo der Fehler liegt.
Anbei einige Screenshots. Alle aus dem Raum Schlafzimmer.

HKKNX Version: • 1.3.0 (2021-04-28T11:50:31+02:00)

![Screenshot 2021-06-14 181614](https://user-images.githubusercontent.com/82179494/121925786-8dc30700-cd3d-11eb-86b3-03f681d6e980.png)
![Screenshot 2021-06-14 181841](https://user-images.githubusercontent.com/82179494/121925787-8e5b9d80-cd3d-11eb-9420-8430ae147d8b.png)
![Screenshot 2021-06-14 181857](https://user-images.githubusercontent.com/82179494/121925788-8e5b9d80-cd3d-11eb-9103-90da5a0c7f5f.png)
![20210614_162131962_iOS](https://user-images.githubusercontent.com/82179494/121925804-93b8e800-cd3d-11eb-8b5d-2a6c162fbe91.png)

**Comment by brutella** [comment]
Ich kann ich keinen Fehler entdecken. Es wird korrekt der Wert von der GA 12/1/2 ausgelesen.

Kannst du mal mit einer anderen HomeKit-App (zB Eve-App) nachsehen, welcher Ist-Wert für das Thermostat angezeigt wird?

**Comment by HollaTheWoodFairy** [comment]
Hi, jetzt gerade ist es etwas schwierig zu prüfen da IST und SOLL identisch sind. In der Eve-App wird zumindest auch die aktuelle korrekte Temperatur angezeigt.

Vielleicht hab ich ja auch einen Denkfehler - wird denn in der Home-App (oben links in dem grünen Kreis) die aktuelle Temperatur angezeigt?

Laut meinen Screenshots müssten dort 22,8 °C (oder 22,5 - ich weiß nicht ob iOS da rundet) stehen - oder hab ich das falsch verstanden?

**Comment by brutella** [comment]
@HollaTheWoodFairy Gibt es schon etwas neues zu deinem Problem?
