### ISSUE TITLE
[Scripts] Support for MQTT

### ISSUE THREAD

**Issue by nanosonde** [brutella/hkknx-public#107]
Concerning external packages:
Can I also use [this package](https://github.com/eclipse/paho.mqtt.golang)?
There is already the support for HTTP, but MQTT would also be nice.

**Comment by bernd70** [comment]
I second that. Maybe even on a more integrated approach. A switch (or any other action) could be a call to http oder mqtt instead of writing to a group address.

**Comment by brutella** [comment]
Access to MQTT via a client implementation sounds like a great idea. 
This way you can send KNX values to MQTT and vice versa.

Would you also need to run an MQTT broker in hkknx?

**Comment by bernd70** [comment]
Opps, this is an old thread... :-)

Right now I do not use Homekit a lot. Actually I only use three actions: "Turn on/off Espresso Machine", "Activate Sun Protection in Office" and "Open/Close Garage Door".

But regarding the question: I dont think HKKNX needs a MQTT broker.. When using MQTT there is typically a MQTT instance like mosquitto running somewhere.

And if hkknx could both publish and subscribe it caould act as a gateway between Homekit and any other instance supporting MQTT.

**Comment by brutella** [comment]
The mqtt package is now available in [2.7.0-b1](https://github.com/brutella/hkknx-public/releases/tag/2.7.0-b1).
Read more here → https://hochgatterer.me/de/hkknx/docs/scripts/mqtt/ (German only for now)
