### ISSUE TITLE
Script lässt sich nicht aktivieren

### ISSUE THREAD

**Issue by Joeknx** [brutella/hkknx-public#112]
Wenn ich ein Script aktiveren oder ausführen möchte, erscheint entweder ein drehendes Rad oder "waiting for remote server".

**Comment by chef76** [comment]
Drehendes Rad, wie auch Waiting for remote Server heißt, dass das Skript läuft und auf ein Telegramm vom Bus wartet.

**Comment by Joeknx** [comment]
> Drehendes Rad, wie auch Waiting for remote Server heißt, dass das Skript läuft und auf ein Telegramm vom Bus wartet.

ah, danke!
Das ist irgendwie nicht ganz selbsterklärend.

**Comment by brutella** [comment]
Also Ergänzung: `Waiting for remote server` steht so lange da, bis die erste Log-Ausgabe via `println` oder `printf` erscheint oder das Skript fertig ausgeführt wurde.
