### ISSUE TITLE
HMErrorDomain-Fehler 31 bei HomeKit sync

### ISSUE THREAD

**Issue by areicherdt** [brutella/hkknx-public#115]
Während des Syncs mit der Konfigurator App erhalte ich aktuell folgende Meldung "HMErrorDomain-Fehler 31".
Der Fehler ist bei mir das erste mal, nach dem Update der iOS App, aufgetreten.

Der Sync wird, trotz der Meldung, komplett durchgeführt.

App Version 1.1.1 (12)
hkknx 2.0.0 (public)

**Comment by brutella** [comment]
Dieser Fehler tritt auf, wenn versucht wird ein Gerät umzubenennen aber es bereits ein Gerät mit dem selben Namen gibt. HomeKit erlaubt mehrere Geräte mit dem selben Namen nicht. Ist zwar blöd, kann man aber nicht ändern.

**Comment by areicherdt** [comment]
Homekit hatte anscheinend auch Probleme mit Umlauten bzw. Geräte mit Umlauten umzubennen. Mit einem reset der kompletten HomeKit Instanz , ist das Problem verschwunden.
