### ISSUE TITLE
 Support for IP Secure & Data Secure

### ISSUE THREAD

**Issue by dkreutzer** [brutella/hkknx-public#129]
Currently, no secure devices are supported. Are there any plans for when it will be possible?
In my case, it shows in HomeKit a 0.0° as temperature as it cannot be decoded properly. The raw data is shown in the group monitor.

**Comment by brutella** [comment]
There are currently no plans to support secured devices, but I will definitely look into this issue in the future.

**Comment by nanosonde** [comment]
BTW: What KNX stack do you use for this project?
Is it the golang KNX stack from vapourismo?
Or your own stack?

**Comment by MirkoLenz** [comment]
Recently, xknx (the library used by Home Assistant) [added support](https://github.com/XKNX/xknx/releases/tag/0.20.0) for IP Secure. If hkknx would also have support for this, I could activate it for my IP interface. Would that be possible now that there ist at least some reference implementation available?

**Comment by Julian0Davinci** [comment]
KNX-ULTIMATE for node-red also supports knx-secure. Hkknx is the last software in my setup which does not allow me activate knx-secure on my ip-interface.

> Recently, xknx (the library used by Home Assistant) [added support](https://github.com/XKNX/xknx/releases/tag/0.20.0) for IP Secure. If hkknx would also have support for this, I could activate it for my IP interface. Would that be possible now that there ist at least some reference implementation available?

**Comment by brutella** [comment]
Secure tunneling is now supported in the pre-release version [2.3.1](https://github.com/brutella/hkknx-public/releases/tag/2.3.1).

Please test it and give feedback. Thanks!

**Comment by mirkolenz** [comment]
Thank you so much for working on this feature! At the moment, my IP Router with support for IP Secure is broken and my temporary unit does not have support for secure connections. I hope to have a replacement unit next week and will test v2.3.1 as soon as possible 😊

**Comment by brutella** [comment]
@dkreutzer @mirkolenz Did anyone already test Secure Tunneling in the latest build?

**Comment by mirkolenz** [comment]
Sadly not. I am still waiting for my new IP Router to arrive…

**Comment by mirkolenz** [comment]
Small update: I received my new router today and will install it during the weekend. If everything goes as planned I will be able to provide feedback sometime next week.

**Comment by brutella** [comment]
A better documentation is now available in the Online Handbuch (currently German only).
https://hochgatterer.me/de/hkknx/docs/config/knx-connection/#sichere-verbindung
