### ISSUE TITLE
KNX-Scenes - wrong error message for DPST-17-1 datatype

### ISSUE THREAD

**Issue by Superwuzy** [brutella/hkknx-public#132]
I'm using various KNX scenes in my house (DPT 17.001 - 1 Byte scene numbers).

When trying to add a toggle switch to HKKNX I'm trying to trigger a DPT 17.001 scene but HKKNX tells me that the data type is wrong. That is not correct. When I'm triggering the scene externally the HKKNX group monitors cleary lists the correct DPT type of the scene. 

What is wrong here (see pictures)?

Group monitor dump for GA 11/2/2:
<img width="1457" alt="Bildschirmfoto 2021-09-04 um 20 29 43" src="https://user-images.githubusercontent.com/17985563/132104728-79fd4ddb-3d14-4b8c-a4f0-952ab04a234c.png">

Dialog with error message when trying to attach the scene trigger GA 11/2/2: 
<img width="1099" alt="Bildschirmfoto 2021-09-04 um 20 30 31" src="https://user-images.githubusercontent.com/17985563/132104727-579b60f8-d8c7-42ea-911c-b0ff3cd5c230.png">

HKKNX-version: 2.0.0 (2021-08-11T10:39:56+02:00)

**Comment by chef76** [comment]
Is the DPT Type die this Group Adress Set in your ETS Project File?

**Comment by Superwuzy** [comment]
> Is the DPT Type for this Group Adress Set in your ETS Project File?

Yes, for several years already.

![Bildschirmfoto 2021-09-04 um 22 13 45](https://user-images.githubusercontent.com/17985563/132106965-7baf2541-b98d-4cb8-8e32-c4f5d65ca03e.png)

**Comment by chef76** [comment]
Strange... works fine for me. Sometimes if you don't choose from the pulldown-menue and enter the group adress directly such errors appear, but if you press Tab to leave the field it goes green.

**Comment by brutella** [comment]
You can easily ignore this warnings. hkknx sends the data to any group address you want, regardless of the defined DPT in your ETS project.

**Comment by brutella** [comment]
Should be fixed in [pre-release version 2.0.1](https://github.com/brutella/hkknx-public/releases/tag/2.0.1).
