### ISSUE TITLE
DPT7012/DPT7013 script function outputs only 8bit (0-255) instead of the correct 16bit values (0-65,535)

### ISSUE THREAD

**Issue by matthafner** [brutella/hkknx-public#134]
I think I found a bug in scripting, when using "hkknx.DPT7012(...)" or "hkknx.DPT7013(...)", the max value is "00 FF" (255).
Below 255, it works correctly... it is always "00 FF" if the value is between 255 and 65,535).

Here is a screenshot of the code I was using to test it...
![Code](https://user-images.githubusercontent.com/8529743/133857482-8a03bd59-848a-4832-8fc8-31f8f998fdb4.png)

... here the response (the 300 and 30000 values are not correct)!
![GroupMonitor](https://user-images.githubusercontent.com/8529743/133857597-91cf686e-f496-4c17-8229-a619f0935568.png)

It should say "01 2C" and "75 30"

I'm on hkknx Version 2.0.0.

And thanks for making this tool, it works really well... minus this little bug which should be a quick fix ;)

**Comment by brutella** [comment]
Fixed in [pre-release version 2.0.1](https://github.com/brutella/hkknx-public/releases/tag/2.0.1).
