### ISSUE TITLE
Virtuelle Geräte-Seriennummern für Homekit bereitstellen

### ISSUE THREAD

**Issue by Peyto79** [brutella/hkknx-public#137]
Hallo,

wenn ich mir die Geräte-Details eines HKKNX Gerätes in Homekit anschaue, so wird mir die Seriennummer als "undefined" angezeigt.

_In meinem Fall ist es so, dass ich mit der "Controller for Homekit" App regelmäßig Backups von meiner HomeKit Konfiguration erstelle. Meine Konfiguration ist sehr umfangreich, da ich neben 142 HKKNX Geräten auch 118 Homematic Geräte, 41 Phillips Hue Leuchtmittel, 3 von IKEA Tradfri und verschiedene Homebridge Geräte integriert habe. Aufgeteilt auf 25 Räume und Funktions-Gruppen mit allerhand Regeln und Automationen. Und Homekit hat mir schon öfter was "durcheinander" gebracht._

Wenn ich nun das Backup erstellen möchte, kommt der Hinweis, dass eine Wiederherstellung nicht ohne weiteres möglich wäre, da viele Geräte die gleiche Seriennummer "undefined" hätten. Anscheinend wird bei dem Backup die Seriennummer als eindeutiges Merkmal des Geräts herangezogen um es beim wiederherstellen eindeutig den Räumen und Automationen zuweisen zu können.

Daher die Frage:
Könnte man in HKKNX ein Feld hinzufügen um virtuelle Seriennummern zu vergeben? Oder per Zufalls-Wert?
Hersteller und Modell gibt es ja schon.

Viele Grüße
Christian

**Comment by brutella** [comment]
`hkknx` erstellt bereits eine UUID für jedes Gerät und speichert es in die HomeKit-Eigenschaft mit der ID `0E4B0602-C7BC-4CA6-83D5-3CD81A24EF34`. Diese Eigenschaft wird dem Benutzer normalerweise nicht angezeigt, da sie als verborgen markiert ist. Ob "Controller for HomeKit" diese Eigenschaft verwenden kann, weiss ich nicht.

**Comment by brutella** [comment]
Mit [Home+](https://apps.apple.com/us/app/home-5/id995994352) kannst du auch Backups erstellen und dabei werden die hkknx-Geräte korrekt über die ID identifiziert.

**Comment by Peyto79** [comment]
Danke für den Tipp:-)
Backup erstellt
