### ISSUE TITLE
Buying a license is not possible

### ISSUE THREAD

**Issue by hmoerli** [brutella/hkknx-public#141]
The certificate for the licensing website has expired on september, 21st.

**Comment by brutella** [comment]
What error message do you see when you try to purchase a license?

**Comment by hmoerli** [comment]
That's the error message:

Get "https://api.stripe.com/v1/products/prod_JdJpV1PZOv2dfx": x509: certificate has expired or is not yet valid: current time 2021-06-02T11:11:28+01:00 is before 2021-09-21T00:00:00Z

**Comment by brutella** [comment]
Please try to set the current date and time on your computer. See https://hochgatterer.me/hkknx/docs/help/buy-license-error/
