### ISSUE TITLE
Bus Monitor Problem

### ISSUE THREAD

**Issue by gisbertpeter** [brutella/hkknx-public#142]
Hallo,
wenn man den KNX-Monitor nutzt und viel Bus-Traffic hat beendet sich das Monitoring scheinbar nach x Minuten, d.h. es kommen keine Ausschriften mehr. Das scheint auch Auswirkungen auf die Stabilität der Software zu haben. Gibt es Begrenzungen oder Einstellungen, die man beachten muss? Kann man überprüfen wie der Status der HKKNX Software ist?

**Comment by brutella** [comment]
Beobachte mal die Log-Ausgaben in der [Konsole](https://hochgatterer.me/de/hkknx/docs/help/access-log/) während der Bus Monitor läuft.

Auch der Speicherverbrauch von `hkknx` könnte ausschlaggebend für das Problem sein.

**Comment by brutella** [comment]
Bitte teste dein Problem mal mit der aktuellen Pre-Release Version 2.1.1. Besteht das Problem weiterhin?

**Comment by gisbertpeter** [comment]
Vielen Dank für das Update. Ich habe die Version 2.1.1 installiert und werde das nun beobachten.
Inzwischen glaube ich jedoch, dass das Problem noch mit dem [Issue 150](https://github.com/brutella/hkknx-public/issues/150)  zusammenhängt. Das ist beim mir das gleiche "partially unresponsive" Verhalten, siehe mein Eintrag im [Issue 150](https://github.com/brutella/hkknx-public/issues/150).
