### ISSUE TITLE
Arm64 / armv8 build

### ISSUE THREAD

**Issue by retrack** [brutella/hkknx-public#144]
Hello

would it be possible to provide an arm64 binary ?

great product by the way, I am still Evaluating but super promising for my setup with 150+ devices.

**Comment by brutella** [comment]
Should this build be for Linux? 
(There is already an armv8 build for darwin/macOS.)

**Comment by retrack** [comment]
> Should this build be for Linux? (There is already an armv8 build for darwin/macOS.)

yes please, linux target. I am specifically running on Espressobin but more and more SBC are armv8 nowadays.

**Comment by brutella** [comment]
I've just uploaded an armv64 package for linux for the release 2.0.1.
Please try that.

**Comment by retrack** [comment]
Confirmed working with Armbian on Rockchip RK3399.
https://github.com/brutella/hkknx-public/releases/tag/2.0.1

Thanks.
