### ISSUE TITLE
Add support for ETS6 imports

### ISSUE THREAD

**Issue by paulfarnell** [brutella/hkknx-public#147]
I recently upgraded and had to find an old copy of my `.knxproj` for initial import. 

All my newer devices are part of my ETS v6 project file now, and ETS won't allow me to export to earlier ETS file formats ☹️

**Comment by paulfarnell** [comment]
If you wish to send me a sample **ETS5** project I can upgrade it to **ETS6**.

Bitte sagen Sie mir, wie ich helfen kann. 🙂

**Comment by brutella** [comment]
Support for ETS6 projects is now available in the [pre-release version 2.1.0](https://github.com/brutella/hkknx-public/releases/tag/2.1.0).

**Comment by paulfarnell** [comment]
Confirmed I can import an ETS6 project with version 2.1.0. 👍
