### ISSUE TITLE
Unterstützung für Fensterkontakt-Sensor mit mehreren Stati (Geschlossen/Gekippt/Manipulation)

### ISSUE THREAD

**Issue by pfeifix** [brutella/hkknx-public#149]
Eve hat einen Fenstersensor herausgebracht, der im HomeKit über einen Kontakt repräsentiert wird, der mehrere Stati ausgeben kann. Speziell wird zwischen "Offen/Geschlossen", "Gekippt" und "Manipulation/Störung" unterschieden werden können. --> Siehe https://www.evehome.com/de/eve-window-guard

Ich habe in meiner KNX-Installation an jedem Fenster zwei Kontakte eingebaut, einen unten und einen oben, um zwischen geschlossen und gekippt unterscheiden zu können. Die Manipulation wird über den Sabotagekontakt erkannt.

Ist so eine Art Kontakt auch im hkknx geplant? Für mich (und wie ich denke für viel andere) wäre das super hilfreich.

**Comment by brutella** [comment]
Wie wird der Status _Gekippt_ in der Apple Home-App angezeigt? Meines Wissens können Kontaktsensoren in HomeKit nur 2 Stati – _Kontakt erkannt_, u. _Kein Kontakt erkannt_.

**Comment by pfeifix** [comment]
Das ist auch mein Stand. Allerdings weiß ich nicht, ob Apple da mittlerweile nicht was dran erweitert hat. Ich nehme ja mal schon an, dass es Eve's Bestreben ist, im HomeKit-Ökosystem zu bleiben (wenngleich sie auch eine eigene App anbieten, die allerdings meines Wissens auch auf HomeKit -Standards basiert). Meine Hoffnung war, dass Du da nähere Infos bzgl. der HomeKit-Definitionen von Apple hast.
Dass Fensterkontakte mehrere Stati haben müssen ist ja ein lang bekannter Tatbestand insofern müssten die ja eigentlich irgendwann mal drauf kommen.

**Comment by brutella** [comment]
Nein, leider hat sich im HomeKit-Standard dahingehend nichts getan.

**Comment by pfeifix** [comment]
Könntest Du so etwas in Deine Home+ App einbauen (ähnlich wie Eve es macht)? Dann hätte man zumindest eine schöne Bedienoption bis Apple das nativ einbaut.
