### ISSUE TITLE
Fehler bei Import von ETS 6.0.0

### ISSUE THREAD

**Issue by Guido1976** [brutella/hkknx-public#155]
Hallo,
ich habe ein Problem, dass ich auf der KNX Bridge auf dem Raspberry Pi mein neues ETS6 Projekt nicht importiert bekomme. Es kommt immer die Fehlermeldung zip: invalid password.
Wenn ich das alte Projekt von der ETS5 importiere geht es reibungslos. Woran kann das liegen?

Ich habe heute morgen nochmal mehrere Versuche gestartet und dabei festgestellt, dass auch das entfernen meines MDT Ip Secure Routers noch nicht zum Erfolg führte. Wenn ich aber dann das Passwort entfernte, funktionierte der Import.

Grüße Guido

**Comment by brutella** [comment]
Laut [knx-user-forum](https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/1711442-erster-ausflug-in-die-ets6-ernüchterung?p=1713912#post1713912) kann ein exportiertes ETS 6 Projekt mit einem Passwort nicht mehr so ohne weiteres entschlüsselt werden.

**Comment by Guido1976** [comment]
Und was bedeutet dies nun konkret für mich in Zukunft? Muss ich dann immer vor dem Import sicherstellen, dass kein Passwort vorhanden ist?

**Comment by brutella** [comment]
Ja leider. 😕

**Comment by traxanos** [comment]
Aber dann geht doch Secure nicht mehr, oder? Zumindest bin ich dazu genötigt worden ein Passwort zu vergeben seit ich Secure nutze.

**Comment by brutella** [comment]
Passwortgeschützte ETS 6 Projektdateien können jetzt mit Version [2.3.1](https://github.com/brutella/hkknx-public/releases/tag/2.3.1) korrekt importiert werden.
