### ISSUE TITLE
Unable to buy license

### ISSUE THREAD

**Issue by GSt4r** [brutella/hkknx-public#159]
Buying a license via the locally running hkknx server fails with the following error message:

`Get "https://api.stripe.com/v1/products/prod_JdJpV1PZOv2dfx": x509: certificate has expired or is not yet valid: current time 2021-09-05T14:54:00+01:00 is before 2021-09-21T00:00:00Z`

**Comment by AlexSpaeth1976** [comment]
> Please check the Date and Time on your device where hkknx is installed!

Yes. I had the same issue!
 I used the Rasp Image and the automatic date and time sync did not work!

**Comment by brutella** [comment]
See https://hochgatterer.me/hkknx/docs/help/buy-license-error/
