### ISSUE TITLE
POST requests in Script

### ISSUE THREAD

**Issue by GSt4r** [brutella/hkknx-public#160]
How are network requests supposed to be scripted? Using the standard golang functionality doesn't seem to work. I've already tried using `http.Post` from the `net/http` package, but that does not seem to be available. With `http.PostForm` I'm having trouble constructing the `url.Values` with the form data. Is there any script example that demonstrates this functionality?

**Comment by matthafner** [comment]
I am working on a video which uses this KNX bridge to connect to HomeKit and more (I played around a little to find out what this bridge is capable). Yes you are correct that there should be a little bit more examples of important things like this...

I had to figure out the same thing (so not sure this is the exact code which works for you but at least you can build of this ;) ).
This is a GET request, I believe... but hope this is of help.
 
![httpRequestExample](https://user-images.githubusercontent.com/8529743/148067838-4f0d1a31-942b-4501-a032-7f95e8de34fb.png)

This is the response you get in hkknx:

![httpRequestPrintln](https://user-images.githubusercontent.com/8529743/148067885-2b6f6e4f-d9d0-4801-ac75-ceaf47841617.png)

This is the response you get in a browser for example:

![httpRequestTeste](https://user-images.githubusercontent.com/8529743/148067617-be215479-0b2d-4635-a647-01df284bc25b.png)

@brutella Hi, Matthias, did you receive my email regarding the video I want to make, I didn't hear back from you? Let me know if you would like to collaborate ;)

**Comment by brutella** [comment]
> How are network requests supposed to be scripted? Using the standard golang functionality doesn't seem to work. I've already tried using `http.Post` from the `net/http` package, but that does not seem to be available.

Right, `http.Post` ist not available. Instead you have to use `Post` or `PostForm` function from the `Client` struct.

> With `http.PostForm` I'm having trouble constructing the `url.Values` with the form data. Is there any script example that demonstrates this functionality?

This example is an adapted version from the [net/http package documentation](https://pkg.go.dev/net/http#pkg-overview).

```go
http = import("net/http")
url = import("net/url")

data = url.Values{"key": {"Value"}, "id": {"123"}}
client = &http.Client{}
resp, err = client.PostForm("http://example.com/form", data)
```

**Comment by GSt4r** [comment]
Thanks @brutella for your example. Unfortunately, I'm receiving a syntax error on the following line:
```
data = url.Values{"key": {"Value"}, "id": {"123"}}
```

**Comment by brutella** [comment]
Oh, sorry. This should work.

```go
http = import("net/http")
url = import("net/url")

data = make(url.Values) 
data.Set("key", "Value")
data.Set("id", "123")

client = make(http.Client)
resp, err = client.PostForm("http://example.com/form", data)
```
