### ISSUE TITLE
Fehlerhaftes Verhalten von Apple Home in Verbindung mit Dimmer

### ISSUE THREAD

**Issue by Asa68** [brutella/hkknx-public#161]
Ich teste gerade die KNX-Bridge und würde mich freuen, wenn ich sie für mein Projekt einsetzen könnte. Das was ich bisher gesehen habe stimmt mich zuversichtlich.

Beim Rumprobieren ist allerdings ein Thema in Verbindung mit einer Lampe und einem Dimm-Aktor (Hager STYA662AN) aufgefallen, das ich hier platzieren möchte:

Zur Config:
Zum Schreiben der Dimmung nutze ich eine Gruppenadresse, welche einen absoluten Dimmwert an den Dimmer sendet.
Zum Lesen des Dimmwertes nutze ich eine Gruppenadresse an die der Dimmer den Dimmwert senden kann.
Beim Einschalten ist der Dimmer so konfiguriert, dass er in 2 Sekunden von 0 auf den eingestellten Dimmwert hochdimmt.

Das Problem:
Wenn ich den Dimmer mit meinem MDT Glastaster schalte, dann sendet dieser ein Einschalt-Telegramm ... der Dimmer dimmt hoch ... und sendet danach (!) zwei Statustelegramme zum Schalt-Status und zum Dimmstatus. Das funktioniert alles tadellos und auch Apple-Home bekommt die richtigen Werte mit.
Wenn ich den Dimmer nun mit Apple Home schalte, dann sendet dieser ein Einschalt-Telegramm und nahezu gleichzeitig ein Telegramm für einen Dimmwert von 100 % ... der Dimmer dimmt hoch, sendet aber dann viel zu schnell die zwei Statustelegramme, was dazu führt, dass der Dimm-Status bei eigen wenigen % hängen bleibt und die Lampe auch.

Die Frage: 
Gibt es einen Weg, dem Home-Schalter abzugewöhnen, dass er zum Einschalten gleich den Dimmwert (von 100 %) mitschickt. Das bringt die Sache wohl hier durcheinander.

Der Workaround:
Ich kann den Dimmer so konfigurieren, dass er beim Schalten nicht dimmt - dann passt es.
ABER: Auch hier ist es störend, dass ich beim Einschalten über Apple-Home immer auf 100 % komme, wo ich doch die Dimmung gern so hätte, wie sie beim Ausschalten war.

Vielen Dank für eure Hilfe.

**Comment by brutella** [comment]
> Wenn ich den Dimmer nun mit Apple Home schalte, dann sendet dieser ein Einschalt-Telegramm und nahezu gleichzeitig ein Telegramm für einen Dimmwert von 100 %

Richtig. Die Apple Home-App sendet beim Einschalten einer Lampe einen Dimmwert von 100%, wenn der Dimmwert im ausgeschalteten Zustand 0% war. Meistens ist das der Fall, da beim Ausschalten einer Lampe viele Dimmaktoren einen Dimmstatus von 0% melden.

Im Gegensatz dazu sendet meine [Home+](https://itunes.apple.com/us/app/home-smart-home-automation/id995994352)-App wie erwartet nur einen Einschaltbefehl beim Tippen auf ein Feld. 

> Die Frage: Gibt es einen Weg, dem Home-Schalter abzugewöhnen, dass er zum Einschalten gleich den Dimmwert (von 100 %) mitschickt. Das bringt die Sache wohl hier durcheinander.

Ich könnte versuchen, dieses Verhalten zu unterbinden, indem beim Einschalten einer Lampe gewartet wird, ob anschließend ein Dimmwert gesendet wird. Ist das der Fall, dann wird der Dimmbefehl ignoriert.

Jetzt stellt sich natürlich die Frage, ob es Dimmaktoren gibt, die beim Einschalten einer Lampe auf einer Helligkeit von 0% "stehen bleiben" und auf den Dimmbefehl warten. Hast du dazu Erfahrung?

**Comment by brutella** [comment]
Fixed in [2.2.0](https://github.com/brutella/hkknx-public/releases/tag/2.2.0)
