### ISSUE TITLE
HomeKit funktioniert nicht mehr nach Aufruf der Konsole

### ISSUE THREAD

**Issue by ralf-muc** [brutella/hkknx-public#163]
Hallo Herr Hochgatterer,

ich habe schon mal im KNX Forum mein folgendes Problem geschildert:

Das Problem ist das HomeKit Brücke immer wenn ich die Konsole im WEB Browser öffne nach einiger Zeit nicht mehr funktioniert.
Da hilft immer nur ein kompletter Neustart, ansonsten läuft das System aber absolut stabil und schnell.

Also ich starte die Konsole und die Log Ausgaben beginnen.

Nach einer Weile kommt dann:
..
..
..
Fehler: undefined
Aufzeichnung gestoppt
Aufzeichnung gestartet
Fehler: undefined
Aufzeichnung gestoppt
Aufzeichnung gestartet
Fehler: undefined
Aufzeichnung gestoppt
Aufzeichnung gestartet

Danach geht nichts mehr, die Geräte in der App stehen dann alle auf „Aktualisieren“.

Das Webinterface reagiert noch aber System neu Starten unter Einstellungen / Mehr ist nicht mehr möglich.

Inhalt der error.log Datei dann:
2022/01/17 21:57:31 log: failed to write msg: WebSocket closed: failed to read frame header: read tcp 192.168.168.248:8080->192.168.168.107:50509: read: connection reset by peer

Ein Reboot über SSH bringt das System wieder zum laufen.

Meine Version: 2.1.0 (2021-11-18T10:06:16+01:00)

Vielen Dank im Voraus.

VG Ralf

**Comment by brutella** [comment]
- Welchen Browser verwendest du?
- Wie lange dauert es, bis die Aufzeichnung gestoppt wird? Ist dieses Intervall bei dir immer gleich?
- Auf welchem Betriebssystem hast du hkknx laufen?
- Gibt es noch andere Log-Ausgaben, die auf den Fehler hindeuten könnten? (Dein geposteter Fehler sollte eigentlich keine Auswirkung auf die Funktionsweise der Brücke haben.)

**Comment by brutella** [comment]
Könntest du mal im Chrome die Console (Developer Tools → Console) auf mögliche Fehler durchsuchen?

**Comment by brutella** [comment]
https://www.google.at/search?q=chrome+konsole+öffnen 😉

**Comment by ralf-muc** [comment]
Habe ich gefunden, und was brauchst du da?
Ich bin kein Programmierer :-)
Eventuell kann ich TeamViewer anbieten?

**Comment by brutella** [comment]
Versuche das Problem zu reproduzieren und lass dabei die Konsole im Chrome geöffnet. Tauchen da Fehlermeldungen auf?

**Comment by ralf-muc** [comment]
![image](https://user-images.githubusercontent.com/96773602/150509151-eceb7b81-6975-48d9-9198-86f6e68d5594.png)
Hier?

**Comment by brutella** [comment]
Ja

**Comment by ralf-muc** [comment]
![image](https://user-images.githubusercontent.com/96773602/150509480-bbd5c6f7-79ca-4f48-a912-52a18c9b64f2.png)
2 Probleme?
Bisher läufts aber noch ....

**Comment by brutella** [comment]
Sind nur Info-Meldungen. Nur rot-markierte Meldungen sind Fehler.

**Comment by ralf-muc** [comment]
![image](https://user-images.githubusercontent.com/96773602/150509766-dfb32391-4912-46b7-bc60-933754c2fe13.png)

**Comment by ralf-muc** [comment]
Komischerweise blieb es jetzt stabil.

Soll ich es mit IOS noch ausprobieren?

**Comment by brutella** [comment]
Ja

**Comment by ralf-muc** [comment]
Ja was soll ich sagen, der Fehler ist momentan nicht mehr da :-)

**Comment by brutella** [comment]
Ist der Fehler wieder aufgetaucht?

**Comment by ralf-muc** [comment]
Leider ja, gerade am iPad getestet :-(

**Comment by ralf-muc** [comment]
Wollen wir da jetzt noch weiter nachforschen um den Fehler zu finden?

**Comment by brutella** [comment]
Der Fehler wurde gefunden. Mit der nächsten Version wird das Problem behoben.

**Comment by brutella** [comment]
Das Problem wurde in Version [2.2.1](https://github.com/brutella/hkknx-public/releases/tag/2.2.1) behoben.
