### ISSUE TITLE
Probleme mit Temperaturregelung bei MDT Heizungsaktor

### ISSUE THREAD

**Issue by dengler5000** [brutella/hkknx-public#171]
Hi, ich habe leider mit der Temperaturregelung zu kämpfen. Übernimmt die Homebridge bzw hkknx den Soll-Ist-Abgleich und regelt entsprechend das Ventil oder muss ich das über den Heizungsaktor machen, dem ich die Solltemperatur vorgebe? So habe ich das jedenfalls gerade eingestellt, jedoch passiert nicht wirklich was wenn ich die Temperatur stark erhöhe. Die Soll-Temperatur kommt zwar in ETS an, jedoch bleibt der Stellwert des Ventils bei 0,0%.

![projects_701517b2-4ff0-48c3-a221-de6764b55068_groupmon – Ope](https://user-images.githubusercontent.com/100120546/154948160-38a8b07d-6ce1-4d60-8e61-0a45ba4b1b8d.png)

**Comment by brutella** [comment]
hkknx führt keine Heizungsregelung durch. Es werden lediglich die über HomeKit eingestellten Temperaturen an KNX weitergeleitet. Die Regelung selbst, muss dann ein Heizungsaktor durchführen.

**Comment by dengler5000** [comment]
so habe ich das aktuell auch eingestellt. Im Heizungsaktor auf "integrierter Regler". Aber es tut sich nichts...

**Comment by lutz1299** [comment]
Bei MDT musst du das Objekt „Sollwert Komfort“ in die schreiben Aktion von hkknx setzen. In lesen kommt dann „Aktueller Sollwert“

**Comment by brutella** [comment]
@dengler5000 Konntest du das Problem bereits lösen?

**Comment by dengler5000** [comment]
Hi, sorry war ne Woche weg. Ja ich habe es nun so eingestellt wie @lutz1299 es beschrieben hat. Scheint für den ersten Moment zu funktionieren :)
