### ISSUE TITLE
Generate serial number for HomeKit accessories

### ISSUE THREAD

**Issue by unsaltedorg** [brutella/hkknx-public#172]
I am using [Controller](https://controllerforhomekit.com) with HomeKit and it gave the following warning:

> Each Accessory should have a unique serial number. Regrettably, many HomeBridge plugins and some HomeKit Accessory manufacturers use the same serial number for all Accessories. As a result, Controller can not tell these Accessories apart, which causes issues with custom icons, HomeKit Codes,and Backups.

All my HKKNX-bridged devices have empty serial numbers, and the serial number field isn't accessible via the web UI.

Could HKKNX generate a unique serial number automatically for each KNX device?

![image](https://user-images.githubusercontent.com/48354391/155892410-30782f62-88b2-434a-a047-79ba6336ece7.jpeg)

**Comment by brutella** [comment]
Should be fixed in [v2.2.1](https://github.com/brutella/hkknx-public/releases/tag/2.2.1)

**Comment by unsaltedorg** [comment]
Thank you! @brutella
