### ISSUE TITLE
Shutters do not work with Siri on iOS 15.4

### ISSUE THREAD

**Issue by MirkoLenz** [brutella/hkknx-public#180]
Hello,
since the latest iOS and HomePod updates (iOS 15.4) on Monday, I am no longer able to control my shutters with my voice. They work just fine when controlling them directly in the Home app, but asking Siri to close or open them gives the error that my covers do not support this feature. This bug does not seem to be isolated to your application however, since I also found a blog entry that describes the same error for the officially certified Bosch smart home system: <https://stadt-bremerhaven.de/bosch-smart-home-ios-15-4-stoert-siri-unterstuetzung-fuer-rollladensteuerung/>.

Since this seems to be a general issue, I am not sure if this is just a bug on Apple's side (which could not be fixed by you) or a general change in the HomeKit interface.

**Comment by chef76** [comment]
Fixed with 15.4.1
