### ISSUE TITLE
Skript "Meldung mit Kamerabild"

### ISSUE THREAD

**Issue by Guido1976** [brutella/hkknx-public#181]
Ist es möglich in hkknx mit den Skripten eine Meldung zu generieren und in dieser auch gleichzeitig ein Kamerabild einer IP Kamera mitzusenden?

Mit den Meldungen über den configurator und Skripten habe ich bereits genutzt. Jetzt soll bei einer gewissen Gruppenadresse ein Kamerabild mitgesendet werden.

Oder gibt es andere/bessere Möglichkeiten?

**Comment by Guido1976** [comment]
Ist es möglich in hkknx mit den Skripten eine Meldung zu generieren und in dieser auch gleichzeitig ein Kamerabild einer IP Kamera mitzusenden?

Mit den Meldungen über den configurator und Skripten habe ich bereits genutzt. Jetzt soll bei einer gewissen Gruppenadresse ein Kamerabild mitgesendet werden.

Oder gibt es andere/bessere Möglichkeiten?

**Comment by brutella** [comment]
Zurzeit ist das noch nicht möglich. Die Möglichkeit Bilder anzuhängen wäre eine tolle Erweiterung.

Wie kannst du auf deine IP Kamera zugreifen um ein Bild zu empfangen?

**Comment by Guido1976** [comment]
Momentan kann ich noch gar nicht auf die Kamera zugreifen, weil ich noch keine eingebaut habe 😀 

Also die Situation momentan ist folgende. 

Wir haben unseren Neubau komplett mit KNX gemacht, um hier schon mal offen für alles zu sein. Ich hatte vorher nix mit KNX zu tun gehabt und bin daher in diesem Bereich noch Neuling. Komme aber aus dem Bereich der Industrie Automation und bin daher kein Neuling, was grundsätzlich das Programmieren angeht.

Da wir alles von Apple haben, IPhone, Iwatch, IPad, HomePod, AppleTV, war klar, dass wir unser KNX mit HomeKit steuern wollten. Dazu haben wir uns das Raspberry Pi zugelegt und ich habe mir deine Lizenz für hkknx gekauft. Das ganze habe ich letzte Woche eingerichtet und bin auch schon ziemlich begeistert. Wie gesagt, das mit deinen Skripten habe ich mir auch gleich mal angeschaut und bisschen rumgespielt. Nachrichten habe ich mir auch schon mal generiert. Das klappt schon mal 😀

Jetzt steht eben noch die Entscheidung an, was ich mit der Türklingel mache, da ich noch keine habe.

Ich habe an der Haustür Netzwerk- und KNX Kabel liegen. Ich habe im Internet versucht zu recherchieren, was für mich in Frage käme und komme dabei einfach auf keinen grünen Zweig 🤦🏻‍♂️.

Eine Möglichkeit wäre vielleicht. Einfachen Klingeltaster auf KNX Binäreingang verdrahten. Aktorausgang auf einen Gong im Flur. Mit der Gruppenadresse und deinem Skript mir eine Message zu senden. Daher meine Frage, wie ich das ganze mit einem Bild versehen kann und was ich dafür für eine Kamera brauche. Die Meldung mit Bild soll auch auf meinem AppleTV ankommen.

Die andere Möglichkeit wäre dann eben eine fertige Videotürklingel, die Apple HomeKit fähig wäre. Ich habe aber noch nicht die "Eierlegende Wollmilchsau" gefunden. 
Ein System, das bezahlbar ist,
Stromversorgung mit PoE und Anbindung über LAN und nicht WLAN,
Gong über einen potentalfreien Kontakt,
usw.

Vielleicht hättest du ja eine Idee? Ich habe gesehen, du hast ja auch ein System "hkcam", wäre das eine Möglichkeit mit meinem vorhandenen Raspberry? Geht das auch über LAN oder nur USB? 

Gruß Guido

**Comment by brutella** [comment]
Mir geht es genauso wie dir. Unser EFH wird auch mit KNX umgesetzt und die HomeKit Brücke ist unsere Schnittstelle zu iPhone, iPad und Apple TV. 

Eine gute All-In-One Türstation mit KNX Anbindung hab ich bis jetzt keine gefunden. Meine Anforderungen sind halt auch etwas speziell, da ich keine Gegensprechanlage brauche sondern nur zwei Klingeln, eine Zugangskontrolle (Code-Eingabe) und eine Kamera. 

Daher werde ich mir das selbst zusammenbasteln. 

Dazu verwende ich einen Gira 021467 Rahmen. Zwei einfache Taster dienen als Klingeltaster und werden mit einer KNX-Tasterschnittstelle abgegriffen. Beim Drücken wird ein Hugomüller AS 26.01 KNX Gong angesteuert.

Als Kamera verwende ich mein [hkcam](https://github.com/brutella/hkcam) Projekt, welches auf einem Raspberry Pi läuft und auf eine [ELP 1080P USB Kamera](https://de.aliexpress.com/item/32274943813.html) zugreift. (Ob ich das Kabel der USB Kamera bis in den Schaltschrank mit einem CAT7-Kabel verlängern kann, muss ich noch ausprobieren. Ansonsten sitzt der Raspberry Pi halt in einer UP-Dose – ist alles vorbereitet.)

Für den Gira Rahmen gibt es eine [Kamera-Abdeckung](https://www.voltus.de/schalterprogramme/gira/tx-44/sonstiges/gira-141567-abdeckung-fuer-farbkamera-tx-44-anthrazit.html). Dahinter werde ich irgendwie das Kamera-Modul reinpacken.

Wenn dann [hkcam](https://github.com/brutella/hkcam) läuft, kann ich einfach über eine HTTP-Get URL das Kamerabild abrufen. (Diese Funktion wurde in [hkcam](https://github.com/brutella/hkcam) noch nicht eingebaut. Werde ich aber bald implementieren.)

(Wie ich die Zugangskontrolle löse ist ein ganz anderes Thema, welches ich vermutlich mal in einem Blog-Post niederschreibe.)

Somit haben ich meine HomeKit-Kamera und KNX Türstation.

**Comment by Guido1976** [comment]
Mit dem Audio brauche ich auch nicht. 

Muss die Kamera denn zwingend über USB an den Raspberry angeschlossen sein? Eine IP Kamera wäre ja schon eleganter. USB ist ja auch mit den Leitungslängen schon sehr begrenzt. Bei mir sind es auf jeden Fall mehr als 5m von der Klingel bis zur Verteilung mit dem Raspberry.

Bekomme ich denn auch dann irgendwie einen Klingelton aus dem HomePod raus?

**Comment by brutella** [comment]
> Muss die Kamera denn zwingend über USB an den Raspberry angeschlossen sein? Eine IP Kamera wäre ja schon eleganter. USB ist ja auch mit den Leitungslängen schon sehr begrenzt. Bei mir sind es auf jeden Fall mehr als 5m von der Klingel bis zur Verteilung mit dem Raspberry.

Nein, muss nicht zwingend sein. Man könnte hkcam auch so anpassen, dass ein RTSP Stream abgegriffen werden kann.

> Bekomme ich denn auch dann irgendwie einen Klingelton aus dem HomePod raus?

Ja, das sollte mit einer HomeKit Automation funktionieren.
https://www.imore.com/how-use-homepod-homekit-alarm

**Comment by Guido1976** [comment]
Was bedeutet, man kann hkcam so anpassen. Du müsstest die Software umprogrammieren oder kann der Nutzer hier was einstellen?


Das mit der Audioausgabe auf dem HomePod probiere ich später mal aus.

**Comment by brutella** [comment]
hkcam müsste umprogrammiert werden um RTSP Streams verwenden zu können. Aktuell wird nur eine Kamera unterstützt, die direkt mit dem Computer verbunden ist – zB via USB. Womöglich könnte man auch eine Kamera über Ethernet anschließen, aber davon hab ich keine zum testen.

**Comment by MirkoLenz** [comment]
Bei mir gibt es quasi die gleiche Ausgangssituation: Wir haben die gesamte Elektrik eines Altbaus erneuert und dabei auch KNX verwendet. Bei der Klingel stand ich vor dem gleichen Problem wie ihr. Ich habe das so gelöst:

Zur Klingel habe ich einmal ein Netzwerkkabel (derzeit nicht in Verwendung) und einmal ein ganz normales Klingelkabel gelegt. In jedem Stockwerk gibt es dann auch ein Klingelkabel zentral im Flur, das direkt in den Verteiler läuft. Das Klingelkabel der Haustür ist an einen potentialfreien Binäreingang angeschlossen, die restlichen Klingelkabel an einen Schaltaktor.

Als Klingel verwende ich die [Unifi Doorbell G4](https://eu.store.ui.com/collections/unifi-protect/products/uvc-g4-doorbell). Diese hat die Möglichkeit, ein Schaltsignal auf ein bestehendes Klingelkabel zu senden. Gleichzeitig habe ich die Doorbell via Homebridge an HomeKit angebunden und erhalte dadurch automatisch bei jeder Betätigung eine interaktive Benachrichtigung auf meine Geräte. Dort wird dann ein Screenshot angezeigt und wenn man auf die Benachrichtigung tippt startet sofort der Livestream mit Gegensprechfunktion.

Man muss dafür auch nicht zwingend die Unifi Doorbell nutzen, sondern kann jede beliebige Videoklingel nehmen, die ein Schaltsignal senden kann (bspw. auch die [Robin ProLine](https://www.robin.nl/de/produkte/robin-proline-de.html)). Mit dieser würde das ganze sogar ohne Homebridge funktionieren.

Ich bin damit sehr zufrieden. Sollte es mal Softwareprobleme geben (ist bisher einmal bei einem Unifi-Update vorgekommen), dann funktionieren immer noch die Gongs im Haus und man steht nicht "dumm" da.

**Comment by brutella** [comment]
Die Konfiguration Version 1.2.2 ist jetzt offiziell im App Store verfügbar und hkknx Version 2.3.0 ist auch verfügbar.
