### ISSUE TITLE
Flashvorgang auf 16GB microSD Karten für RaspberryPi schlägt immer fehl.

### ISSUE THREAD

**Issue by 71z0** [brutella/hkknx-public#183]
Auf ["https://hochgatterer.me/de/hkknx/docs/install/rpi-img/"](https://hochgatterer.me/de/hkknx/docs/install/rpi-img/) habe ich gelesen "_Die SD-Karte muss mindestens eine Kapazität von 16GB haben._"

Nach 4 verschiedenen **16GB Sandisk Extreme microSD** Karten und 2 verschiedenen microSD-Adaptern habe ich daran meine Zweifel.
Sowohl der Raspberry Pi Imager als auch der Balena Etcher brechen den Flashvorgang bei 99% mit einer Fehlermeldung ab.

Entpacke ich das GZip Archiv **2021-05-21_raspio-lite_hkknx-1.3.0_linux_arm.img.gz** zuerst und versuche das darin liegende Image **2021-05-21_raspio-lite_hkknx-1.3.0_linux_arm.img** dann auf eine der 4 Karten zu flashen, erhalte ich sofort die Meldung, die SD Karte sei zu klein. Eine der 4 Karten ist fabrikneu, die anderen 3 liefen/laufen in anderen PIs tadellos.

Mache ich einen Fehler? Oder benötigt das 1.3.0 Raspberry Pi release möglicherweise etwas mehr als 16GB?

**Comment by brutella** [comment]
Für [Version 2.6.0](https://github.com/brutella/hkknx-public/releases/download/2.6.0/2023-02-27-raspio-lite_hkknx-2.6.0_linux_arm.img.gz) gibt es jetzt ein neues Raspberry Pi Image. Bitte versuche das neue Image auf eine SD-Karte zu laden, so wie es [im Online Handbuch beschrieben](https://hochgatterer.me/de/hkknx/docs/install/rpi-img/) ist.
