### ISSUE TITLE
"Speichern" leitet auf "localhost" weiter

### ISSUE THREAD

**Issue by curana** [brutella/hkknx-public#185]
Wenn ich in den Einstellungen auf "Speichern" klicke, leitet hkknx auf die URL "http://localhost/projects/.../settings?msg=Änderungen+gespeichert" weiter.

Ich habe hkknx als Docker Image laufen.

Gibt es noch andere mit diesem Problem?

**Comment by brutella** [comment]
Ups, das Problem ist in Version [2.3.1](https://github.com/brutella/hkknx-public/releases/tag/2.3.1) behoben.
