### ISSUE TITLE
Taster

### ISSUE THREAD

**Issue by Mikergbg** [brutella/hkknx-public#186]
Hallo!
Wie ist es möglich einen Taster aus dem KNX Projekt in HomeKit zu importieren und letztendlich in Homekit dann zu programmieren.
Der punkt Schalter war bis jetzt nicht hilfreich, da dieser ja nur eine vorher definierte Aktion ausführt.
Mein ziel ist es, über einen Schalter der in KNX eingebunden ist NanoLeafs zu steuern.
Lg

**Comment by Mikergbg** [comment]
Ich habe leider die Taster option nicht
![taster](https://user-images.githubusercontent.com/104915923/166716805-3ee3a737-9ee7-4ab8-a138-2502fd538ad9.PNG)
.

**Comment by brutella** [comment]
Welche Version von hkknx hast du installiert? Taster gibt es seit Version [2.3.0](https://github.com/brutella/hkknx-public/releases/tag/2.3.0).

**Comment by chef76** [comment]
> Die Option Schalter in dem Screenshot, lässt nur einen Virtuellen Schalter erstellen, der dann eine KNX adresse Steuert.

Der Schalter ist ein echter Schalter den du in beiden Welten bedienen und abfragen kannst:

![image](https://user-images.githubusercontent.com/69462419/166722788-4cf143a3-91a5-43cd-9782-23df5cafd4c7.png)

So steuere ich meine Nanoleafs schon immer mit einem KNX-Taster

**Comment by Mikergbg** [comment]
Stimmt! Ich habe eine ältere Version ...
Jetzt kann ich mich jedoch nicht per SSH einloggen. pi und raspberry funktioniert nicht. wurden diese login daten bei dem Raspberry image geändert?

**Comment by brutella** [comment]
Updates können auch über die Weboberfläche installiert werden.
https://hochgatterer.me/de/hkknx/docs/install/update/

**Comment by Mikergbg** [comment]
habe ich bereits probiert. Jedoch ist leider die Zeit noch falsch. Auch nach dem neustarten. :(

**Comment by brutella** [comment]
Die Anmeldedaten für das vorgefertigte Raspberry Pi Image stehen im Online Handbuch ganz unten.
https://hochgatterer.me/de/hkknx/docs/install/rpi-img/

**Comment by Mikergbg** [comment]
Vielen dank! Hat geklappt. Da war ich wohl etwas blind beim durchlesen...
