### ISSUE TITLE
KNX Gateway Gira X1 

### ISSUE THREAD

**Issue by holli17** [brutella/hkknx-public#188]
Hallo,
ich komme nicht weiter...
Ich habe alles soweit installiert und möchte nun über den Gira X1 als Gateway auf meine KNX Installation zugreifen. Ich nutze bereits "Homebridge" und habe zu Testzwecken mal "Symcon" installiert. Beides funktioniert. bei "hkknx" habe ich das Problem, dass der X1 wohl nur kurz ( ca. 1 Minute ) erreichbar ist. Ich habe mir die app"Discovery" geladen. Hier werden unter "Hap._tcp." alle Verbindungen angezeigt. Die zu hkknx passende aber nur für ca. 1 Minute. Die Zeit reicht nicht, um unter Apple Home die Bridge zu installieren.  Wo ist mein gedanklicher Fehler? Viele Dank für die Hilfe.
KNX1
16EDEFC3B85.local:51447
192.168.1.17
TXT Record
C# = 2
ci = 2
ff = 0
id = 16:E1...
md = KNX1
pV = 1.0
s# = 1
sf = 1
sh = ByMqLQ==

Der Status ist alles auf grün. Wenn ich die Brücke deaktiviere und sie nach dem speichern wieder aktive, dann habe ich diese für ca. 1 Minute ...

**Comment by brutella** [comment]
Das hört sich nach einem Netzwerkproblem an. Hast du Multicast in deinem Netzwerk aktiviert?

**Comment by holli17** [comment]
Danke  für die Idee. ich nutzte uniFi Dream Maschine und habe dort Multicast DNS und IGMP Snooping beides aktiviert. Allerdings muss ich in den Einstellungen des hkknx die IP für den Gateway direkt eintragen, eine automatische Suche funktioniert nicht...

**Comment by brutella** [comment]
Wenn die automatische Suche nicht funktioniert, dann hast du wohl Port `3671` oder die Multicast Adresse `224.0.23.12` gesperrt. Lies dir bitte mal dazu den Eintrag im Online Handbuch nach. 
https://hochgatterer.me/de/hkknx/docs/config/knx-connection/

**Comment by holli17** [comment]
allo,
den Verdacht hatte ich auch schon, habe diesen aber eigentlich verworfen da nebenbei noch „Homebridge“ läuft und vor allem auch noch Symcon läuft. Dieses ist ähnlich wie hkknx aufgebaut ( meine ich ) und funktioniert. Aber auch hier kann keine automatische Suche nach dem Gateway erfolgen.

Ich habe mir daher mal eine FritzBox zum testen einer Alternative zu meinem UniFi Router geliehen und neu aufgesetzt. Die hkknx habe ich neu auf einem MacBook installiert.
Leider keine Änderungen— auch hier nur für ca. eine Minute in der App „DNS-SD Browser“ sichtbar!

hier mal einige Bilder meiner Einstellungen.

Vermutlich mache ich nur einen dummen Fehler auf den ich nicht komme…

**Comment by brutella** [comment]
Versuch's mal mit dem aktuellen Build von Version 2.3.1.

**Comment by brutella** [comment]
Versuch ausserdem mal einen fixen Port für die HomeKit Brücke unter Einstellungen → HomeKit Brücke → Port zu vergeben, zB `54321`.

**Comment by holli17** [comment]
Hallo,
den Verdacht hatte ich auch schon, habe diesen aber eigentlich verworfen da nebenbei noch „Homebridge“ läuft und vor allem auch noch Symcon läuft. Dieses ist ähnlich wie hkknx aufgebaut ( meine ich ) und funktioniert. Aber auch hier kann keine automatische Suche nach dem Gateway erfolgen.

Ich habe mir daher mal eine FritzBox zum testen einer Alternative zu meinem UniFi Router geliehen und neu aufgesetzt. Die hkknx habe ich neu auf einem MacBook installiert.
Leider keine Änderungen— auch hier nur für ca. eine Minute in der App „DNS-SD Browser“ sichtbar!

hier mal einige Bilder meiner Einstellungen.

Vermutlich mache ich nur einen dummen Fehler auf den ich nicht komme…

**Comment by brutella** [comment]
@holli17 Könntest du bitte mal die aktuellste Version 2.5.1-b3 installieren und es nochmals probieren.

**Comment by holli17** [comment]
Moin, ich habe die X1 mittlerweile verkauft. Ich habe einen alten MacMini reaktiviert und dort läuft alles ohne Gira gut. Ferner habe ich die X1 gegen die MDT SNC-IP003 getauscht. Auch meine S1 und die G1 haben dank eBay ein neues zuHause.   Nutze jetzt voll Apple. Das iPad für die Wand bestelle ich am WE und werde dann versuchen, dass meine Gira TKS Videoanlage damit läuft. Im Augenblick klingelt es nämlich nicht, was abgesehen von der schlechten Qualität des Video nervt.

Danke und ein schönes WE
