### ISSUE TITLE
Status Werte von Rolladen werden in der Home App wird nicht aktualisiert 

### ISSUE THREAD

**Issue by sberer** [brutella/hkknx-public#19]
Ich habe eine Rolladen wie folgt eingebunden

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/20122720/75602875-7f5dc700-5ac9-11ea-873a-edbf84f65ec8.png">

Die Bedienung funktioniert, jedoch wird der Status in der Home App nicht korrekt angezeigt. Obwohl sich die Raffstore nicht mehr bewegen wird noch immer "Closing ..." angezeigt. 

<img width="117" alt="image" src="https://user-images.githubusercontent.com/20122720/75602854-47ef1a80-5ac9-11ea-85e4-56accd81340e.png">

**Comment by brutella** [comment]
Welcher Wert wird an die Gruppenadresse 2/5/0 (Ist-Position) gesendet, wenn der Rolladen die Soll-Position erreicht?

**Comment by brutella** [comment]
Closed due to inactivity

**Comment by chef76** [comment]
... selbes Problem wie hier das 2. Problem:

https://github.com/brutella/hkknx-public/issues/61
