### ISSUE TITLE
Hinzufügen der Brücke ab 2.3.0 nicht möglich

### ISSUE THREAD

**Issue by mbrockeu** [brutella/hkknx-public#192]
Ich teste gerade mit der Anleitung von den Container rum und habe die Version für mich mal auf den aktuellen Stand gebracht.

Dabei ist mir aufgefallen, dass ab der Version 2.3.0 ich die Brücke nicht neu hinzufügen kann und wenn diese vorher mit der 2.2.0 hinzugefügt wurde diese dann keine Rückmeldung mehr auf die Geräte bringt.

Kann das Problem noch jemand nachvollziehen?

**Comment by mbrockeu** [comment]
Danke das hat geholfen!

**Comment by brutella** [comment]
@chef76 Verstehe ich das richtig, dass die TCP Kommunikation bei dir Probleme macht? Siehst du in den Log-Ausgaben Fehlermeldungen, wenn du auf TCP umstellst?

**Comment by chef76** [comment]
Mein Gateway kann einfach nur UDP. Ich hab da auch nicht weiter nachgeforscht und einfach wieder auf UDP gestellt.

**Comment by mbrockeu** [comment]
Ich habe gerade mal versucht, ob er über TCP irgendwas in die Konsole schreibt oder in die Logs. Kann da jetzt nix erkennen. Außer, dass jetzt offenbar gar keine Verbindung mehr zum X1 hergestellt werden kann. Weder TCP noch UDP.
In den Logs sagt er merkwürdigerweise, dass er keine Verbindung aufgebaut hat:

INFO 2022/07/04 19:21:24 app.go:333: tunnel: connected to 192.168.4.152:3671 via 1.1.252

**Comment by brutella** [comment]
@mbrockeu Dann scheint der X1 kein TCP und daher auch keine Secure Tunnelling zu unterstützen.

**Comment by mbrockeu** [comment]
Musste jetzt einmal Container auf 2.2.0 starten damit ich überhaupt wieder eine Verbindung bekomme. Danach wieder auf 2.3.1 dann geht es auch direkt. In den Einstellungen steht dort TCP, wenn man dann speichert geht die Verbindung nicht, dann muss man auf UDP dann geht es auch. Komischerweise haben meine Versuche davor nix gebracht und es war die ganze Zeit down.

**Comment by mbrockeu** [comment]
> > @mbrockeu Dann scheint der X1 kein TCP und daher auch keine Secure Tunnelling zu unterstützen.
> 
> Der X1 sollte TCP problemlos unterstützen. Zu Secure Tunneling habe ich keinerlei Info gefunden!

Funktioniert es den bei dir?
Ich kann es bei mir jedenfalls immer wieder reproduzieren, dass er sobald ich ab 2.3.0 mit TCP speichere die Einstellungen er mir um die Ohren fliegt. Mit 2.2.0 wo man nix auswählen kann verbindet wieder korrekt. Dann dort einmal speichern und wieder auf 2.3.1.

Wäre ja mal interessant ob es nur am X1 liegt.

**Comment by brutella** [comment]
Ich hab jetzt für Version 2.3.1 einen neuen Build hochgeladen. Bitte damit mal ausprobieren.

**Comment by mbrockeu** [comment]
> Ich hab jetzt für Version 2.3.1 einen neuen Build hochgeladen. Bitte damit mal ausprobieren.

Habe jetzt zumindest mit der Einstellung TCP eine Verbindung zum X1, Bridge scheint auch zu gehen und in HomeKit ist auch alles ok. Danke
