### ISSUE TITLE
Taster-Konfiguration

### ISSUE THREAD

**Issue by fuji4** [brutella/hkknx-public#193]
Hallo,
ich würde gern einen Taster mit 2 Tasten konfigurieren, der beim Druck auf eine Taste 0 oder 1 an eine definierte Gruppenadresse schickt. Ich scheitere jetzt aber an der Konfiguration, weil ich in HK-KNX ja nur "Lesen"-Felder hab, wo ich Gruppenadressen einstellen kann.

Außerdem hab ich noch das Problem, dass sobald ich einen Taster anlege, das HK-KNX abstürzt (auch wenn die Taster-Konfiguration komplett leer ist).

**Comment by fuji4** [comment]
HK-KNX stürzt ab, sobald ich einen Taster anlege - da reagiert dann gar nix mehr...
`Apanic: runtime error: index out of range [45] with length 24

goroutine 46 [running]:
github.com/brutella/hkknx/app.(*app).accessoriesInProject.func2(0x2d, 0x22, 0x4000739500)
	/Users/mah/Source/Code/Go/src/github.com/brutella/hkknx/app/app.go:755 +0xb4
sort.medianOfThree_func(0x4000739c60, 0x4000810c60, 0x2d, 0x22, 0x38)
	/usr/local/opt/go/libexec/src/sort/zfuncversion.go:53 +0x38
sort.doPivot_func(0x4000739c60, 0x4000810c60, 0x0, 0x5b, 0x40007395b8, 0xbeb00)
	/usr/local/opt/go/libexec/src/sort/zfuncversion.go:77 +0x468
sort.quickSort_func(0x4000739c60, 0x4000810c60, 0x0, 0x5b, 0xe)
	/usr/local/opt/go/libexec/src/sort/zfuncversion.go:143 +0x80
sort.Slice(0x75eaa0, 0x400068d050, 0x4000739c60)
	/usr/local/opt/go/libexec/src/sort/slice.go:20 +0xdc
github.com/brutella/hkknx/app.(*app).accessoriesInProject(0x4000254ea0, 0x40001f2b00, 0xb96a78, 0x40003606f0, 0x400078e3c8, 0x40005fb56c, 0x2, 0x0)
	/Users/mah/Source/Code/Go/src/github.com/brutella/hkknx/app/app.go:754 +0x3be0
github.com/brutella/hkknx/app.(*app).Run.func2(0xb8e088, 0x40003662c0, 0x4000254ea0, 0x40001f2b00, 0x40003606f0, 0x40004d2ff0)
	/Users/mah/Source/Code/Go/src/github.com/brutella/hkknx/app/app.go:368 +0x214
created by github.com/brutella/hkknx/app.(*app).Run
	/Users/mah/Source/Code/Go/src/github.com/brutella/hkknx/app/app.go:356 +0x4d8`
Das passiert bereits wenn ich einen Taster
![Bildschirmfoto 2022-07-13 um 13 43 00](https://user-images.githubusercontent.com/1442410/178726369-16fd62c8-4ebf-434e-a949-29fe1bb71947.png)
 anlege, nichts weiter konfiguriere und auf Speichern klicke.

Zum Konfigurationsproblem: Wenn ich versuche die gewünschte Gruppenadresse zuzuordnen, krieg ich den Fehler "Falscher Datentyp" - siehe Screenshot.

**Comment by chef76** [comment]
Zum Absturz kann ich nichts sagen, das müsste @brutella mal anschauen.

Ist die GA in der ETS für den Datentyp konfiguriert? Manchmal kommt bei der Eingabe der Fehler und wenn man das Feld mit Tab verlässt, wird es grün.

**Comment by brutella** [comment]
> Hallo, ich würde gern einen Taster mit 2 Tasten konfigurieren, der beim Druck auf eine Taste 0 oder 1 an eine definierte Gruppenadresse schickt. Ich scheitere jetzt aber an der Konfiguration, weil ich in HK-KNX ja nur "Lesen"-Felder hab, wo ich Gruppenadressen einstellen kann.

Ein Taster ist dafür nicht geeignet. Mit einem Taster kann du einen Tastendruck in KNX mit einer Aktion in HomeKit verknüpfen. Ein Taster kann nicht von HomeKit aus bedient werden.

Verwende stattdessen einen [Schalter](https://hochgatterer.me/de/hkknx/docs/accessories/switch/). Dieser kann über HomeKit geschaltet (also gedrückt) werden.

> Außerdem hab ich noch das Problem, dass sobald ich einen Taster anlege, das HK-KNX abstürzt (auch wenn die Taster-Konfiguration komplett leer ist).

Dieses Problem kann ich nicht nachvollziehen. Welche Version von hkknx verwendest du?

**Comment by fuji4** [comment]
> Dieses Problem kann ich nicht nachvollziehen. Welche Version von hkknx verwendest du?

hkknx 2.3.0 auf Ubuntu 20.04.4 LTS auf einem Raspberry Pi 4 Model B

**Comment by fuji4** [comment]
Ja, ich mach zu
