### ISSUE TITLE
Fine-Granular Release Management

### ISSUE THREAD

**Issue by mirkolenz** [brutella/hkknx-public#195]
Hi!
I use this app via a Docker container and set up notifications on GitHub gor every new release. I noticed that you update new builds directly into old releases. This poses the following issues for me:

- I do not get a notification for new build.
- It is not possible to roll-back to a previous build if I encounter a new bug.
- The exact changes between builds are "merged" with existing changes.
- Hashes cannot be compare reliably if the binary files change.
- I need to clear any caches for my Docker images to force a new download for the new version number.

My suggestion would be to append a build number or (preferably) add something like "a1, "b2" (for alpha/beta version) to the version number of any pre-release. Then, once the pre-release is the new stable, create a new release without such a suffix. This scheme should resolve all of the issues mentioned above.

Keep up your great work!

**Comment by brutella** [comment]
I've renamed the current pre-release to 2.3.1-b1 which includes a fix for #198.
The next pre-release will then be 2.3.1-b2. 
The final release will be 2.3.1.

**Comment by mirkolenz** [comment]
Great, that solves all of the mentioned issues 😄
