### ISSUE TITLE
Bug Temperaturmesser

### ISSUE THREAD

**Issue by chef76** [brutella/hkknx-public#196]
Versucht man einen Temperaturmesser in eine Automation einzubinden erhält man nur abstruse Temperaturwerte:
![image](https://user-images.githubusercontent.com/69462419/179345687-fe5b0c60-66d2-4830-a38a-f03968ec1437.png)

Macht man dasselbe mit einem Temperaturregler, passt es:
![image](https://user-images.githubusercontent.com/69462419/179345726-760a5a61-9caf-4955-863c-f59fcf8380b7.png)

Die Datentypen sind bei beiden definiert

Hier zum Vergleich ein EveWeather:

![image](https://user-images.githubusercontent.com/69462419/179348196-cf0bdf3a-a720-45fe-9d11-9a926186d71a.png)

**Comment by brutella** [comment]
Tritt das Problem auch bei anderen HomeKit-Apps auf oder nur in der Apple Home-App?

**Comment by chef76** [comment]
Bist Du sicher, dass es daran liegt? Dann müsste das Problem bei Temperaturreglern doch auf auftreten oder hast Du da den Bereich begrenzt? Im Prinzip müssest Du meiner Meinung nach den Temperaturmesser genauso implementieren, wie es beim der Ist-Temperatur des Reglers gemacht ist.

Eine Beobachtung noch: Wenn ich die Automation mit demselben Wert in der Eve-App (der Screenshot oben ist aus der Koogeek-App)erstelle, dann werden die Temperaturen in der Eve-App korrekt angezeigt, z.B. 23 °. Öffnet man dann aber die erstellte Automation in Home, dann steht als Temperatur -4,5°

Ein sinnvoller Bereich wäre wohl -30° bis +50°

**Comment by brutella** [comment]
Ok, in [2.3.1-b2](https://github.com/brutella/hkknx-public/releases/tag/2.3.1-b2) kann man für die Ist-Temperatur `-50...100°C` oder `-273 °C ... 670 760 °C` auswählen.
Für die Soll-Temperatur stehen `10...38°C`, `-50...100°C` und `-273 °C ... 670 760 °C` zur Auswahl. Der Wertebereich `10...38°C` ist in HomeKit Standard für die Soll-Temperatur.

**Comment by chef76** [comment]
o.k, für die Temperaturmesser funktioniert es so, wenn ich -50 - 100 auswähle, allerdings kann ich in Homekit die Regler jetzt nicht mehr aufrufen. Wenn man einen Regler auswählt stürzt Home ab. Nur wenn man bei Ist-Temperatur = Soll-Temperatur = -50 -100 wählt, dann gehts wieder. Bei unterschiedlichen Datentypen krachts. Vielleicht kannst Du noch einbauen, dass der Datentyp beim Update automatisch gesetzt wird, denn sonst sehe ich das Forum schon wieder explodieren und ich hab auch keine Lust das jetzt bei allen meinen Reglern von Hand zu setzten. :-) Danke!

**Comment by brutella** [comment]
> Nur wenn man bei Ist-Temperatur = Soll-Temperatur = -50 -100 wählt, dann gehts wieder

Hm, unter iOS 16 stürzt in der Home-App nichts ab.

> Vielleicht kannst Du noch einbauen, dass der Datentyp beim Update automatisch gesetzt wird

Hab eine neuen Build von 2.3.1-b2 hochgeladen. Bei vorhandenen Geräten wird der Wertebereich jetzt nicht geändert. Das heißt bei Ist-Temperaturen ist der Wertebereich 0...100°C und bei Soll-Temperaturen 10...38°C. Also genau wie vorher, nur das die Ist-Temperaturen jetzt eine kleinerenn Wertebereich haben.

**Comment by chef76** [comment]
Probier ich dann aus, aber das hatte ich eben auch von Hand eingestellt und dann hat's nicht funktioniert. 🤔

**Comment by chef76** [comment]
Ok, die anderen Regler funktionieren wieder, aber die Anzeige in HKKNX passt nicht dazu:

![image](https://user-images.githubusercontent.com/69462419/180024363-b1219018-a2c5-40dd-85b8-db407a92a1c7.jpeg)

Find ich mit dem Wissen, welches ich in dem Issue gesammelt habe etwas verwirrend, aber von mir aus ist es so o.k.

Danke!

**Comment by chef76** [comment]
... für mich auch o.k. 👍

**Comment by brutella** [comment]
So, hab jetzt [2.3.1-b2](https://github.com/brutella/hkknx-public/releases/tag/2.3.1-b2) nochmal neu hochgeladen und die Wertebereiche sind jetzt so wie es im [Release](https://github.com/brutella/hkknx-public/releases/tag/2.3.1-b2) steht.
