### ISSUE TITLE
Allow inverting cover position

### ISSUE THREAD

**Issue by mirkolenz** [brutella/hkknx-public#198]
I have two marquees installed at my house. In HomeKit, they are highlighted as being open when they are actually closed. The same behavior is also true for Home Assistant. There however, I have the [option to invert the values of all properties](https://www.home-assistant.io/integrations/knx/#invert_updown) and thus I am able to solve the problem. In HKKNX, it is currently only possible to invert the up/down behavior, but not the absolute position.

As a workaround, I also tried to invert the position on the KNX actuator. In this case however, the automatic shading function no longer works since the actuator "thinks" that the cover is already fully closed.

Thus, I propose to add the new value type `DPST-5-1 (100..0%)` (maybe with slightly different naming) for the properties `Jalousie Ist-Position` and `Jalousie Soll-Position` (maybe also the corresponding slat positions for the sake of completeness).

**Comment by brutella** [comment]
So your actuator uses a value of `0%` to fully extend the marquees and `100%` to fully wind it up?

**Comment by mirkolenz** [comment]
No, the opposite is true (just like for regular covers). But for a marquee, HomeKit should report the position `0%` as closed and `100%` as open.

**Comment by brutella** [comment]
This should now be possible in [2.3.1-b1](https://github.com/brutella/hkknx-public/releases/tag/2.3.1-b1)

**Comment by mirkolenz** [comment]
The app is not able to establish a connection to the HKKNX server (even though the correct host and port are entered).

**Comment by mirkolenz** [comment]
It says `Connection Problem. Unable to connect to IP:PORT`.

**Comment by mirkolenz** [comment]
I just figured out the problem: My phone somehow connected to my guest Wi-Fi network that has no access to my internal VLAN. So it was an issue on my side. Sorry for any inconveniences caused!
