### ISSUE TITLE
Ability to "forward" group monitor logs to file

### ISSUE THREAD

**Issue by hahasagined** [brutella/hkknx-public#199]
Hello,

I would love to store my knx bus telegrams and HKKNX does have a connection to the gateway and is able to decode messages. The data is in hkknx and I see the bus monitor working perfectly, I would like to put the output of the bus monitor into a file that can then be ingested in splunk, elastic, ... for visualisation and search.

Thank you,
Martin

**Comment by brutella** [comment]
In version 2.4.0 you can use [GroupWriteTelegramNotify](https://hochgatterer.me/pkg/hkknx/#GroupWriteTelegramNotify) in a script to receive all group write telegrams. You can then forward the telegram to an external service (ex. InfluxDB) or store it on disk.

Hope this helps.
