### ISSUE TITLE
Gruppierung von Geräte zu Räumen in der Home App

### ISSUE THREAD

**Issue by sberer** [brutella/hkknx-public#20]
Aktuell müssen neu hinzugefügte Geräte per Hand in der iOS Home App zu Räumen zugeordnet werden.
Wäre es möglich die Zuordnung bereits beim Anlegen eines neuen Geräte zu definieren?

**Comment by brutella** [comment]
Leider kann eine HomeKit Brücke die Räume in HomeKit nicht verändern.
Man müsste dafür eine iOS App entwicklen, die die Räume von KNX in HomeKit erstellt und die Geräte direkt den Räumen hinzufügt.
