### ISSUE TITLE
Downgrade über Web-Frontend

### ISSUE THREAD

**Issue by chef76** [brutella/hkknx-public#203]
Hallo Matthias,

Ich denke es wäre eine gute Idee im Web-Frontend eine Downgrade Option einzubauen, entweder durch Hochladen des gewünschten Files oder durch Auswahlliste. So tun sich Anwender die mit dem Raspi nicht so fit sind echt schwer.

https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1468592-homekit-br%C3%BCcke-f%C3%BCr-knx?p=1790982#post1790982

**Comment by brutella** [comment]
Ab Version [2.6.0-b1](https://github.com/brutella/hkknx-public/releases/tag/2.6.0-b1) kann man eine beliebige Version herunterladen und installieren. Downgrades sind somit auch möglich.
