### ISSUE TITLE
Automatic HKKNX update

### ISSUE THREAD

**Issue by gisbertpeter** [brutella/hkknx-public#213]
At my configuration the new software release v2.4.0 is installed automatically and is activ at a new restart. 
I want to stay with v2.2.0. How is it possible to deactivate the automatic installation?

**Comment by gisbertpeter** [comment]
This is due to the issue https://github.com/brutella/hkknx-public/issues/204

**Comment by brutella** [comment]
You can disable auto updates by running hkknx with the command `--autoupdate=false`.
