### ISSUE TITLE
Nach "Datensicherung Importieren..." keine Erweiterungen mehr möglich

### ISSUE THREAD

**Issue by MarinoKNX** [brutella/hkknx-public#216]
Vorab: Bisher nutzte ich schon über 2 Jahre HKKNX und nutze es seit Beginn in der Dockerumgebung. Ich wollte mit HKKNX umziehen und testen, wie gut eine zweite Instanz gleichzeitig läuft. Also habe ich nebenbei alles aufgesetzt und es lief.

Also Datensicherung (von 2.4.1) erstellt und Lizenz raus gelöscht, da diese ja woanders benutzt werden sollte und Tests zeigten, dass es läuft, anschließend den ursprünglichen Docker gelöscht.
Also habe ich zwei parallele Instanzen gestartet (v.2.4.1). Alles gut soweit. Datensicherung in die erste Instanz importiert, klappt. Lizenz ist bereits drin. Okay, in zweiter Instanz die Brücke zu HomeKit hinzugefügt und testweise eine Lampe eingefügt. Klasse, funktioniert. In meiner ersten (Haupt-)Instanz habe ich 103 Geräte und ich wollte noch eines hinzufügen. Ein paar Tage zuvor habe ich noch einen Schalter hinzugefügt, was funktionierte. Lampe hinzugefügt und "Testlampe" genannt. Komisch, warum sehe ich die nicht in HomeKit? Nichts aktualisiert. Also mit iPhone auf's Webinterface und auf "Jetzt Synchronisieren" geklickt und anschließend mit "öffnen" das Öffnen der Configurator App bestätigt. Die App sucht Geräte und dann eine Fehlermeldung:
"Fehler: Accessory Testlampe not found"

Ich bekomme keine neuen Geräte hinzugefügt. Die zweite Instanz läuft ohne Probleme, nur diejenige, in welcher die Datensicherung importiert wurde, kann keine Geräte hinzufügen, aber alles bereits vorhandene weiter steuern, als wäre alles in Ordnung.

Also Lizenzen gelöscht und alles gestoppt und die alten Daten nochmal rausgekramt und alles so gestartet, wie es seit über einem Jahr läuft. Also nur eine einzige Instanz laufend mit alter Konfiguration. Da ich alles gelöscht hatte, musste ich dort die Datensicherung importieren. Steuerung klappt. Neues Gerät hinzufügen im Webinterface auch, aber das zeigte an dieser Stelle bisher auch nie Probleme. Leider taucht das Gerät in HomeKit nicht auf. Wieder mit iPhone versucht zu synchronisieren... gleicher Fehler.

Instanzen hin oder her, es ist egal ob eine oder mehrere Instanzen laufen. Wenn ich eine neue Konfiguration erstelle, läuft alles und ich kann Geräte hinzufügen. Sobald ich meine Datensicherung zurückspiele, funktioniert die Steuerung darin enthaltener Geräte, aber ich kann keine weiteren Geräte hinzufügen.

Wie bekomme ich also mein Backup wieder richtig lauffähig und erweiterbar?

Konkret ist also das Problem also zusammengefasst folgendes: Eine Datensicherung, erstellt mit v.2.4.1) kann in neuer, gleicher Umgebung importiert (auch 2.4.1) werden und lässt die Steuerung vorhandener Geräte in HomeKit problemlos zu. Hinzufügen neuer Geräte (Lizenz vorhanden, also keine Begrenzung) funktioniert augenscheinlich im Webinterface, lässt sich aber nicht synchronisieren. Somit lässt sich das importierte Backup weiter nutzen, aber nicht mehr erweitern.
Neue Konfigurationen hingegen laufen perfekt und hinzufügen von Geräten klappt und sie tauchen auch in HomeKit auf.

Die bisher einzige Lösung für mich wäre also in neuer Konfiguration alles neu erstellen oder eine zweite Instanz nutzen und die erste unangetastet lassen und hoffen, dass ich nichts ändern muss. Ein zurückgespieltes Backup sollte aber funktionieren und man sollte sich darauf verlassen können. Immerhin kopiere ich nicht selber Datenbanken, sondern nutze eine Softwareseitig zur Verfügung gestellte Funktion.

Im KNX-User-Forum hatte ich bisher kein Feedback erhalten, daher noch einmal hier, da ja "Support-Tickets" über Github laufen sollen.

Viele Grüße
Nils

**Comment by brutella** [comment]
Versuche es mal andersrum und setzt ein Gerät als inaktiv. Verschwindet dieses Gerät dann aus HomeKit?

**Comment by MarinoKNX** [comment]
Leider nein. 

bleibt weiter erhalten und wird nicht gelöscht und ich kann es auch noch steuern (habe eine Lampe inaktiv gesetzt).

Was mir aber auffällt, sind 2 Dinge:
- Sowohl auf dem Handy, als auch am Computer gibt es unter den Geräten das "jetzt synchronisieren" nicht mehr. Das war bis gestern noch da....
- In die Home-App gibt es eine Lampe (Testlampe), welche nicht in der Konfiguration auftaucht, aber der Homekitbrücke zugeordnet ist, wo alles andere auch dran ist. Es läuft nur eine mit dem Zurückgespielten Backup.

**Comment by brutella** [comment]
Hast du womöglich mehrere Instanzen von hkknx am Laufen bei denen du die selbe Datensicherung eingespielt hast?

**Comment by MarinoKNX** [comment]
Nein. Es läuft nur die alte Instanz, nichts weiter.
Als ich zwei Instanzen testete, war es in einer eingespielt. Als es nicht funktionierte, löschte ich die Lizenz, stoppte alles, startete nur eine Instanz und spielte es dort ein. Darin befinde ich mich gerade.

**Comment by brutella** [comment]
Versuche so wie im [Online Handbuch](https://hochgatterer.me/de/hkknx/docs/help/homekit-connection-issues/) unter Punkt 3 beschrieben den DNS-SD Browser zu installieren und schaue welche Einträge für `_hap._tcp` auf deinem iPhone angezeigt werden.

Wirf auch mal eine Blick auf die Log-Ausgaben in der Konsole.
https://hochgatterer.me/de/hkknx/docs/help/access-log/

**Comment by MarinoKNX** [comment]
Die Einträge im _hap._tcp sehen normal aus.
1x HKKNX
1x Homebridge
1x Doorboord (in Homebridge)
1x Unifi Protect (in Homebridge)

Log:
Im Docker-Image von bugroger ist das Verzeichnis leer. Ich kann später die Config nochmal in meinem Ubuntu-Docker laden und dann dort schauen.

**Comment by MarinoKNX** [comment]
Ich habe gestern noch das ganze mit meinem Image probiert. Also Lizenz gelöscht, Docker gestoppt. Meinen Docker gestartet, Datensicherung importiert und ein wenig versucht zu ändern. Anschließend nach dem log geschaut. Hier gibt es zwar Logs, im Gegensatz zum vorherigen, aber hkknx ist darin nicht enthalten. Kann es sein, dass logging deaktiviert ist?

**Comment by MarinoKNX** [comment]
Ich habe nun alles neu aufgesetzt, als ich ein paar Tage krankheitsbedingt Zeit hatte... Nun funktioniert für mich alles wieder.
