### ISSUE TITLE
Push button naming

### ISSUE THREAD

**Issue by petnau** [brutella/hkknx-public#217]
Hi, 

There´s something strange with the naming of Push Buttons. If I create a Push button with a name containing a space. Then go to the Switches category in the Configurator app to look for the Buttons, the names seem to be stripped to only show the last 1-2 letters/digits.

Not a big issue, but just wanted to give a heads-up.

**Comment by brutella** [comment]
How do those buttons appear in the Apple Home app?

**Comment by brutella** [comment]
Closed due to inactivity
