### ISSUE TITLE
Steuerung HSV in Homekit

### ISSUE THREAD

**Issue by mbrockeu** [brutella/hkknx-public#223]
Ich habe eine Lampe angelegt bei der ich die einzelnen GAs von H,S,V jeweils Helligkeit, Farbton und Sättigung zugeordnet habe.
In HomeKit bekomme ich das als Slider angezeigt bei dem ich direkt die Helligkeit steuern kann.

Wenn ich aber eine GA für HSV habe kann ich diese auch verwenden, allerdings wird mir dann in HomeKit ein Schalter angezeigt und ich muss über die Farbauswahl unten alles einstellen.

Hat das einen Grund warum das so ist? Müsste doch vom Verhalten das gleiche sein, nur das es am Ende ein paar GAs spart?!
Oder habe ich was übersehen?

**Comment by brutella** [comment]
Welchen Datentyp hast du in hkknx konfiguriert, um HSV über eine GA zu steuern?

**Comment by mbrockeu** [comment]
Ich habe dort 232-600 genommen, so wie es auch in der ETS definiert ist. Die Steuerung der Farbe etc, funktioniert auch. Nur ist die Darstellung in HomeKit bei beiden Varianten Unterschiedlich.

Aber offensichtlich ist Farbe nur für Farbe gedacht und nicht Helligkeit. 

<img width="904" alt="image" src="https://user-images.githubusercontent.com/16849873/198969979-604d815f-fbb8-467e-8bfa-edd5fecf15c8.png">

Sofern ich die einzelnen Werte angebe scheint er das auch richtig zu nutzen. Der Gedanke war, dass man ggfs. etwas spart.

**Comment by brutella** [comment]
DPST 232-600 ist RGB also **R**ot **G**rün **B**lau und beinhaltet nicht die Helligkeit.

**Comment by mbrockeu** [comment]
Dann wandelt der Aktor das sicher um. Ok dann wird’s wohl nicht gehen bzw. ich muss Helligkeit separat mitgeben.

**Comment by brutella** [comment]
Warum sollte der Dimmer die Werte als HSV interpretieren, wenn du den Datentyp 232.600 (RGB) eingestellt hast?

**Comment by mbrockeu** [comment]
Warum der Controller von Enertex das so macht kann ich auch nicht sagen. Aber im Handbuch ist das so beschrieben:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/16849873/200264376-21e28f7e-83b8-401f-8b77-7c52376cf168.png">

**Comment by brutella** [comment]
Dieses Verhalten ist ja toll. 😒 
Was für eine Enertex Controller hast du da in Verwendung?

**Comment by mbrockeu** [comment]
Das wären diese beiden: https://www.enertex.de/d-dimmer2.html

Die Applikationen sind soweit ich das sehr identisch.

**Comment by brutella** [comment]
Im Build [2.4.2-b3](https://github.com/brutella/hkknx-public/releases/tag/2.4.2-b3) gibt es jetzt die Eigenschaft "Helligkeit & Farbe" mit DPT 232-600 die HSV unterstützt. Bitte testen und Feedback geben.

**Comment by mbrockeu** [comment]
Also ich hab die neue Version installiert. Aber irgendwie ist die Bridge nicht mehr erreichbar. Im Status ist alles grün. Gibts irgendwie ne Möglichkeit einen erweiterten Log anzuzeigen?

Ich hab immer wieder das Problem das die Bridge nicht kommt. Und selbst nach einem reset dauert es immer ewig bis sie wieder hi zugefügt werden konnte.

**Comment by brutella** [comment]
Bei Änderungen an den Einstellungen oder Geräten wird die Bridge neu gestartet. Das kann etwas dauern. Siehe #212

**Comment by mbrockeu** [comment]
So konnte es mal testen, also Grundsätzlich scheint es zu gehen. Aber ich glaube bei der Umrechnung ist irgendwo ein Trick drin. 
Ich habe die Lampe einmal mit allen Werten einzeln drin und einmal mit HSV. 
Wenn die Lampe mit den einzelnen anschalte ist die Helligkeit bei 100% die andere nur bei 58%.

je nachdem wie ich dran rumstelle kommt auch irgendwann "Keine Antwort" bei beiden Geräten.

**Comment by brutella** [comment]
Speichert der Dimmer den letzten Helligkeitswert und sendet diesen beim Einschalten auf den Bus?

Ansonsten ist das Verhalten wie erwartet, da die Apple Home-App automatisch beim Einschalten einer Lampe das Licht auf 100% stellt – wenn vorher auf 0%. Siehe #161

**Comment by mbrockeu** [comment]
Kleine Ergänzung.
Die Lampe mit den Einzelwerten startet mit "100%" der Dimmer nimmt aber den letzten Wert und reduziert z.b. auf "29%".
Es werden alle HSV Werte Einzeln als Status gesendet und einmal gesamt. Die Lampe mit dem neuen Wert bleibt aber auf 100%. Egal wie der Status kommt.

**Comment by mbrockeu** [comment]
Wir werden die Werte den umgerechnet? Meine Recherche haben jetzt ergeben:
als Beispiel: 
4E = 78 
78/255 = 0,306 = 31%

Bei den Winkel eher so:
A4 = 164
360/255*164 = 231,5° 

Völlig absurd was Enertex da tut, aber nun gut.

**Comment by brutella** [comment]
Ja, genau so ist die Umrechnung in hkknx.

**Comment by mbrockeu** [comment]
Folgendes wird gesendet wenn ich die Lampe (egal welche von Beiden) einschalte
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/16849873/203650383-1f73b940-f780-494a-83cd-74649719fd61.png">
Und das sagt mir dann HomeKit:
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/16849873/203650486-7c57b89d-a453-49f4-b618-6cb4a392aa5e.png">

Wenn ich die Helligkeit bei der neuen Konfiguration ändere passiert auf dem Bus nix.

**Comment by brutella** [comment]
Das Problem mit der Helligkeit sollte mit [2.4.2-b4](https://github.com/brutella/hkknx-public/releases/tag/2.4.2-b4) behoben sein. Bitte ausprobieren.

**Comment by mbrockeu** [comment]
Helligkeit scheint zu funktionieren, auch wenn in den niedrigen Bereichen die Anzeige um 1% abweicht.
Die Farbsteuerung scheint weiterhin nicht zu funktionieren, es kommt dann irgendwann wieder "keine Antwort" und die Farbe wechselt in keinem Fall.

**Comment by brutella** [comment]
Gibt es neue Erkenntnisse bei diesem Problem mit Version [2.4.2-b8](https://github.com/brutella/hkknx-public/releases/tag/2.4.2-b8)?

**Comment by mbrockeu** [comment]
Mir ist nur gerade aufgefallen, dass offenbar der Wert für HSV gesamt nicht gesendet wird. Das erklärt natürlich auch warum sich dort nix ändert und warum er gegebenenfalls dann hängt mit "Keine Antwort". Die Variante mit allem getrennt scheint weiterhin zu gehen.
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/16849873/213544265-8a722122-fb2e-4bff-a12f-13142b1a3e0a.png">

**Comment by mrmatze007** [comment]
Ich habe nun auch die 2.5.0-b1 installiert, da sonst die Ansteuerung der RGBW-Geräte bei Szenen nicht sauber funktioniert (Thema: In welcher Reihenfolge werden die Befehle von HomeKit übertragen). Abhilfe kann hier vermutlich der HSV-Kombidatenpunkt schaffen.

Bei mir ist aber dasselbe Verhalten wie bei @mbrockeu zu beobachten: Der HSV-Kombidatenpunkt wird nicht übertragen. Folglich erhalte ich auch die Fehlermeldung "Keine Antwort" in HomeKit.

**Comment by brutella** [comment]
@mrmatze007 Wie schaut deine Konfiguration in hkknx für diese HSV Lampe aus?

**Comment by mrmatze007** [comment]
@brutella 

Danke für deine schnelle Antwort. Meine Konfiguration besteht aus lediglich aus "Schalten" und "Helligkeit & Farbe". Damit werden ja alle notwendigen Werte übertragen. Hier ein Screenshot:
![image](https://user-images.githubusercontent.com/112128957/215585675-3a3e8d57-eb88-4de6-a255-b07ac5f79e60.png)

**Comment by brutella** [comment]
Und welche Bytes werden an KNX versendet, wenn du die Farbe oder die Helligkeit in HomeKit änderst?

**Comment by mrmatze007** [comment]
Wenn die Leuchte per HomeKit eingeschaltet wird, sendet hkknx ein "Ein" sowie einen initialen HSV-Befehl (warum auch immer, der wird eigentlich nicht benötigt, da der Aktor durch das "Ein" ja die initiale Farbe vorgibt):
![image](https://user-images.githubusercontent.com/112128957/215618105-f43fc095-d9e5-43fb-923f-b4c832a5444d.png)

Schalte ich die Leuchte direkt danach aus, wird ein "Aus" auf den Bus gesendet:
![image](https://user-images.githubusercontent.com/112128957/215618201-ab00e63b-b8f0-4d34-a69e-8dc48b64ca7c.png)

Versuche ich nach erneutem Einschalten die Helligkeit oder die Farbe zu verändern, geschieht in beiden Fällen nichts und ich bekomme eine "keine Antwort" in HomeKit:
![image](https://user-images.githubusercontent.com/112128957/215618347-b74f4acc-0c41-40c6-a6e0-1acadbbd7fc3.png)

Danke Dir für den Support!

**Comment by brutella** [comment]
Findest du dazu im Systemprotokoll irgendwelche Log-Ausgaben?

**Comment by mrmatze007** [comment]
Wow, das ging ja mal richtig zügig. Danke dir!

Habe die 2.5.0-b2 gleich installiert. Und tatsächlich: Die HSV-Befehle kommen jetzt perfekt auf dem Bus an. Respekt :-)

Es wäre super, wenn du noch folgende Sache "fixen" könntest: Wird die HSV-gesteuerte Leuchte angeschaltet, wird zusätzlich zum "Ein" immer ein HSV-Wert übergeben. Das Verhalten ist so wie in meinem Screenshot gestern dokumentiert (= dort wurde #0000FF übergeben). Dieser HSV-Wert bezieht sich auf die letzte Farbeinstellung.

Bei der RGBW-gesteuerten Leuchte ist das Verhalten anders: Dort wird beim Einschalten nur ein "Ein" gesendet. Das hat den Vorteil, dass der KNX-Aktor seine Voreinstellung aufruft (= bei mir ist das HCL). Wird ein HSV-Farbwert zusätzlich mit gegeben, wird die interne Logik der Aktors übergangen.

Daher wäre es klasse, wenn du bei HSV-Leuchten ebenfalls nur ein "Ein" übergeben könntest.

Danke Dir!!

**Comment by mbrockeu** [comment]
> Wow, das ging ja mal richtig zügig. Danke dir!
> 
> Habe die 2.5.0-b2 gleich installiert. Und tatsächlich: Die HSV-Befehle kommen jetzt perfekt auf dem Bus an. Respekt :-)
> 
> Es wäre super, wenn du noch folgende Sache "fixen" könntest: Wird die HSV-gesteuerte Leuchte angeschaltet, wird zusätzlich zum "Ein" immer ein HSV-Wert übergeben. Das Verhalten ist so wie in meinem Screenshot gestern dokumentiert (= dort wurde #0000FF übergeben). Dieser HSV-Wert bezieht sich auf die letzte Farbeinstellung.
> 
> Bei der RGBW-gesteuerten Leuchte ist das Verhalten anders: Dort wird beim Einschalten nur ein "Ein" gesendet. Das hat den Vorteil, dass der KNX-Aktor seine Voreinstellung aufruft (= bei mir ist das HCL). Wird ein HSV-Farbwert zusätzlich mit gegeben, wird die interne Logik der Aktors übergangen.
> 
> Daher wäre es klasse, wenn du bei HSV-Leuchten ebenfalls nur ein "Ein" übergeben könntest.
> 
> Danke Dir!!

Fände ich auch gut. Bei mir wird’s primär auch HCL sein. Ich werde es dann wohl in 3-4 Wochen testen 😊

**Comment by mrmatze007** [comment]
@mbrockeu - Ich werde so lange für dich testen ;-)

**Comment by brutella** [comment]
Das Problem, dass HSV Werte beim Einschalten der Lampe gesendet werden sollte jetzt in [2.5.1-b1](https://github.com/brutella/hkknx-public/releases/tag/2.5.1-b1) behoben sein.

**Comment by mrmatze007** [comment]
Mega! In 2.5.1-b1 wird beim Einschalten tatsächlich kein HSV-Wert mehr mitgegeben.

Dafür hat sich das andere Problemchen wieder aufgetan: Jetzt wird bei der Farbverstellung wieder kein HSV-Wert gesendet. Heißt, in der aktuellen Beta kann ich die Leuchte nur noch ein- und ausschalten.

Hier ein Screenshot aus dem Log:
![image](https://user-images.githubusercontent.com/112128957/216415178-2ddbf3c9-002e-431d-aad3-d9e122677a8f.png)

**Comment by brutella** [comment]
Upsi, mit [2.5.1-b2](https://github.com/brutella/hkknx-public/releases/tag/2.5.1-b2) sollte es wieder klappen.

**Comment by mrmatze007** [comment]
Du haust die Betas ja echt raus wie McDonalds die BigMacs... 👍 

Ich habe mir die neue Version gerade installiert und "Upsi" scheint gelöst zu sein. Bei einer Testleuchte hat es bei einem kurzen Test zumindest funktioniert. Ich werde jetzt die restlichen Leuchten im Haus auf HSV umstellen und in ein paar Tagen berichten.

Merci!

**Comment by mrmatze007** [comment]
Ich habe etwas "rumprobiert" und dabei folgendes Verhalten festgestellt: Die Farbeinstellung bei Einzelleuchten funktioniert. Wenn ich die Farbe im Rahmen einer Szene speichere, wird beim Aktivieren der Szene aber nur ein "Ein" gesendet. Die HSV-Farbinformation wird beim Aktivieren der Szene also nicht mitgegeben.

Ist das ein Thema von hkknx oder von Apple?

**Comment by brutella** [comment]
Dieses Verhalten ergibt aus der Anforderungen, dass beim Einschalten der Lampe mit 100% Helligkeit die Farbinformation nicht mitgesendet werden soll. 100% Helligkeit wird automatisch von der Apple Home-App (oder Siri) mitgesendet, wenn die Lampe mit einem Tipp auf die Kachel eingeschaltet wird.

Hast du schonmal versucht in der Szene die Lampe nicht einzuschalten, sondern nur die Farbinformation festzulegen. Die Lampe müsste sich dann automatisch einschalten – glaub ich.
(Mit der Apple Home-App kannst du das leider nicht festlegen, aber mit [Home+](https://itunes.apple.com/us/app/home-smart-home-automation/id995994352) schon.)

**Comment by mrmatze007** [comment]
Alles klar, jetzt beißt sich die Katze also in den Schwanz. Über die ETS habe ich es gerade getestet: Über das Senden der reinen HSV-Information lässt sich die Leuchte einschalten. Ich hole mir dann mal die Home+-App und teste das. Lassen sich in Home+ erstellte Szenen dann auch in der Apple Home-App bzw. über Siri aufrufen?

**Comment by brutella** [comment]
> Lassen sich in Home+ erstellte Szenen dann auch in der Apple Home-App bzw. über Siri aufrufen?

Ja, klar. Home+ speichert Szenen und Automationen in HomeKit ab.

**Comment by brutella** [comment]
Kann dieses Issue nun geschlossen werden?

**Comment by mrmatze007** [comment]
On top habe ich mir jetzt noch die Home+-App zugelegt. Und ja: So wie von @brutella geschrieben funktioniert es.

Heißt: Von meiner Seite kann das Issue geschlossen werden.

Danke für den Support!!

**Comment by mbrockeu** [comment]
Ich kann erst irgendwann im März/April testen. Sollte da noch was sein kann man es ja noch mal aufmachen. 

Danke auch von meiner Seite.

**Comment by brutella** [comment]
Eine Anmerkung zu HSV mit DPT 232.600 gibt es jetzt im Online Handbuch zum nachlesen.
https://hochgatterer.me/de/hkknx/docs/accessories/lightbulb/#besonderheit-bei-dpst-232600
