### ISSUE TITLE
Humidity sensor - DPST-9-7 issue

### ISSUE THREAD

**Issue by thorsten-gehrig** [brutella/hkknx-public#226]
Hi
i have several humidity sensors with DPST-5-1 (0-100%) which do work fine.
But i have one with DPST-9-7 - and those doesnt work/doesnt show up in Homekit even the value (e.g. 40.2) is send via the bus.
It is also visible within the bus (on HKKNX Webinterface).
Seems a bug to me...
Can you confirm?

Best
Thorsten

PS: it´s version 2.4.2-b2

**Comment by brutella** [comment]
Do you see any error messages in the [log](https://hochgatterer.me/de/hkknx/docs/help/access-log/) when a new humidity value is send via the bus?

**Comment by thorsten-gehrig** [comment]
Kein Fehler im log.
Beispiel:
2022-11-08 21:04:56.289 | Low | 1.1.231 |   |   | 4/0/9 | WP Feuchte Wohznzimmer | Write |   | [0 20 46] | 14 2e
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
(sind 42.8 % Luftfeuchte)

Gruß
Thorsten

**Comment by brutella** [comment]
In HomeKit werden Luftfeuchtigkeitswerte mit einer Genauigkeit von 1% dargestellt. Wenn also der Wert von 40,6 % (41% in HomeKit) auf 41.4 % (auch 41% in HomeKit) aktualisiert wird, ändert sich der Wert in HomeKit nicht. 

Kann es daran liegen?

**Comment by thorsten-gehrig** [comment]
Hi
ich habe nur "Relative Humidity" , DPST-9-7, Read 4/0/9, Write 4/0/9
Das ist alles
Gruß
Thorsten

**Comment by brutella** [comment]
Ist die GA auch lesbar? Wenn nicht, dann wird nach dem Initialisieren 0% Feuchtigkeit angezeigt – da ja kein Initialwert ausgelesen werden kann.

**Comment by thorsten-gehrig** [comment]
Hm... derzeit kann ich den Fehler nicht mehr nachvollziehen. 
Hab gerade mal hkknx neu gestartet - und nach der read-periode sind alle Werte vorhanden.
Keine Ahnung was sich geändert hat... Mach das ticket erstmal zu. Sorry - und danke.
