### ISSUE TITLE
Haupt- und Mittelgruppen Namen anzeigen

### ISSUE THREAD

**Issue by Benny-Git** [brutella/hkknx-public#23]
Ich verwende in etwa das Gruppenkonzept von Manfred Meier, also habe z.B. die Gruppenadresse `1/0/6` für das Schalten des Lichts im UG Vorraum:
- `1` = Schaltaktor/Licht
- `0` = Schalten
- `6` = UG Vorraum

In hkknx wird mir nun nur "`UG Vorraum`" für `1/0/6` angezeigt, und ich muss erst wieder zusammenpuzzeln, ob das nun fürs Schalten oder den Status des Schaltens war.

Kann man in der Ansicht auch die Namen der Mittel- und Hauptgruppe einblenden? Ansonsten müsste ich meine ganzen GAs umbenennen, was aber in der ETS wieder unschön wäre.

**Comment by brutella** [comment]
Zurzeit wird nur die Bezeichnung einer Gruppenadresse importiert.
Die Gruppen selbst werden dabei ignoriert. Mal sehen was sich da machen lässt.

**Comment by brutella** [comment]
Fixed in v0.0.15
