### ISSUE TITLE
Compatibility with new Apple Home architecture

### ISSUE THREAD

**Issue by mirkolenz** [brutella/hkknx-public#231]
It seems to be the case that the promised [architectural update](https://www.macrumors.com/2022/10/25/home-app-architecture-update-ios-16-2/) of the Apple Home app will ship with the upcoming iOS 16.2 update. I currently do not participate in beta testing and am aware of the fact that you will most likely not support beta versions.

Since this version could launch next month and HKKNX is deeply integrated into my home workflow, I do not want to risk breaking it with the irreversible upgrade process. Thus my question is: Do you have any experience with this new Home app? Does it even have an effect on HKKNX? Should users wait with the upgrade until you had the time to update HKKNX?

Thank you so much for creating this wonderful application 😄

**Comment by brutella** [comment]
I'm pretty sure there is no action required by HomeKit accessories since the architecture update is only related to internals of the Home app.

**Comment by mirkolenz** [comment]
Thank you for the fast and encouraging response!
