### ISSUE TITLE
Thermostat - issue reading value

### ISSUE THREAD

**Issue by thorsten-gehrig** [brutella/hkknx-public#232]
Hi
I see a bug with receiving the "set to temperature" on hkknx.
I´m havving the latest version 2.4.2-b2
For my thermostat i have 4/1/123 as targert-temperature.
I have this configured for Write/read/inialiize.

My issue: the "set to temperature" is received on the bus as "response" but not "write".
Any value send to the bus as "write" is processed - but on my scenario the most updates are received as "response".
hkknx does only take values from "write" - while "response" on 4/1/123 should also be update the value, isnt?

The log file clearly identfies KNX Type as WRITE and RESPONSE - but only the WRITE does update the value - not the response...

Best
Thorsten

**Comment by brutella** [comment]
That's an interesting behaviour. I thought that response telegrams are only triggered by read telegrams.

Am I wrong to expect that when the set temperature is updated, the new value is sent to a group address via a write telegram?

**Comment by thorsten-gehrig** [comment]
Usually they should be triggered by read telegrams - but this should also update the value, isnt?
You are right that they SHOULD be updated via a write telegram... but in some use cases those telegram can not be submitted or get lost. 
Anyhow - I have fixed my use case so I´m fine (EDOMI now send WRITE instead of RESPONSE)
Best
Thorsten
