### ISSUE TITLE
Zurücksetzen der Bridge nicht möglich

### ISSUE THREAD

**Issue by mbrockeu** [brutella/hkknx-public#233]
Ich wollte die Bridge zurücksetzen, weil diese nicht erreichbar ist oder ähnliches.

Beim zurücksetzen kommt der Dialog zum bestätigen, nach dem bestätigen sieht man das die URL sich noch einmal kurz ändert und dann bleibt der Dialog offen und die Seite lädt sich einen Wolf.

Ich habe auch folgendes Probiert:
1. Bridge vorher deaktivieren
2. Vorheriger Neustart

Problem dabei ist, mit Neuaufrufen der URL komme ich wieder auf die Einstellungsseite, ob die Bridge zurücksetzt wurde weiß ich aber nicht.

Ich hatte in einigen Fällen schon mal eine Bestätigung bekommen das alles geklappt hatte. Da war das Projekt aber ziemlich leer.

Aktuell habe ich 141 Geräte in der Konfiguration. Da es noch eine Testinstallation ist sind nicht alle Autoren im Hintergrund erreichbar.

**Comment by brutella** [comment]
Du musst die HomeKit Brücke selbst unter den Einstellungen → Mehr → HomeKit Brücke zurücksetzen.

**Comment by brutella** [comment]
Habe die Funktion gerade getestet und konnte keine Probleme feststellen. Welche Probleme treten bei dir auf?

**Comment by brutella** [comment]
- Welchen Browser verwendest du?
- Hast du nach dem zurücksetzen wieder versucht die Brücke zu HomeKit hinzuzufügen?

**Comment by mbrockeu** [comment]
Ebenfalls frohe Weihnachten.

Ich wollte eigentlich gerade noch schreiben das ich in letzter Zeit das Problem nicht mehr hatte.
Aber da nach einer Änderung die Bridge offenbar nicht wieder wollte, musste ich diese wieder zurücksetzen. 

Der Fehler trat wieder auf, aber der Workaround funktioniert bei mir irgendwie nicht, er hängt immer noch beim zurücksetzen.

Konntest du bei dir das Problem mit dem endlosen Laden reproduzieren?

**Comment by brutella** [comment]
Ja, ich werde in einem Update den Status der Bridge etwas genauer anzeigen lassen. Zur Zeit wird "Verfügbar" angezeigt, obwohl die Geräte erst initialisiert werden – da besteht Verbesserungsbedarf.

**Comment by mbrockeu** [comment]
Ich hatte auch schon in dem anderen Ticket noch eine Idee geschrieben.
Vielleicht kann man im Log Output auch etwas mehr Details geben, welches Gerät er gerade abfragt, wieviele ggfs. noch offen sind.

Wenn ich zum Beispiel nur mal eine GA ändere müsste meiner Meinung nach nicht die Bridge neugestartet werden?

**Comment by brutella** [comment]
In der aktuellste Pre-Release Version [2.5.0-b2](https://github.com/brutella/hkknx-public/releases/tag/2.5.0-b2) siehst du unter *Status* den Fortschritt der Initialisierung, zB 10/53.

**Comment by brutella** [comment]
Besteht das Problem in Version 2.5.1 immer noch?
