### ISSUE TITLE
Bridge switches on lamps with a wrong dim level

### ISSUE THREAD

**Issue by Graefer** [brutella/hkknx-public#239]
The bridge is not able to turn on a lamp on a defined dim level. This seems due to the fact that many KNX actors always send a predefined default dim value when they switch on a lamp. Unfortunately this makes the use of HomeKit scenes almost useless. If the bridge could send the dim level delayed to its switch on command could presumably resolve this problem.

**Comment by mirkolenz** [comment]
I think this may be related to #200.

**Comment by Graefer** [comment]
Yes. All KNX dim actors known to me have an „initial brightness“ parameter which definitely interferes with the bridges/HomeKit behavior to turn on an then to set a dim value.
