### ISSUE TITLE
Rollladen Status wird als "Öffnen" angezeigt

### ISSUE THREAD

**Issue by Benny-Git** [brutella/hkknx-public#24]
Auf meinem iPhone wird der Rollladen im offenen Zustand als "Öffnen" angezeigt (vermutlich übersetzt von "Open"?).
"Geschlossen" ist korrekt übersetzt.

**Comment by brutella** [comment]
Kannst du bitte hier einen Screenshot posten, der die konfigurierten Gruppenadressen des Rollladens zeigen.

**Comment by Benny-Git** [comment]
![image](https://user-images.githubusercontent.com/20797438/75886929-4dca6000-5e29-11ea-8839-2d0b650da8d1.png)

![IMG_4092](https://user-images.githubusercontent.com/20797438/75887226-c0d3d680-5e29-11ea-849b-d34db9eb4e09.PNG)

**Comment by nanosonde** [comment]
Das Problem habe ich auch. Aber nur auf den Geräten mit iOS13.
Ich habe noch ein iPad Air 1 für das es ja nur noch iOS 12.4.5 gibt und da wird "Geöffnet" angezeigt.
Meiner Meinung nach also ein iOS Problem.

Ich habe auch noch openHAB2.5 mit Homekit kaufen und da wird bei iOS13 leider auch "Öffnen" abgezeigt.

**Comment by brutella** [comment]
Hab auch gerade überprüft. Unter iOS 12 wird richtig **Geöffnet** angezeigt. Unter iOS 13 steht **Öffnen**.

Es scheint sich also um einen Übersetzungsfehler in Apple Home zu handeln.

Ich werde mal einen Bug Report an Apple schicken.

**Comment by Benny-Git** [comment]
Okay, dann kann dieser Issue vermutlich geschlossen werden.

**Comment by brutella** [comment]
Reported as [FB7615711](http://openradar.appspot.com/radar?id=4960814654029824)

**Comment by nanosonde** [comment]
What is the status of this issue?

**Comment by brutella** [comment]
@nanosonde The issue is fixed in iOS 14.
