### ISSUE TITLE
aktueller Status in der HomeApp verschwindet

### ISSUE THREAD

**Issue by holli17** [brutella/hkknx-public#249]
Hallo, der aktuelle Status der Geräte wird nur kurz angezeigt. Beispiel: Lampe über Esstisch wird angeschaltet, dieses wird ausgeführt und in der App angezeigt. ( Symbol leuchtet und "An" wird angezeigt. Nach einiger Zeit ändert sich dieses in "Aus" und das Symbol wird dunkel, Leuchte ist aber weiterhin an. Besonders ärgerlich, da die Temperaturanzeigen auf "0" gehen.

Bei externem Zugriff auf die App, also über das mobile Netz, bleiben die Anzeigen!

Woran kann das liegen? was mache ich falsch?

Danke

**Comment by chef76** [comment]
Verschwinden die Stati bei geöffneter App oder schließt du nach dem Schalten die App und öffnest sie dann wieder?

**Comment by holli17** [comment]
Sie verschwinden ( verschwanden ) in der geöffneten App -- allerdings im Augenblick bleiben sie! Ich habe in der Zwischenzeit noch weitere Schalter hinzugefügt. Ich kann den Fehler im Moment nicht mehr rekonstruieren. Ich wollte erst noch ein Foto machen, hätte ich's mal gemacht-
Beobachte und teste weiter und werde mich spätestens morgen melden.
DANKE

**Comment by chef76** [comment]
... um das abzukürzen: schau mal in der Konsole der Brücke, ob es read-Timeouts für die Status GAs gibt! Sind die GA's der Stati vom Bus lesbar (Lesen Flag der Aktoren und Sensoren gesetzt)?

**Comment by holli17** [comment]
Hallo, war gestern erst sehr spät zuHause, daher erst jetzt!
habe mir aber noch die Werte angesehen und zum ausprobieren mal neu ein neues zuHause in AppleHome eingerichtet. Hier habe ich nun eine Lampe über Schaltaktor mit Ein/aus, eine weitere auch über Schaltaktor mit ein/aus. Die Temperatur der Küche hole ich mir über den Gira PM.
in Deiner Brücke habe ich keine Read-Timeouts gefunden, aber über den Gruppenmonitor andere Fehler, die aber nichts hiermit zutun haben. Folgende Einstellungen der Aktoren/Sensoren:
TM Küche: 7/5/8 lesen DPST 9-1 ( K-L-S-Ü ) 2bytes ---Gira PM Einstellungen: senden bei Temp.Änderungen um: 3 / zyklisch senden: 10Min.
Lampe Tisch: 0/0/47 schreiben DPST 1-1 ( K-S ) 1 bytes --- Schaltaktor: zyklisch senden: 0 ( deaktiviert ) / Status senden: bei Änderungen
Lampe Tisch: 0/3/47 lesen DPST 1-11 ( K-L-Ü ) 1 bytes --- 

Vielen lieben Dank für die Hilfe!!
Kann auch gerne, wenn ich wieder daheim bin Bilder/Fotos der Einstellungen usw. senden...

**Comment by chef76** [comment]
So seh ich halt jetzt nicht, was in der Brücke eingetragen ist. Im Prinzip muss die Adresse, die in der Brücke bei Lesen und Initialisieren eingetragen ist lesbar sein. Lese mal mit der ETS die GA. Wenn von der Adresse dann die Antwort mit dem Wert kommt, sollte es funktionieren. So wie du es beschreibst, hast du entweder bei Lesen und Initialisieren die falsche GA oder sie ist nicht lesbar.

**Comment by holli17** [comment]
werde ich heute am Abend durchführen.

**Comment by holli17** [comment]
so, habe nun alles komplett neu installiert und es funktioniert, in der ETS kommen auch die korrekten Werte ( auch  ETS neu eingespielt ) 
Trotzdem habe ich manchmal einen Abbruch und dann diese Meldungen:##
"""INFO 2023/01/15 16:44:38 temp.go:14: Unable to unpack value temp from [0 127 255]
2023/01/15 16:49:26 closing data channel because of keep alive error: keep alive: channel closed
2023/01/15 16:49:26 disconnect: write udp4 192.168.1.60:63435->192.168.1.200:3671: use of closed network connection
INFO 2023/01/15 16:49:30 app.go:333: tunnel: connected to 192.168.1.200:3671 via 1.1.6
2023/01/15 16:49:31 rate limitting (sleeping 949.384762ms)
2023/01/15 16:49:32 rate limitting (sleeping 953.041841ms)
2023/01/15 16:49:32 rate limitting (sleeping 952.951122ms)
INFO 2023/01/15 16:49:33 io.go:26: unpack *dpt.DPT_9001: Temperatur "670760.94" outside range [-273, 670760]
2023/01/15 17:17:36 closing data channel because of keep alive error: connection not found
2023/01/15 17:17:36 disconnect: write udp4 192.168.1.60:50053->192.168.1.200:3671: use of closed network connection
INFO 2023/01/15 17:17:40 app.go:333: tunnel: connected to 192.168.1.200:3671 via 1.1.6
2023/01/15 17:17:40 rate limitting (sleeping 949.818315ms)
2023/01/15 17:17:41 rate limitting (sleeping 953.590287ms)
2023/01/15 17:17:41 rate limitting (sleeping 953.505267ms)
INFO 2023/01/15 17:17:42 io.go:26: unpack *dpt.DPT_9001: Temperatur "670760.94" outside range [-273, 670760]
INFO 2023/01/15 17:29:32 temp.go:14: Unable to unpack value temp from [0 127 255]
2023/01/15 17:56:29 closing data channel because of keep alive error: connection not found
2023/01/15 17:56:29 disconnect: write udp4 192.168.1.60:55160->192.168.1.200:3671: use of closed network connection
INFO 2023/01/15 17:56:33 app.go:333: tunnel: connected to 192.168.1.200:3671 via 1.1.6
2023/01/15 17:56:34 rate limitting (sleeping 951.867498ms)
2023/01/15 17:56:35 rate limitting (sleeping 949.17387ms)
2023/01/15 17:56:35 rate limitting (sleeping 949.065427ms)
INFO 2023/01/15 17:56:36 io.go:26: unpack *dpt.DPT_9001: Temperatur "670760.94" outside range [-273, 670760]
"""
heißt, das er sich manchmal abmeldet.
Ich nutze im Augenblick noch das IP Interface von Weinziel ( über 1home, was ich aber retour sende ), meine X1 von Gira hat nicht funktioniert! ( Gira X1/S1 und G1 geht an Ebay und wird ein neues zuHause finden )

**Comment by chef76** [comment]
Schön, dass es jetzt funktioniert. Zur Meldung kann ich nichts sagen, da müsste @brutella ran.

**Comment by holli17** [comment]
ja, bin schon erleichtert ;-)
vielen dank

**Comment by brutella** [comment]
Bei den Fehlermeldungen kommt die Bytes `0x7FFF` (in `[0, 127, 255]`) was laut KNX Dokumentation ein ungültiger Wert für eine Temperatur ist. Welcher KNX Teilnehmer sendet diese Daten?

**Comment by chef76** [comment]
Hast du die Datentypen für die GAs definiert? Das ist für mich jedenfalls die einzige Erklärung, weshalb "falsche Werte" kommen sollten.

**Comment by brutella** [comment]
@chef76 Du meinst in der ETS oder?

**Comment by holli17** [comment]
ja, habe ich. 9001 für beide Temperaturen. am Anfang der Installation wurden alle drei Werte gesendet. am nächsten tag nicht mehr. mich irritiert auch die Abmeldung, die manchmal erfolgt. liegt eventuell an der weiziel Gateway von 1home. muss mir noch eine neue bestellen, schau gerade welche gut ist. werde also morgen den Schalter auf die Werkseinstellungen zurücksetzen. die aktuelle gesendete Werte gehen über mehrere Seiten und liegen vermutlich an der neuen Security .

**Comment by chef76** [comment]
> @chef76 Du meinst in der ETS oder?

Ja, in der ETS!

**Comment by holli17** [comment]
darauf lässt sich doch aufbauen  ;-)



2023-01-16 20:45:04.676 | Niedrig | 1.1.2 |   |   | 7/5/0 | Temperatur Wohnen | 1009 |   | [0 16 0 36 248 64 56 5 199 195 103 121 132 145 243 109] | 10 00 24 f8 40 38 05 c7 c3 67 79 84 91 f3 6d
2023-01-16 20:45:04.763 | Niedrig | 1.1.2 |   |   | 7/5/4 | Bodentemperatur Wohnen | 1009 |   | [0 16 0 36 248 64 56 6 207 87 183 137 224 4 229 96] | 10 00 24 f8 40 38 06 cf 57 b7 89 e0 04 e5 60
2023-01-16 20:45:05.280 | Niedrig | 1.1.2 |   |   | 7/4/0 | Feuchte Wohnen | 1009 |   | [0 16 0 36 248 64 56 7 16 236 139 255 207 128 252 69] | 10 00 24 f8 40 38 07 10 ec 8b ff cf 80 fc 45


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by brutella** [comment]
Gibt es zu diesem Problem schon etwas neues?

**Comment by holli17** [comment]
Hallo,die meisten Daten bleiben mittlerweile erhalten. Nach dem Wechsel der X1 zu MDT klappt es. Die Probleme mit der Temperatur liegt an der Tatsache, dass die pt1000 nicht kompatibel zu der Gira Tastsensor 4 sind.Also hat sich das insofern erledigt, als es nichts mit der Software zutun hat.  Mit freundlichen Grüßen          Holger Elster  Finanzierungen             Mobil 0177 / 313 13 22Holger Elster28355 Bremen       Register: D-W-112-3BG9-16Steuernummer:  6015000196Aufsichtsbehörde: Handelskammer Bremen        Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen.Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhaltenhaben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nichtgestattet.This e-mail may contain confidential and/or privileged information. If you arenot the intended recipient (or have received this e-mail in error) please notifythe sender immediately and destroy this e-mail. Any unauthorized copying,disclosure or distribution of the material in this e-mail is strictly forbidden.Am 27.02.2023 um 12:27 schrieb Matthias ***@***.***>:﻿
Gibt es zu diesem Problem schon etwas neues?
