### ISSUE TITLE
Der Button "Nach Update suchen" findet keine Updates (Pre-releases?)

### ISSUE THREAD

**Issue by mbrockeu** [brutella/hkknx-public#252]
Ich habe aktuell Pre-Release Versionen am laufen und wenn ich auf "Nach Updates suchen" klicke kommt immer die Meldung es gibt keine Updates.

Wenn ich allerdings direkt Updaten drücken darf ich noch mal bestätigen und er legt gleich los. Ist es ungünstig wenn man nicht sieht welche Version er dort installieren will. 

Nimmt der Button nur offizielle Releases?

**Comment by mbrockeu** [comment]
Ok, dann wäre es vielleicht einfach noch mal gut zu schreiben welche Version er installieren würde. Ich guck zwar hier und sehe das, aber sicher kann man sich erst danach sein :-)

**Comment by brutella** [comment]
Ab Version [2.6.0-b1](https://github.com/brutella/hkknx-public/releases/tag/2.6.0-b1) kann man eine beliebige Version herunterladen und installieren.
