### ISSUE TITLE
Update: File '.hkknx.old' not found

### ISSUE THREAD

**Issue by Graefer** [brutella/hkknx-public#254]
Das Update von 2.5.0-b1 auf Version 2.5.0 schlägt fehl:
File '.hkknx.old' for the command is not found in https://github.com/brutella/hkknx-public/releases/download/2.5.0/hkknx-2.5.0_linux_amd64.tar.gz

**Comment by saimon1799** [comment]
Hallo Matthias,
Ich habe das gleiche Problem. Ich kann nicht von 2.4.2-b6 auf 2.5.0 aktualisieren. Bekomme folgende Fehlermeldung:

File '.hkknx.old' for the command is not found in https://github.com/brutella/hkknx-public/releases/download/2.5.0/hkknx-2.5.0_linux_arm.tar.gz

Gibt es schon eine Lösung für dieses Problem?

Vielen Dank im Voraus. 

Viele Grüße 
Simon

**Comment by brutella** [comment]
Kannst du die aktuellste Version 2.5.1-b3 installieren?

**Comment by saimon1799** [comment]
Vielen Dank für Deine Rückmeldung. Leider funktioniert das auch nicht. 

Da ist der rote Banner am oberen Rand der Weboberfläche:

„Das Update auf Version 2.5.0 ist fehlgeschlagen.. 
File '.hkknx.old' for the command is not found in https://github.com/brutella/hkknx-public/releases/download/2.5.0/hkknx-2.5.0_linux_arm.tar.gz
Nochmal versuchen“

Der lässt das Installieren der neuesten Beta nicht zu.

Gibt‘s denn einen alternativen Weg um zu aktualisieren, als das über die Weboberfläche zu tun?

**Comment by brutella** [comment]
> Gibt‘s denn einen alternativen Weg um zu aktualisieren, als das über die Weboberfläche zu tun?

Ja klar. → https://hochgatterer.me/de/hkknx/docs/install/update/

**Comment by saimon1799** [comment]
Super, das hat geklappt. 

Vielen herzlichen Dank

**Comment by Graefer** [comment]
Per Hand auf 2.5.0 hat geklappt. Jetzt gleiches Problem mit autom. Update auf 2.5.1: File '.hkknx.old' for the command is not found
