### ISSUE TITLE
Nach HKKNX Update ist KNX Gateway nicht mehr verbunden 

### ISSUE THREAD

**Issue by gisbertpeter** [brutella/hkknx-public#257]
Habe HKKNX v2.2 installiert und das funktioniert. Nach Update zu einer neueren Version (z.B. v2.5) findet HKKNX den KNX Gateway nicht mehr, d.h. "nicht verbunden" (ist auf automatisch gestellt). Auch die HomeKit Brücke wird nicht gefunden, d.h. "nicht verbunden".
Ich musste wieder auf v2.2 zurückgehen, dann OK.

**Comment by brutella** [comment]
Bitte versuche die IP Adresse des KNX Gateways einzutragen. Dann sollte es auf jeden Fall funktionieren.

**Comment by mirkolenz** [comment]
Ich habe ja wie bereit in einem anderen Issue erwähnt das gleiche Problem: Es dauert meist mehr als eine Minute, bis HKKNX sich verbunden hat. Manchmal funktioniert es auch direkt, ich konnte da noch kein Muster erkennen. Wäre also interessant, ob es bei @gisbertpeter auch funktioniert, wenn man einige Zeit abwartet.

**Comment by gisbertpeter** [comment]
Vielen Dank! 
Das Eintragen der IP-Adresse des KNX-Gateways hat geklappt. Die Initialisierung der HomeKit-Brücke hat wirklich etwas länger gedauert, ca. 3 Minuten für 57 Geräte. Aber nun funktioniert die Version 2.5. Das Issue kann geschlossen werden.

**Comment by gisbertpeter** [comment]
Vielen Dank!
