### ISSUE TITLE
http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by tdoescher** [brutella/hkknx-public#268]
Ich habe hkknx mit docker am laufen, nach einer weile schmiert das Programm im Container immer mit dieser Fehlermeldung ab und ist nicht mehr erreichbar:

`http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s`

Es scheint ein Problem im Programm zu sein bzw. mit go:

[stackoverflow.com Beitrag](https://stackoverflow.com/questions/37454236/net-http-server-too-many-open-files-error)

**Comment by brutella** [comment]
Wie sieht deine Konfiguration von hkknx aus? 

- Welchen Port hast du für hkknx mit `-port` angegeben?
- Welchen Port für die HomeKit Brücke hast du in den Einstellungen festgelegt?
- Hast du Skripte am Laufen, die `http.Client` verwenden?

**Comment by tdoescher** [comment]
- Standard Port 80, der Container hat eine komplett eigene IP für sich
- Steht auf Auto
- Nein

Mit fällt aber gerade auf das er aktuell auch keine Verbindung zum KNX Gateway aufbauen kann... also kann es natürlich auch daran liegen.
