### ISSUE TITLE
Update to 2.6 not possible

### ISSUE THREAD

**Issue by Superwuzy** [brutella/hkknx-public#270]
I'm having problems updating to hkknx 2.6 (Raspberry PI 4)

![Bildschirmfoto 2023-04-24 um 20 42 14](https://user-images.githubusercontent.com/17985563/234087757-6a2549b3-0513-4d57-9ff3-458e1bae8045.jpg)

I've tried to start the update several times but always with an error. Probably some files are missing.
The previous updates worked flawlessly.

**Comment by brutella** [comment]
Please restart hkknx and try again. See #262 #264

**Comment by Superwuzy** [comment]
Great response time! Yes, a restart solved the problem. The update was successful. Thanks! 👍
