### ISSUE TITLE
Won't update via Website

### ISSUE THREAD

**Issue by vinc32** [brutella/hkknx-public#271]
Showing:

"Das Update auf Version 2.6.0 ist fehlgeschlagen.. 
File '.hkknx.old' for the command is not found in https://github.com/brutella/hkknx-public/releases/download/2.6.0/hkknx-2.6.0_linux_arm.tar.gz"
when trying to update via Website.

**Comment by brutella** [comment]
Restart hkknx and try again.

**Comment by vinc32** [comment]
Easy fix - but now everything's working like a charm :)
