### ISSUE TITLE
Alarmanlage: keine Reaktion bei "erkannter Störung"

### ISSUE THREAD

**Issue by Graefer** [brutella/hkknx-public#272]
Hi,
ich habe eine Alarmanlage ("Sicherheitssystem") mit hkknx angelegt. Die Störungserkennung ist in hkknx angewählt und eine GA zugeordnet. Wird diese Gruppenadresse '1', tut sich in der Home App aber gar nichts. Ich denke das ist so nicht richtig und bitte um Überprüfung.
Danke
Graefe

**Comment by brutella** [comment]
Bitte poste mal einen Screenshot von den Einstellungen der Alarmanlage in hkknx.

**Comment by Graefer** [comment]
Bitteschön:
![IMG_1408](https://github.com/brutella/hkknx-public/assets/26072184/2ad2197c-0708-4f42-bb3e-c427d5650fa7)

**Comment by mbrockeu** [comment]
Gibt es den seitens HomeKit überhaupt ne Beschreibung was bei einer Störung passieren würde? 

Die Idee den Fehler der Scharfschaltung auf die Störung zu legen ist ne coole Idee.  Wollte das über scripts und ne notification machen. Zumindest die Scharfschaltquittierung

**Comment by brutella** [comment]
> Gibt es den seitens HomeKit überhaupt ne Beschreibung was bei einer Störung passieren würde?

Nein, nicht das ich wüsste.

**Comment by mbrockeu** [comment]
> > Gibt es den seitens HomeKit überhaupt ne Beschreibung was bei einer Störung passieren würde?
> 
> Nein, nicht das ich wüsste.

Was passiert den dann mit den Werten? Reichst du das nur durch?

**Comment by brutella** [comment]
Besteht das Problem weiterhin?
