### ISSUE TITLE
Thermostateinstellung wechselt von alleine

### ISSUE THREAD

**Issue by mbrockeu** [brutella/hkknx-public#273]
Ich habe irgendwie ein merkwürdiges Problem mit den Thermostaten und dem Verhalten. 

Da es keine Gruppenadresse gibt mit der man den Modus vorgeben kann muss ja irgendwas übergeben werden, oder aber HomeKit selbst hat ein Bug. 

Das Problem ist, in der Home App wird ständig der Modus entweder wieder auf heizen oder aus gesetzt. Ich hatte alle auf automatisch gestellt, da ich keine Lust habe manuell zwischen kühlen und heizen zu wechseln. 
Vermutlich ist der Status egal, da eh der Sollwert übergeben wird. Aber verwirrend ist es dennoch. 

Konnte das jemand auch so beobachten?

**Comment by brutella** [comment]
Wenn du die Soll- und Ist-Temperaturen mit Gruppenadressen versehen hast, dann wird der aktuelle Status (Heizen, Aus) anhand der Temperaturen berechnet. Wenn Ist < Soll → *Heizen*, ansonsten *Aus*.

**Comment by mbrockeu** [comment]
Das gibt die Bridge so mit? 
das wäre für meinen Status in der Anzeige nicht korrekt da er jetzt im Sommer kühlt. 

Es hat ja offenbar keine Auswirkung aber die Anzeige ist somit nicht so ganz richtig.

**Comment by brutella** [comment]
> Das gibt die Bridge so mit?

Ja, dass macht hkknx automatisch. Hatte ich mir mal so ausgedacht. Kann man aber auch noch verbessern, falls gewünscht.

**Comment by mbrockeu** [comment]
Also besser wäre es wenn man den Status vom Bus mitgeben kann. Da würde es mir erstmal reichen wenn man den nur liest. Einzeln ändern würde eh nix bringen.

Es sei den ich baue mir ein Thermostat fürs Haus wo ich Heizen/Kühlen/Aus wählen kann um es an die Heizung zu geben.

**Comment by brutella** [comment]
Wenn man den Status des Temperaturreglers über eine KNX Gruppenadresse soll ändern können, muss man überlegen welche Stati unterstützt werden. In HomeKit gibt es Aus, Auto, Heizen, und Kühlen.

**Comment by Graefer** [comment]
Da (wie bi der Alarmanlage) vermutlich alle Zustände angezeigt werden, sollte man auch alle schreiben/lesen können. Notfalls kann man ja in den hkknx-Einatellungen die gleiche GA für unterschiedliche Zustände verwenden.

**Comment by brutella** [comment]
Kann das Issue geschlossen werden?
