### ISSUE TITLE
ETS6.1.0 (Build 5686) knxproj file cannot be imported (Unexpected namespace 'http://knx.org/xml/project/22')

### ISSUE THREAD

**Issue by moadl** [brutella/hkknx-public#275]
With the latest version of hkknx (2.6.0) and the latest updated version of ETS 6.1.0 (Build 5686) it is no longer possible to import the created knxproj files due to the following error message:
Unexpected namespace 'http://knx.org/xml/project/22'
Attached you can find an knxproj file which was tested to import in a local hkknx instance.

[testproject.zip](https://github.com/brutella/hkknx-public/files/11614699/testproject.zip)

**Comment by brutella** [comment]
Thanks for providing a test project. 

Please checkout the [pre-release 2.7.0-b2](https://github.com/brutella/hkknx-public/releases/tag/2.7.0-b2) which should support the new ETS project exports.

**Comment by moadl** [comment]
seems to be working like a charme again!
thanks for the quick fix and release 👍
