### ISSUE TITLE
HKKNX startet nach update auf 2.7.0 Beta nicht mehr

### ISSUE THREAD

**Issue by Spont09** [brutella/hkknx-public#278]
Nach dem Update auf die 2.7.0 beta startet HKKNX nicht mehr.

HKKNX läuft unter Debian. 

`root@HKKNX:/usr/bin/database# systemctl status hkknxd.service
* hkknxd.service - hkknx Service
     Loaded: loaded (/etc/systemd/system/hkknxd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-06-10 11:02:18 CEST; 2min 55s ago
    Process: 391 ExecStart=/usr/bin/hkknx -db /usr/bin/database (code=exited, status=2)
   Main PID: 391 (code=exited, status=2)
        CPU: 6ms

Jun 10 11:02:18 HKKNX systemd[1]: hkknxd.service: Scheduled restart job, restart counter is at 6.
Jun 10 11:02:18 HKKNX systemd[1]: Stopped hkknx Service.
Jun 10 11:02:18 HKKNX systemd[1]: hkknxd.service: Start request repeated too quickly.
Jun 10 11:02:18 HKKNX systemd[1]: hkknxd.service: Failed with result 'exit-code'.
Jun 10 11:02:18 HKKNX systemd[1]: Failed to start hkknx Service.

**Comment by dkreutzer** [comment]
Vermutlich hängt das mit den geänderten Parametern zusammen. Haben alle nun ein doppeltes Minus (--) statt einen einfachen. War zumindest in dem Bild b2 so

**Comment by brutella** [comment]
So wie @dkreutzer korrekt erkannt, gab es bei 2.7.0 eine Änderung bei der Verarbeitung der Kommandozeilen Parameter. Das Problem ist jetzt in [2.7.0-b4](https://github.com/brutella/hkknx-public/releases/tag/2.7.0-b4) behoben.
