### ISSUE TITLE
Thermostat dauerhaft "Aus"

### ISSUE THREAD

**Issue by dj95** [brutella/hkknx-public#283]
Hallo,

seit dem Update auf hkknx 2.7.0 kann ich in HomeKit keine Thermostate mehr verwenden. Die Thermostate sind minimal konfiguriert (was in 2.6 auch entsprechend gut funktioniert hat). Hier ein Screenshot.

<img width="1494" alt="Screenshot 2023-10-04 at 17 02 35" src="https://github.com/brutella/hkknx-public/assets/4348959/bc4f5469-7cf6-45d8-be11-d05b5f925e4a">

Nach dem Update auf 2.7.0 wird in der Home App leider nur noch der Status "Aus" angezeigt und es gibt keine Möglichkeit diesen wieder auf "Heizen" zu ändern. Ein Ändern des Status mit der Home-Configurator App ist möglich. Wenn in hkknx weitere Adressen für die Konfiguration der verschiedenen Modi gesetzt werden, taucht auch leider keine Auswahl in der Home App auf, um das Thermostat wieder auf "Heizen" zu stellen.

Getestet ist das ganze mit der Home App unter iOS 17.0.2. Hkknx läuft auf einem Raspberry Pi in der Version 2.7.0.

Gibt es irgendeine Fehlkonfiguration? Welche Voraussetzungen müssen getroffen werden, dass das Thermostat auch wieder auf "Heizen" gestellt werden kann?

Vielen Dank

**Comment by brutella** [comment]
> Welche Voraussetzungen müssen getroffen werden, dass das Thermostat auch wieder auf "Heizen" gestellt werden kann?

Hab gerade eine neue Version [2.7.1-b1](https://github.com/brutella/hkknx-public/releases/tag/2.7.1-b1) hochgeladen, die dieses Problem beheben soll. Funktioniert es damit?

**Comment by chef76** [comment]
2.7.1-b1 behebt das Problem. Vielen Dank für die schnelle Hilfe!

**Comment by brutella** [comment]
Version [2.7.1](https://github.com/brutella/hkknx-public/releases/tag/2.7.1) wurde soeben veröffentlicht. Das Problem sollte somit gelöst sein.
