### ISSUE TITLE
Corrupt/won't start after shutdown

### ISSUE THREAD

**Issue by derfritz1** [brutella/hkknx-public#285]
Hallo,

ich hatte jetzt wiederholte male den Fall, dass hkknx nicht mehr startete nach unerwartetem Spannungsverlust. So weit so nachvollziehbar.
Jetzt habe ich vor geplanter Abschaltung hkknx per ssh heruntergefahren und erst dann abgeschaltet, und trotzdem scheint das image danach zerstört - hkknx startet nicht. Ich muss neu flashen und ein Backup einspielen. Das ist leider sehr ärgerlich auf Dauer.

Woran kann es liegen? Verwende eine 32GB Marken-Micro-SD.

Vielen Dank!

**Comment by brutella** [comment]
Welche Fehlermeldung wird angezeigt, wenn du hkknx starten möchtest?

**Comment by derfritz1** [comment]
Sorry, die Information fehlte: Es ist ein Headless RaspberryPi, und er bootet schlicht nicht. Auch eine ssh-Verbindung ist dann nicht möglich.

**Comment by brutella** [comment]
Hm, dann scheint es ein Problem mit der Hardware oder der SD-Karte zu geben. 🤔

**Comment by brutella** [comment]
Ist das Problem noch aktuell?
