### ISSUE TITLE
Problem importing knxproj

### ISSUE THREAD

**Issue by gson** [brutella/hkknx-public#287]
Hi,

Evaluating the tool, but can't import the knx project. Got the knx project from my electrician and would guess it is ETS6. The file unzips and seems valid, but get an error message at import. Any suggestion where to start?

<img width="385" alt="image" src="https://github.com/brutella/hkknx-public/assets/169327/f3228982-5cd1-4cde-b905-4b289a105632">

<img width="248" alt="image" src="https://github.com/brutella/hkknx-public/assets/169327/49158172-8b8d-4a47-b587-7deb72150efe">

**Comment by brutella** [comment]
Are you using the latest version of hkknx?
Is your KNX project password-protected?

**Comment by gson** [comment]
I don't have a working copy of ETS, but guess no password because I can read all xml files in the unzipped package.

[2.7.1]  (2023-10-06T15:19:28+02:00)

**Comment by brutella** [comment]
Can you unzip the `P-0350.zip` file in Finder?

**Comment by gson** [comment]
asks for password (that is it I guess), will try to get it from the electrician

**Comment by gson** [comment]
He had a password on it, thanks for very quick feedback!
