### ISSUE TITLE
Szenen werden erst nach wiederholtem auswählen in Home App aktiviert

### ISSUE THREAD

**Issue by Elektroarzt** [brutella/hkknx-public#29]
Wenn eine umfangreichere Szene in Home ausgewählt wird (13 Leuchtengruppen), erscheint diese oft erst beim zweiten oder dritten auswählen dort auch als aktiv. Home führt die Szene halb aus und nach etlichen Sekunden wird dann der Rest ausgeführt.

**Comment by brutella** [comment]
Hast du schonmal andere HomeKit Apps ausprobiert?
Womöglich liegt das Problem bei der Apple Home App?
