### ISSUE TITLE
Group addresses after multiple imports

### ISSUE THREAD

**Issue by mrmatze007** [brutella/hkknx-public#291]
Mein ETS-Projekt wurde über die Zeit schon mehrfach ergänzt und geändert. Nach jeder Änderung starte ich einen erneuten Import des kompletten Projekts. Bei jedem Import werden alle Gruppenadresse neu angelegt, ohne dass ein Duplikate-Check stattfindet.

Daraus resultiert:
Jede GA ist mehrfach angelegt - teilweise ohne Änderung, teilweise mit Änderung.

Folgendes Verhalten würde ich mir wünschen:
Beim Import wird geprüft, ob die Gruppenadresse bereits angelegt ist.
- Falls nein: GA wird angelegt.
- Falls ja: Bestehende GA wird aktualisiert.

Vielen Dank für das tolle Projekt!

**Comment by brutella** [comment]
Du kannst das "alte" Projekt einfach aus hkknx entfernen. Damit verschwinden auch die "alten " GA-Einträge.

In Zukunft soll es einen "Aktualisieren" Button geben, der automatisch das alte Projekt löscht und das neue Projekt importiert.
