### ISSUE TITLE
Wrong types

### ISSUE THREAD

**Issue by sdonati8484** [brutella/hkknx-public#295]
Hi, in my knxproj temperature sensor outputs are defined as 9.001 values but hkknx interface see them as DPST-7-1. Am I missing something or there is something not working correctly?
See attachments

![immagine](https://github.com/brutella/hkknx-public/assets/155996455/b3427b24-ce19-4d8b-94dd-39f847d01750)
![immagine](https://github.com/brutella/hkknx-public/assets/155996455/ebaf4b0c-4661-484f-954d-57ddc489c1a8)

If you need more information ask please
Greetings,
Stefano

**Comment by sdonati8484** [comment]
No, the project is the same. To check I re-exported and re-uploaded today

Da: hr-automation ***@***.***>
Inviato: lunedì 8 gennaio 2024 17:30
A: brutella/hkknx-public ***@***.***>
Cc: sdonati8484 ***@***.***>; Author ***@***.***>
Oggetto: Re: [brutella/hkknx-public] Wrong types (Issue #295)


Is your hkknx project file ident to the ets project?

It looks like that in the uploaded project file to hkknx the datatype was 7.001

**Comment by brutella** [comment]
hkknx will use the data type that you've defined under the "Data Type" for the characteristic "Current Temperature" – so in your case it will use 9.001. Can you verify that this works?

**Comment by sdonati8484** [comment]
For temperature sensor it works, even if wrong data type is showed, temperatures seem coherent. 
However for writing data (eg fot thermostat) it should be nice if data type detected is correct, as it is it doesn't bring much peace of mind

**Comment by brutella** [comment]
> However for writing data (eg fot thermostat) it should be nice if data type detected is correct, as it is it doesn't bring much peace of mind

hkknx uses the data type specified for the characteristic in the web interface. It doesn't actually matter what's specified in the ETS project.

If you want, you can send your ETS project  to hkknx@hochgatterer.me so that I can take a look why the wrong data type is imported.

**Comment by sdonati8484** [comment]
Ok, sent project in private

Da: Matthias ***@***.***>
Inviato: giovedì 11 gennaio 2024 19:30
A: brutella/hkknx-public ***@***.***>
Cc: sdonati8484 ***@***.***>; Author ***@***.***>
Oggetto: Re: [brutella/hkknx-public] Wrong types (Issue #295)


However for writing data (eg fot thermostat) it should be nice if data type detected is correct, as it is it doesn't bring much peace of mind

hkknx uses the data type specified for the characteristic in the web interface. It doesn't actually matter what's specified in the ETS project.

If you want, you can send your ETS project to ***@***.******@***.***> so that I can take a look why the wrong data type is imported.

**Comment by brutella** [comment]
Thanks for providing a project. I've just uploaded version [2.8.0-b5](https://github.com/brutella/hkknx-public/releases/tag/2.8.0-b5) which should fix this issue.

(The problem was that some group addresses (with *DPST-9-1*) are actually used by communication objects which define their datapoint type as *DPST-7-1*.)

**Comment by sdonati8484** [comment]
Hi Matthias,
thank you for the fast update.
With 2.8.0-b5, now temperature sensors are recognized correctly as DPST-9-1. But temperature setpoint are still recognized as DPST-7-1.
Can you check please?

***@***.***


Greetings,
Stefano

Da: Matthias ***@***.***>
Inviato: venerdì 12 gennaio 2024 17:28
A: brutella/hkknx-public ***@***.***>
Cc: sdonati8484 ***@***.***>; Author ***@***.***>
Oggetto: Re: [brutella/hkknx-public] Wrong types (Issue #295)


Thanks for providing a project. I've just uploaded version 2.8.0-b5<https://github.com/brutella/hkknx-public/releases/tag/2.8.0-b5> which should fix this issue.

(The problem was that some group addresses (with DPST-9-1) are actually used by communication objects which define their datapoint type as DPST-7-1.)

**Comment by brutella** [comment]
Should be fixed by version [2.8.0-b6](https://github.com/brutella/hkknx-public/releases/tag/2.8.0-b6)

**Comment by sdonati8484** [comment]
Confirm, fixed in b6. Thank you!
