### ISSUE TITLE
Missing raspio-custom images under release section

### ISSUE THREAD

**Issue by regetskcob** [brutella/hkknx-public#302]
I'm currently facing an issue, since the mentioned raspio images from the installation guide can not be found.

<img width="842" alt="Screenshot 2024-03-01 at 12 25 53" src="https://github.com/brutella/hkknx-public/assets/52231719/c4770a72-338e-48e7-8497-08078051ea0f">

<img width="1148" alt="Screenshot 2024-03-01 at 12 25 05" src="https://github.com/brutella/hkknx-public/assets/52231719/7cddfe2a-0d41-4c77-add4-19d69215c37e">

**Comment by regetskcob** [comment]
@brutella I just found, that https://github.com/brutella/hkknx-public/releases/tag/2.6.0 was the last release containing the mentioned image. Can I use it and then update up to the current state? :D

**Comment by regetskcob** [comment]
@brutella  ok, seems like my thoughts were a little bit to easy. Just put the mentioned release-image on a SD card (using Pi Imager) and put this into my RaspPi 5 (8 GB) but nothing happens, only STAT LED is green and also LAN LEDs are not flashing...

![IMG_8834](https://github.com/brutella/hkknx-public/assets/52231719/c1af0628-3b49-461e-b684-08c0b44a40da)
![IMG_8835](https://github.com/brutella/hkknx-public/assets/52231719/acb0eaad-5c02-4bdf-b7d9-d83d79cac196)

I'll try the manual install now...

**Comment by brutella** [comment]
This should be fixed by now. There will be a custom Raspberry Pi disk image available for every release from now on.

**Comment by regetskcob** [comment]
To be honest. By looking at the fact, that you charge ~300€ for the software, it's a mess that it took nearly half a year to fix it. 

In the meantime I switched from the demo to HA and I'm very fine with it, without having to pay for a license without getting immediate support.

**Comment by brutella** [comment]
The primary way of installing hkknx never was the Raspberry Pi image. The new image is not based on the Raspberry Pi OS anymore. That's why it took some effort to implement that.

**Comment by regetskcob** [comment]
Since I really love the UI of the new Web App, I'll try v3.0 out, since the recent beta's seems to not have the RPI Image within. :)

**Comment by brutella** [comment]
Right, pre-releases are not available as Raspberry Pi disk images – only final releases are.
