### ISSUE TITLE
Error importing ETS 6.2.0 project file

### ISSUE THREAD

**Issue by dkreutzer** [brutella/hkknx-public#303]
Using 2.9.0-b2, when importing an ETS project file that was exported with ETS 6.2.0 I get the following error:

> import: Unexpected namespace 'http://knx.org/xml/project/23'

Interesting thing is that on my "productive" hkknx that runs inside homeassistant as add-on it simply crashes and gets restarted. But when running it locally on macOS I get the above error.

Beside that I noticed two minor issues in the beta
- using upload as new project I get no message that is it already loaded, but the upload button simply stays disabled
- on a fresh installation when it fails the first time there is no retry or update button (so you have to remove it first)

**Comment by brutella** [comment]
Thanks for reporting this issue. I will take a look at this issue in the next few days.

**Comment by cptbalusgit** [comment]
This behavior happens on my setup with V2.8.1 on RPi 4 as well with exported ETS 6.2.0 files. Tried on numerous browsers, restart the bridge and so on.
- Using the update button "update" message appears on old project file and "import" message and spinner appears on new one. But it "never" ends the job. Well I let it run for >1h in the background. 
- Switching e.g. from settings to status panel at the top will lead to the described error above.

**My suspicion therefore would be: It is linked to the ETS 6.2.0 files and not necessarily to the 2.9.0-b2.**

Unfortunately trying to import as a new project file does not work as the pop-up UI does not work properly. Might be separate issue. Did not do this for a while and just tried it as workaround.
- Able to select the new project file.
- Hover over the select-file-space shows that it seems to be there and loaded, but it is not visibly shown as file name in the field.
- Upload button stays in light blue and does not allow the upload - probably as the file name is not visibly shown in the field.

**Comment by brutella** [comment]
This issue should be fixed in [2.8.2-b1](https://github.com/brutella/hkknx-public/releases/tag/2.8.2-b1)
