### ISSUE TITLE
log stream cnndbkcm7a6c1qqfuuug: waiting for task...

### ISSUE THREAD

**Issue by guyyannick** [brutella/hkknx-public#304]
Hallo,

ich bekomme folgende Log-Einträge...  lässt sich die Meldung unterdrücken ? Was ist hier die Ursache ?

DEBUG	2024/03/11 15:18:14	script.go:482	log stream cnndbkcm7a6c1qqfuuug: waiting for task...
DEBUG	2024/03/11 15:18:14	script.go:482	log stream cnndbkcm7a6c1qqfuuug: waiting for task...
DEBUG	2024/03/11 15:18:14	script.go:482	log stream cnndbkcm7a6c1qqfuuug: waiting for task...
DEBUG	2024/03/11 15:18:15	script.go:482	log stream cnndbkcm7a6c1qqfuuug: waiting for task...
DEBUG	2024/03/11 15:18:15	script.go:482	log stream cnndbkcm7a6c1qqfuuug: waiting for task...
DEBUG	2024/03/11 15:18:15	script.go:482	log stream cnndbkcm7a6c1qqfuuug: waiting for task...

Thanks

**Comment by brutella** [comment]
Kann es sein, dass du keine Verbindung zum KNX Gateway hast? 
(Diese Log-Meldungen sind nur informativ und können ignoriert werden.)

**Comment by guyyannick** [comment]
die Verbindung war da... Nach einem Restart sind die Logs Einträge auch weg !
