### ISSUE TITLE
Mehr als 149 geraete supporten, evtl. mit childbridges

### ISSUE THREAD

**Issue by 1vnt** [brutella/hkknx-public#307]
Ich habe das Limit erreicht. Ich moechte trotzdem, ohne z.B. eine zweite Instanz von hkknx laufen zu lassen, mehr geraete hinzufuegen.

Andere Projekte machen dies einfach mit child-bridges, hkknx koennte ja auch einfach mehrere Bridges verwalten. Siehe https://github.com/homebridge/homebridge/wiki/Child-Bridges

**Comment by brutella** [comment]
Duplicate of #253
