### ISSUE TITLE
Update from 2.8.2-b1 to 2.8.2  broke write/read access to KNX bus

### ISSUE THREAD

**Issue by cptbalusgit** [brutella/hkknx-public#308]
After updating from 2.8.2-b1 to 2.8.2 write/read access to KNX bus did not work properly. Roll back to 2.8.2-b1 fixed issue. No changes to settings and so on between Update/Downgrade.

**Comment by brutella** [comment]
What kind of error did you see in the logs when writing/reading from the KNX bus?
Was hkknx able to connect to the KNX gateway?

There was no change in this regard between version 2.8.2-b1 and 2.8.2. Maybe your issue is related to a different problem.

**Comment by cptbalusgit** [comment]
Connection to KNX Gateway shown as "secured connection (TCP)" and Homekit Bridge as "Available" in both cases. Initialisation of all HK devices was successful as well based on settings tab.

I will upgrade and downgrade and run complete system protocol and GA monitor in the background while doing so. Will compare and let you know.

**Comment by cptbalusgit** [comment]
Well - after doing it again, now for the fourth time overall, it works as expected again and no apparent issues in the logs visible with 2.8.2. Read and Write of values to GAs works as expected. Closing issue. Don't really have an explanation, as it was reproducable at least twice before after restarts of bridge itself and Pi as well.

**Comment by cptbalusgit** [comment]
alright so issue came back after a while - here is the system protocol screenshot of a write call to GA 1/0/28 not working on 2.8.2.  
...79 is hknx
 ...219 is knx gateway.
 ...178 is hk hub = apple tv 4k
 
![2 8 2](https://github.com/brutella/hkknx-public/assets/162726110/2013ce64-df48-4eb5-b416-5e5debda20e6)

same call after rolling back to 2.8.2-b1
![2 8 2-b1](https://github.com/brutella/hkknx-public/assets/162726110/ec2d51cd-2d52-44c1-9a1e-83ec49fb75da)

hknx on rpi and knx gw currently still on the same default VLAN and ip address range within the network. I will check tomorrow morning again to see if the closed network communication issue occurs after time again on 2.8.2-b1.

I did not change any intra VLAN rules on xxx.xxx.1.xxx - none of the two ports are isolated. I can still ping both IPs.

**Comment by brutella** [comment]
What hardware are you using as KNX gateway? Do you have other software connected to your KNX IP gateway?

**Comment by cptbalusgit** [comment]
ISE Smart Connect KNX Remote Access. I did not update to its new V7 SW yet. So still on V6.1.392. Besides ETS SW 6.2.1 when I use it - no. No changes on the KNX GW configuration itself. Connection confirmed in hknx UI as well as "securely connected (TCP)". Works in this setup smooth since Aug 2023.

**Comment by cptbalusgit** [comment]
So with 2.8.2-b1 it still works without issues after 2 days.

**Comment by dornadeluxe** [comment]
I have the same/simular issue and it started either with the 2.8.2 update or the new ios 14.5. So far hkknx has been rock stable for me but now it looses connection to the KNX bus after a while (several hours to days). I recognize when I can't control my devices in homekit anymore. They still show up there as available and also on the hkknx web interface all looks well but I can see that the connection is lost because the bus monitor is just dead. The only thing that helps is to restart hkknx or the complete raspi. Will try to roll back to an older version.

**Comment by brutella** [comment]
@dornadeluxe Do you find any log output which indicates an error?

Can you find an mDNS entry for the HomeKit bridge when the connection seems lost?
https://hochgatterer.me/hkknx/docs/help/homekit-connection-issues/

**Comment by brutella** [comment]
In version 3.0, where you can control accessories directly in the web interface, you will be able to check if the connection between KNX and hkknx or between hkknx and HomeKit is broken.
