### ISSUE TITLE
Issue with Light Bulb - "relative color temperature"

### ISSUE THREAD

**Issue by thorsten-gehrig** [brutella/hkknx-public#310]
Hi
i have an LED with tunable white connected via DALI to KNX.
It´s an ABB-DALI interface and a Lunatone DALI Dimmer (LUNATONE 89453833 DALI DT6 2-Kanal LED Dimmer CV)
The Relative Color Temperature needs to be reversed to what I can select today.
So DPST-5-1 (0-100%) should be DPST-5-1 (100-0%).

May you consider this for a future release?
Thank you
Best
Thorsten

**Comment by brutella** [comment]
We can definitely consider this in a future version. Thanks for reporting.

**Comment by brutella** [comment]
Version [3.0.0-a3](https://github.com/brutella/hkknx-public/releases/tag/3.0.0-a3) now supports warm white percentage for relative color temperature.

Please try it out and report back if it works for you.

**Comment by thorsten-gehrig** [comment]
Works like a charm!
Thank you - appreciate!!!
