### ISSUE TITLE
knxproj Import fails with "Unexpected namespace" error

### ISSUE THREAD

**Issue by pfeifix** [brutella/hkknx-public#311]
Ich habe versucht, mein Projekt zu aktualisieren. Der Vorgang dauert ewig (zeigt "Wird aktualisiert..." bzw. "Wird importiert..." an), wenn ich nach 5 Minuten von den Einstellungen weg und wieder zurück wechsle, erscheint ein rotes "x" mit der Fehlermeldung

'Unexpected namespace 'http://knx.org/xml/project/23'

Ich habe ein passwortgeschütztes ETS6-Projekt.

Was läuft hier schief?

**Comment by brutella** [comment]
Versuch es mal mit der aktuellsten Version [2.8.2](https://github.com/brutella/hkknx-public/releases/tag/2.8.2).

**Comment by pfeifix** [comment]
Ich bin auf der Beta [v2.9.0-b2]. Kann ich da problemlos downgraden?

**Comment by brutella** [comment]
Ja, sollte keine Problem sein.

**Comment by pfeifix** [comment]
Hat geklappt, danke!
