### ISSUE TITLE
Anzeige Gerätestatus bei Initialisierung

### ISSUE THREAD

**Issue by chef76** [brutella/hkknx-public#316]
Schon seit einigen Versionen wird bei mir der Gerätestatus bei Initialisierung nicht mehr angezeigt. Auch in der aktuellsten Vorabversion 3.0.0-a3 ist das noch so:

![image](https://github.com/brutella/hkknx-public/assets/69462419/0ab3c83a-5667-4071-bb6c-e858a123f24d)

**Comment by brutella** [comment]
Sollte in Version [3.0.0-a4](https://github.com/brutella/hkknx-public/releases/tag/3.0.0-a4) behoben sein.
