### ISSUE TITLE
Diagramme funktionieren nicht (mehr)

### ISSUE THREAD

**Issue by chef76** [brutella/hkknx-public#317]
Ich habe die Datenaufzeichnung aktiviert, dann hat er auch eine aufgezeichnete Datenmenge angezeigt. Dann noch mal deaktiviert und die Daten gelöscht und später wieder aktiviert. Nun werden keine Daten mehr aufgezeichnet

**Comment by brutella** [comment]
Hast du versucht hkknx neu zu starten? Bekommst du eine Fehlermeldung im Log angezeigt?

**Comment by chef76** [comment]
Ok, da hätte ich auch drauf kommen können. 😆 

Danke, jetzt gehts!
