### ISSUE TITLE
Chart in Statistiken nicht sichtbar 

### ISSUE THREAD

**Issue by mbrockeu** [brutella/hkknx-public#321]
Bei den Charts in der V3 habe ich die Einstellungen aktiviert und er belegt offenbar auch Speicher. Die möglichen Geräte stehen zur Auswahl es wird aber kein Chart angezeigt. 

Browser am Handy und PC jeweils Safari

**Comment by brutella** [comment]
@mbrockeu Besteht das Problem weiterhin?

**Comment by mbrockeu** [comment]
Ja funktioniert weiterhin nicht. Er zeigt einfach nix an, sieht so aus:

![image](https://github.com/brutella/hkknx-public/assets/16849873/eed52fd7-6e45-48c8-b291-bfc4bc993300)

**Comment by brutella** [comment]
Welchen Browser mit welcher Version verwendest du? (Ich vermute mal dein Browser ist nicht aktuell.)

**Comment by mbrockeu** [comment]
Habe aktuell Safari V17. Im Chrome Version 125.0.6422.113 (Offizieller Build) (arm64) gehts auch nicht auf dem Mac

**Comment by brutella** [comment]
Hm, kannst du mal nachsehen, ob im Safari unter Develop → Show JavaScript Console irgendwelche Fehler angezeigt werden?

**Comment by mbrockeu** [comment]
![image](https://github.com/brutella/hkknx-public/assets/16849873/411e052a-6d22-4fb2-9c46-31f34dd2459e)

**Comment by brutella** [comment]
Bitte Version [3.0.0-a9](https://github.com/brutella/hkknx-public/releases/tag/3.0.0-a9) testen. Danke.

**Comment by guyyannick** [comment]
Bei mir scheint das Problem behoben zu sein ! Die Charts sind im Chrome (125.0.6422.78 )  und Safari (17.5) sichtbar: OS 14.5 ,
