### ISSUE TITLE
Sometimes I have issue to connect to the web page

### ISSUE THREAD

**Issue by MarcZimmi** [brutella/hkknx-public#322]
Sometimes I have the issue that the site ist not available and all devices in Home Kit are offline?
Is there an issue on my side and a way to solve it?

![Fehler](https://github.com/brutella/hkknx-public/assets/170747466/0e033e4f-c2ba-49b6-892d-c8509f8af11a)

**Comment by brutella** [comment]
Which version do you have installed? 

Unfortunately there was a bug in version 3.0.0-a6 where the app crashes when creating a new accessory. This issue is now resolved in version [3.0.0-a7](https://github.com/brutella/hkknx-public/releases/tag/3.0.0-a7).

Might this be related to your issue?

**Comment by MarcZimmi** [comment]
Yes, is there a way to update to New Version by terminal?

**Comment by brutella** [comment]
Unfortunately you will have to edit the `server.json` file inside your --db folder to resolve this issue. There you have to delete the last array entry under the "accessories" key. Then you can restart hkknx and update to the latest version.

**Comment by brutella** [comment]
Did you manage to resolve this issue?

**Comment by MarcZimmi** [comment]
Is solved. Thank you!
