### ISSUE TITLE
Abstürze in 3.0.0-B7

### ISSUE THREAD

**Issue by mbrockeu** [brutella/hkknx-public#323]
Ich hatte gestern mal die aktuellste Version installiert, vorher die B5.
Leider ist die Bridge beim ausführen von Befehlen offenbar immer wieder neugestartet bzw. die Geräte haben sich wieder neu initialisiert.

Hat das Problem noch jemand?
Ich habe jetzt wieder die B5 (Downgrade über die Webseiten funzt super) und nun läuft wieder alles stabil.

**Comment by brutella** [comment]
Konntest du dazu im Log etwas verdächtiges finden?

**Comment by mbrockeu** [comment]
Ich habe das mal auf meiner nicht so wichtigen Instanz noch mal installiert. Da laufen nur meine "Sensoren". 
Er hat die 74 Geräte abgefragt mit dem Output unten, danach hat er wieder von Vorne angefangen und die Aufzeichnung selbst gestoppt.

![image](https://github.com/brutella/hkknx-public/assets/16849873/4a71f7b8-f194-4675-a295-f90f5185edb9)

Kann ich noch irgendwo anders was schauen?

**Comment by brutella** [comment]
Wie führst du diese Instanz aus? Gibt es ein Crashlog, wo man sieht, warum hkknx womöglich abgestürzt ist?

(Wenn in hkknx ein fataler Fehler auftritt, dann stürzt auch das Systemprotokoll ab und liefer keine Daten mehr.)

**Comment by mbrockeu** [comment]
Läuft auf einem Ubuntu, ich hab mal in die Logs geschaut und das gefunden. Wiederholt sich regelmäßig

![Bildschirmfoto 2024-05-27 um 10 27 57](https://github.com/brutella/hkknx-public/assets/16849873/17bb5915-c523-4590-a676-40070ef2c178)

**Comment by brutella** [comment]
Ok, damit kann ich was anfangen. Danke schonmal.

**Comment by brutella** [comment]
Das Problem sollte mit Version [3.0.0-a8](https://github.com/brutella/hkknx-public/releases/tag/3.0.0-a8) behoben sein.

**Comment by mbrockeu** [comment]
Scheint soweit erstmal stabil. Danke
