### ISSUE TITLE
A switch (which sets a scene) should not be turned off automatically

### ISSUE THREAD

**Issue by brutella** [brutella/hkknx-public#326]
If you use a switch in a HomeKit scene to set a KNX scene, you would expect that the state of the scene in HomeKit is shown as active, once the switch is turned on. This is not the case because the switch is automatically turned off after 100ms.

We should fix that and keep the switch turned on as long as we don't receive a new scene number from the configured group address.

Discussed in #312 
Related to #44

**Comment by mbrockeu** [comment]
Hm ich sehe das Ding hier gerade und wundere mich nun nicht mehr warum meine zentralbefehle nicht mehr gehen weil die Schalter die ganze Zeit an sind. 

Das war die perfekte Lösung das sich das Teil einfach zurücksetzt. Welche Alternative gibts?  Und nein ich möchte keine 0 schreiben dann fährt es nämlich hoch.

**Comment by brutella** [comment]
Kannst du bitte genauer erklären, warum deine Zentralbefehle nicht mehr funktionieren.

**Comment by mbrockeu** [comment]
Ich habe eine GA für z.B. alle Rollos Hoch bzw. Runter 2/0/0, bei 1 fährt alles runter, bei 0 eben alles hoch. Ich habe dafür jeweils zwei Schalter angelegt mit eben "Szene" und als DPT-1 einmal mit 1 und einmal mit 0.

Diese Schalter sind z.b. in meiner Gute Nacht Szene in HomeKit, beim aktivieren wird diese getriggert. Dadurch, dass sich der Status aber nicht mehr zurücksetzt ist der Schalter jetzt eben immer an. HomeKit führt ihn beim aktivieren der Szene nicht mehr aus, weil eben schon an.  (Das gleiche Problem wird übrigens auch derjenige haben welcher jetzt über den Schalter die gleiche Szene noch mal ausführen möchte mit der gleichen Nummer sofern nicht zurückgesetzt wurde.)

Verstehe nicht was die Änderung jetzt für einen Mehrwert hat, wenn KNX kein Szenenzustand kennt warum dann in HomeKit abbilden. Den wie du schon beschrieben hast, HomeKit zeigt eine Szene als "Aktiv" an wenn die definierten Parameter passen, im dümmsten Fall steht der Schalter auf "Ein" und man denkt die Szene ist an es hat sich aber schon alles geändert. Aber das nur am Rande ;-)

**Comment by brutella** [comment]
Macht die aktuelle Implementierung immer noch Probleme? Wie bereits erwähnt, kann diese Änderung immer noch vor dem Launch der Version 3.0 rückgängig gemacht werden.

**Comment by blue-brook** [comment]
Was spricht gegen rückgängig machen das war doch früher besser oder?

**Comment by brutella** [comment]
Wird im nächsten Update rückgängig gemacht.
