### ISSUE TITLE
write udp: use of closed network connection

### ISSUE THREAD

**Issue by thpeetz** [brutella/hkknx-public#327]
Hi there.

I have a recurring issue with hkknx. Basically everything works fine after a system restart, then after a while I can't control the devices I added via hkknx anymore on Apple Home.

Example output in the system log triggered by me using Apple Home to try and activate an outlet:

`<head></head>
Type | Time | Source | Message
-- | -- | -- | --
DEBUG | 2024/06/22 13:00:01 | characteristics.go:180 | {"characteristics":[{"aid":4,"iid":10,"value":1}],"pid":0}
DEBUG | 2024/06/22 13:00:01 | writer.go:45 | write 1 to 4/0/20
DEBUG | 2024/06/22 13:00:01 | writer.go:48 | write udp 169.254.138.248:36153->192.168.68.70:3671: use of closed network connection
DEBUG | 2024/06/22 13:00:01 | bool.go:37 | write udp 169.254.138.248:36153->192.168.68.70:3671: use of closed network connection
DEBUG | 2024/06/22 13:00:01 | characteristics.go:259 | {"characteristics":[{"aid":4,"iid":10,"status":-70402}]}
DEBUG | 2024/06/22 13:00:01 | logger.go:161 | "PUT http://KNX-Homekit_Bridge._hap._tcp.local/characteristics HTTP/1.1" from 192.168.68.50:49366 - 207 56B in 2.845513ms
DEBUG | 2024/06/22 13:00:43 | characteristics.go:144 | {"characteristics":[{"aid":1,"iid":7,"value":"2.8.2"}]}
DEBUG | 2024/06/22 13:00:43 | logger.go:161 | "GET http://KNX-Homekit_Bridge._hap._tcp.local/characteristics?id=1.7 HTTP/1.1" from 192.168.68.50:49366 - 200 55B in 492.603µs
DEBUG | 2024/06/22 13:01:48 | characteristics.go:144 | {"characteristics":[{"aid":1,"iid":7,"value":"2.8.2"}]}
DEBUG | 2024/06/22 13:01:48 | logger.go:161 | "GET http://KNX-Homekit_Bridge._hap._tcp.local/characteristics?id=1.7 HTTP/1.1" from 192.168.68.50:49366 - 200 55B in 554.79µs
`

At the same time the hkknx Group Monitor doesn't record anything anymore, and hkknx scripts stop working.

I'm running hkknx 2.8.2 on a Raspberry Pi using the [disk image](https://github.com/brutella/hkknx-public/releases/tag/2.6.0) that is linked in the documentation. I updated hkknx from there using the web interface. The Pi is connected to my network by cable.

Things I've tried and that didn't change anything:
- starting from that disk image, manually install all available updates of libraries
- upgrade to 2.x pre-releases

I am unable to reproduce the "crash", whatever it may be. It happens about once per 24 hours. I have multiple scripts running continuously but they don't spam messages - they mainly wait for specific times of the day to fire a single message.

Any help would be appreciated. I'm not enough of an expert to know if this is a duplicate of #308.

**Comment by brutella** [comment]
It looks like your connection to the KNX gateway gets closed after some time. 

What KNX IP gateway are you using?

**Comment by thpeetz** [comment]
I have an MDT [SCN-IP000.03](https://www.mdt.uk/fileadmin/user_upload/user_upload/download/MDT_DS_IP_Interface_Router_03.pdf).

**Comment by brutella** [comment]
Do you have other systems/software connected to your KNX IP gateway via tunnelling?

**Comment by thpeetz** [comment]
ETS6. Nothing else comes to mind.

For what it's worth, I have hkknx v2.8.1 running for a few days now and things still work without interruption. Much longer than I was able to run on 2.8.2. I'll switch off the nightly reboot of my Raspberry Pi and see if it really runs uninterrupted or if I was just lucky for a few days.

**Comment by brutella** [comment]
Are you able to check, if the connection issue still persists in any of the 3.0.0 beta version?

**Comment by thpeetz** [comment]
I've been running v3.0.0-b6 for two days now, so far without issues. I'll monitor this for a bit and report back in a few days.

**Comment by thpeetz** [comment]
After a few more days it's definitely an improvement. I didn't get the error described in the OP so far.

I noticed that a script that runs every night has twice so far returned a `group read: timeout` error when checking if a certain light is on. I never had that happen with 2.x. This timeout doesn't cause the entire system to misbehave though, all other functions remain available.

Feel free to close this issue as I think the original problem no longer persists.
