### ISSUE TITLE
Feature request, possibility to control AC unit

### ISSUE THREAD

**Issue by charlez79** [brutella/hkknx-public#329]
Hi, 
Would it be possible to add some additional properties in the thermostat so that AC unit can be controlled?

ON/OFF (1bit)
Fan speed => (percentage) modes: Auto, low, min, mid,high,max
quite mode  (1bit)
horizontal flaps (1bit)
vertical flaps (1bit)
mode (8bit) (DPT 5.010)  modes to configure: automatic, heat, dry, fan, cool

thx

**Comment by brutella** [comment]
At the moment it doesn't make sense to support AC units in hkknx because HomeKit doesn't support most of your requested features. 

For example HomeKit doesn't support the different modes (automatic, heat, dry, fan, cool) nor does it show a proper UI for a quiet mode, horizontal and vertical flaps.
