### ISSUE TITLE
Anzeige negativer Temperaturwerte

### ISSUE THREAD

**Issue by feanmg** [brutella/hkknx-public#33]
Mir ist aufgefallen, dass in meiner Home-App negative Temperaturen (z.B. Aussentemperatur) immer als 0,0 Grad angezeigt werden.
Temperaturen > 0 Grad werden richtig dargestellt.

Die Temperatur wird als DPT9 an den Bus geschickt. Der Datentyp in hkknx ist ebenfalls als DPST-9-1 eingestellt.

**Comment by brutella** [comment]
Du hast Recht. Temperaturen haben bei HomeKit standardmäßig eine Wertebereich von [0...100](https://github.com/brutella/hc/blob/master/characteristic/current_temperature.go).

Das Problem werde ich in der nächsten Version beheben.

**Comment by brutella** [comment]
Sollte jetzt im aktuellen Build von Version 0.0.17 behoben sein.

**Comment by feanmg** [comment]
Vielen Dank!
Mangels kalter Nächte konnte ich die Korrektur nur durch manuelles Senden eines neg. Wertes auf den Bus verifizieren. Aber das funktioniert jetzt wie erwartet!

**Comment by feanmg** [comment]
Hallo, heute morgen hatte es doch nochmal Minus-Temperaturen.

Dabei ist mir aufgefallen, dass Home auf 0.5 Grad auf- oder abrundet:
-3.3 --> -3.5
-2.2 --> -2.0
(vermutlich wird das bei Plus-Temperaturen auch passieren)

Wäre es möglich, dies auf eine Rundung von 0.1 Grad zu konfigurieren?
-2.25 --> -2.3

Viel Grüße!

**Comment by brutella** [comment]
Das kann man nicht konfigurieren, da die Anzeige des Wertes in der Home App immer gerundet wird.

**Comment by feanmg** [comment]
Vor der Anpassung, dass auch Minus-Temperaturen richtig angezeigt werden, war die Genauigkeit doch bei 0.1 Grad, oder?
....oder habe ich mich die ganze Zeit verschaut?

Eine Genauigkeit von 0.5 Grad halte ich bei Zimmertemperaturen für zu grob.

Wäre es denkbar, dies den Nutzer in deiner Bridge konfigurierbar anzubieten?

Beispiel:
Option A: Temperaturbereich (-xx.x ... +xx.x): Gerundet auf 0.5 Grad
Option B: Temperaturbereich (0.0 ... +xx.x): Gerundet auf 0.1 Grad

(ggf. Option C: autom. Umschaltung zwischen beiden Optionen wenn Positiv- oder Negativ-Temperatur vorherrscht.)

**Comment by brutella** [comment]
Nochmal. Die Home App zeigt den Wert gerundet an. Der eigentliche Wert wird natürlich nicht gerundet.

**Comment by feanmg** [comment]
Schon klar.

Aber: Ursprünglich war der Wertebereich bei HomeKit (0.0 ... +100.0) mit einer angezeigten Genauigkeit von 0.1K.

Weil ich mir negative Werte gewünscht habe, hast du den angezeigten Wertebereich umkonfiguriert auf (-xx.x ... +xx.x) mit der Konsequenz, dass die angezeigte Genauigkeit nur noch 0.5K beträgt.

Um allen Anforderungen gerecht zu werden, war meine neue Anregung, diesen Wertebereich konfigurierbar zu gestalten.
