### ISSUE TITLE
Raspberry startet nicht

### ISSUE THREAD

**Issue by nikgo2410** [brutella/hkknx-public#336]
Hallo, 
ich habe laut Anleitung das Image geladen (2.8.2) und es mit Raspberry PI Imager auf die SD-Karte kopiert (16GB).
Leider startet aber das Raspberry nicht, der Imager meldet auch keine Fehler.
Ich hoffe es kann mir jemand helfen.

**Comment by nikgo2410** [comment]
Danke für den Hinweis, habe es mit dem Image unter dem Link und mit der 2.6 versuche via Imager, beides hat nicht funktioniert. Also der Imager meldet, dass alles funktioniert hat. Raspberry startet aber nicht :(

**Comment by brutella** [comment]
Ich arbeite gerade an einer neuer Version des Raspberry Pi Images für die Version 3.0. Diese sollte in den nächsten Tagen verfügbar sein und damit sollte es auf jeden Fall klappen.

**Comment by nikgo2410** [comment]
Das wäre super. Gibt es irgendwo eine Anleitung wie man alles über einen MacMini laufen lassen kann? So einen hätte ich hier auch noch rumfliegen. 

Danke für die Mühe 👍

**Comment by brutella** [comment]
Auf einem Mac musst du die Kommandozeile verwenden.

**Comment by nikgo2410** [comment]
Ich glaube dafür bin ich zu sehr Laie 😍

**Comment by brutella** [comment]
Bitte das Raspberry Pi Image von [Version 3.0.0-b9.3](https://github.com/brutella/hkknx-public/releases/tag/3.0.0-b9.3) ausprobieren. Ist die Datei `hkknx-3.0.0-b9.3_rpi.tar.gz`. Damit sollte es klappen.

PS: Dieses Image basiert nicht mehr auf dem Rasbperry Pi OS. Du musst den Raspberry Pi beim ersten Mal per Ethernet mit dem Netzwerk verbinden. Danach kannst du unter Einstellungen → Mehr → WLAN Einstellungen die WLAN Daten eingeben.
