### ISSUE TITLE
Staus of inactive item is getting monitored

### ISSUE THREAD

**Issue by Graefer** [brutella/hkknx-public#338]
Hi, 
I like the monitoring feature of version 3.0.0. However, I have contact sensor which is turned inactive in hkknx. Nevertheless the monitor displays this sensor. I do not think this makes sense. 
Regards,
Graefe

**Comment by brutella** [comment]
Good catch. Will be fixed in the next update.

**Comment by brutella** [comment]
Should be fixed in [3.1.0-b2](https://github.com/brutella/hkknx-public/releases/tag/3.1.0-b2)
