### ISSUE TITLE
Home-App-Szenen - Gleichzeitigkeit

### ISSUE THREAD

**Issue by feanmg** [brutella/hkknx-public#34]
Ich habe in der Home-App eine Szene erstellt, z.B.: "Zimmer OG Licht An".
Diese soll bewirken dass in fünf Zimmern im OG die Zimmerleuchten "Eingeschalten" werden. Jede der fünf Leuchten ist als einzelne Lampe in hkknx konfiguriert.

Möchte ich die Szene aufrufen, erwarte ich, dass alle Leuchten gleichzeitig eingeschaltet werden.
Leider funktioniert das nicht - es scheint, als wäre die Gleichzeitigkeit ein Problem und nicht alle Telegramme kommen auf dem KNX-Bus an.
Hierbei ist es unterschiedlich, welche Leuchten reagieren. In der Home-App machen die Kacheln der Lampen den Eindruck, als wären sie eingeschaltet. Um aus diesen falschen Status rauszukommen, muss ich die nicht-reagierten-Leuchten einmal aus- und dann wieder einschalten.

Kann das jemand reproduzieren?

**Comment by brutella** [comment]
Welche Version von hkknx verwendest du?

Dieses Problem bestand in einer alten Version – sollte aber in der aktuellsten Version nicht mehr der Fall sein.

**Comment by brutella** [comment]
Wegen Inaktivität geschlossen

**Comment by feanmg** [comment]
(Ich bin noch nicht zum testen gekommen - werde das Ergebnis aber hier noch kurz dokumentieren; meine Version war 0.0.16)

**Comment by feanmg** [comment]
Kurz ein Feedback: Ich bin mir tatsächlich nicht ganz sicher und kann nicht ausschließen, dass das Problem auf meiner Seite liegt - evtl. passiert bei mir da auf dem Bus zu viel (es werden nicht nur Leuchten geschalten, sondern auch Rolläden und andere Automatismen).
Ich denke, es passt schon, dass der Vorgang geschlossen ist.
