### ISSUE TITLE
Error while toggling switch in WebUI

### ISSUE THREAD

**Issue by v0lli** [brutella/hkknx-public#347]
<img width="280" alt="Screenshot 2024-10-28 at 09 14 36" src="https://github.com/user-attachments/assets/8abd2fb3-73be-4919-b230-095e33961fb9">

When toggling an on/off button in the WebUI, I get an Error: schema: invalid path "xxxx-xxxx-xxxx" see screenshot 
Siri-commands work and the buttons within the Apple Home App also work. 

version is: v3.1.0-b8

Regards

**Comment by brutella** [comment]
Thanks for the report. Will be fixed in the next beta update.
