### ISSUE TITLE
Geräte im Cofigurator einem anderen Raum zuordnen

### ISSUE THREAD

**Issue by dengler5000** [brutella/hkknx-public#350]
Hallo,
ich habe festgestellt, dass ich einen Temperaturregler einem falschen Raum zugeordnet habe. Wie kann ich das ändern, sodass es auf meinem iPhone wieder passt. Über die Configurator App kann ich lediglich den Namen ändern aber nicht die Zugehörigkeit. Bei Apple Home, kann ich es nicht dahin verschieben, wo ich es will und auf der 3.0 Weboberfläche geht es, lässt sich aber nicht aufs Handy bzw. Configurator rückspiegeln.

**Comment by regetskcob** [comment]
Ich habe da tatsächlich auch geregelt meine Schwierigkeiten, Apple Home, Home+ und Configurator immer im richtigen Moment anzusteuern. 

Aktuell machen ich einen Großteil über Home+, mit scheint auch tatsächlich, dass Configurator einfach eine Teilmenge vom Home+ Funktionaumfang ist...

**Comment by brutella** [comment]
Eine Synchronisierung zwischen hkknx und HomeKit wird mit der Konfigurator-App gemacht. Wie das im Detail geht, ist im Online Handbuch erklärt.
https://hochgatterer.me/de/hkknx/docs/accessories/#konfigurator-app

> Bei Apple Home, kann ich es nicht dahin verschieben, wo ich es will

Würd mich interessieren, warum du es in der Apple Home-App nicht verschieben kannst?

**Comment by dengler5000** [comment]
Beim Synchronisieren kommt immer dieser Fehler:

![image](https://github.com/user-attachments/assets/779bd620-e3ab-4f18-a8e0-c4abed91d1c2)

Das ist seit 3.0.0 so. Habe auch mal alles zurückgesetzt, Bridge gelöscht und neu hinzugefügt. Hilft leider nichts.

> Würd mich interessieren, warum du es in der Apple Home-App nicht verschieben kannst?<

Ich kann das Icon verschieben, aber springt immer wieder an seinen Ursprung zurück.

Auf meiner Weboberfläche passt alles. Das hätte ich einfach gerne so auf dem iPhone, dann wäre ich glücklich :)

**Comment by dengler5000** [comment]
Nach einigem hin und her hat die Synchronisierung nun geklappt, daher würde ich erstmal das Thema schließen

**Comment by regetskcob** [comment]
@brutella ich kann nicht sagen, ob seit einer bestimmten Version, doch ich hatte heute ähnliche Probleme. 

Konkret hatte ich im Konfigurator einige Räume umstrukturiert und mit jedem Synchronisierungsversuch wollte Konfigurator die Räume wieder umbenennen, obwohl diese in Home nicht existierten.

![HKKNX1](https://github.com/user-attachments/assets/1db4d47a-bbde-4f70-a7df-9b70f61d2211)
![HKKNX2](https://github.com/user-attachments/assets/65efe8b0-65c6-4a51-92ca-30f7323f226b)
![HKKNX3](https://github.com/user-attachments/assets/fe7b6b4f-05df-4ba2-9d43-029d83aa10b2)
![IMG_0146](https://github.com/user-attachments/assets/c7be7a85-05e7-442a-83a4-7b3b155a7a2a)

Danach ging‘s nicht weiter, auch nach 10min nicht :D App Neustart half zwar, problem war aber reproduzierbar. Lösen konnte ich es vorerst, indem ich im Konfigurator einen leeren Raum gelöscht hab, der Sync hat danach geklappt und alles war wieder „sauber“.
