### ISSUE TITLE
Missing possibility to send notifications to specific registered devices instand of all

### ISSUE THREAD

**Issue by regetskcob** [brutella/hkknx-public#352]
I think we all know it. You Experiment with KNX Bus of something Else and you wife get‘s notifications again and again… I want to Set specific devices to receive notifications, when e.g. my garage-door get‘s opened.

**Comment by brutella** [comment]
When you configure notifications for an accessory in the accessory settings, you can define which devices should receive the notifications.

When you send notifications via a script, you can append the device name(s) as last argument in the function call of [SendNotification](https://hochgatterer.me/hkknx/scripts/pkgs/hkknx/#SendNotification).

The following example sends the notification to the device containing the text "My iPhone".
```go
hkknx.SendNotification("Title", "This is the message", "My iPhone") 
```

Another example is available in the online help.
https://hochgatterer.me/de/hkknx/scripts/examples/restart-notification/
