### ISSUE TITLE
Missleading german Titels for Window-/Door-Sensor

### ISSUE THREAD

**Issue by regetskcob** [brutella/hkknx-public#353]
The "Ausgelöst" and "Bereit" Titels die Not Reality meet a lot of acceptance within this house. :D In german, "Geöffnet" and "Geschlossen" Sound be the much better fit.

![image](https://github.com/user-attachments/assets/96fb51da-d47c-4266-8b73-b8df21db0085)

**Comment by brutella** [comment]
On the latest beta, you will get the correct labels, if you set the display type of the contact sensor to be a door or a window.
