### ISSUE TITLE
Add heating and cooling property to thermostat

### ISSUE THREAD

**Issue by brutella** [brutella/hkknx-public#36]

**Comment by kreuzundkwer** [comment]
Z.B. die MDT Aktoren arbeiten mit einer Sollwertverschiebung statt mit absoluten Werten um den Soll Wert zu setzen. 
Es werden also keine 22° gesendet sondern die Differenz (in K) zwischen dem Sollwert des aktuellen Programms (20°) und dem gewünschten Wert (+2K). 

Spannend wäre auch, den Stellwert des Ventils (DPT 5.001) in % anzuzeigen.

**Comment by willgf** [comment]
nein, die arbeiten sowohl mit sollwertverschiebung als auch mit absoluten werten. das hängt davon ab, wie du es parametrierst.

**Comment by snoerenberg** [comment]
Es kommt auf die Version an. Die 03 können auch absolut Werte, die 02 von MDT nicht.
