### ISSUE TITLE
Jalousien Auf/Ab

### ISSUE THREAD

**Issue by macindy** [brutella/hkknx-public#38]
Im Moment wird entweder 0% oder 100% für Auf und Zu übergeben.

Es wäre gut, wenn es für Auf/Zu eine extra Configoption gäbe bei der eine 0/1 an den Jalousieaktor gesendet wird. Sprich wenn eine GA bei Auf/Zu-Configoption in der Bridge eingetragen ist, bei Tastendruck Auf/Zu in iOS nicht die Höhe in % übergeben, sondern eine 1/0 an die Auf/Zu GA gesendet wird.

**Comment by brutella** [comment]
Versuch mal eine Jalousiensteuerung mittels eines Garagentores zu testen. Dort gibt es die Option *Öffnen/Schließen* um eine Tor (in deinem Fall die Jalousie) zu öffnen/schließen.

Funktioniert das über diesen Weg?

**Comment by macindy** [comment]
Jup das geht.
<img width="683" alt="Bildschirmfoto 2020-04-22 um 21 20 30" src="https://user-images.githubusercontent.com/6375316/80024946-1fd7d280-84e0-11ea-975e-56997a1ef25e.png">

**Comment by brutella** [comment]
Hast du für deine Jalousien auch Gruppenadressen zum Signalisieren, wenn die Endposition (Offen, Geschloßen) erreicht wurde?

**Comment by macindy** [comment]
Das geht nur über die Rückmeldung Höhe in %

**Comment by macindy** [comment]
https://www.theben.de/ocsmedia/optimized/full/o4261v42%20JMG%204%20T%20KNX%20-%20Handbuch.PDF

**Comment by brutella** [comment]
Damit ich das richtig verstehe. Du bekommst eine Rückmeldung über die Ist-Position der Jalousie, kannst aber die Soll-Position nicht festlegen. Das geht nur komplett öffnen oder schließen?

**Comment by macindy** [comment]
Doch ich kann eine Soll Position angeben. Das Problem ist dass der Aktor bei 0% Höhe die Jalousie wieder zurückfährt - lt. Auskunft des Herstellers wegen der Lamellenposition. Die Taster an der Wand schicken die Jalousie per 1 Bit auf/zu. Damit geht es - also ohne zurückfahren. Also fände ich es gut, wenn es - wie bei den Tastern - für auf/zu die zusätzliche Möglichkeit auf/zu per 1Bit auszulösen gäbe.  Wenn man über den Schieberegler gehen soll natürlich über %.

**Comment by brutella** [comment]
> Wenn man über den Schieberegler gehen soll natürlich über %.

Die Brücke kann leider nicht unterscheiden ob die Position über den Schieberegler, einen Tap auf die Kachel, oder über Siri festgelegt wird.
 Wenn dann müsste man alles über die Öffnen/Schließen Gruppenadresse steuern. Ob damit eine Anfahrt an einen prozentuellen Soll-Wert zuverlässig funktioniert ist schwierig zusagen.

**Comment by macindy** [comment]
Wenn es keinen Unterschied zwischen Tap auf die Kachel und Schieberegler gibt, macht es keinen Sinn.

**Comment by brutella** [comment]
Nein, gibt es leider nicht. 

Bei einem Tap wird die Soll-Position auf 0% oder 100% gestellt. Selbiges geht auch auch über den Schieberegler.

**Comment by macindy** [comment]
Bitte mal einen Blick auf das Video 00:23 werfen. Long Move Up/Down. Scheint schon Bedarf zu sein. If 0% then 0 elseif 100% = 1. 

Https://Vimeo.com/304124771

**Comment by brutella** [comment]
Wird *Long Move Up/Down* womöglich dafür verwendet, um die Jalousie ein Stück nach oben oder unten zu fahren? Ich glaube das ist bei KNX so eine Standardfunktion.

**Comment by macindy** [comment]
Ich kenne Schritt (=kurze Bewegungen) und Fahren (=lange Bewegung). Bei meinem Wandtaster ist kurzer Tastendruck Schritt und langer Tastendruck fahren.  Dafür gibt es im Aktor auch die entsprechenden KOs. Zusätzlich gibt es im Aktor noch Ist% und Soll% Höhe und Ist% und Soll% Lamelle.

**Comment by brutella** [comment]
Da es in HomeKit so etwas wie kurze oder lange Fahrt nicht gibt, wird es zurzeit auch nicht verwendet.

**Comment by fxpde** [comment]
Wie wäre es wenn man bei der Soll-Position 0% bzw. 100% aus HomeKit den Auf bzw. Ab-Befehl nutzt und für alles dazwischen die GA für die absolute Soll Position nutzt?

**Comment by brutella** [comment]
Was wäre damit gewonnen?

**Comment by OliverS79** [comment]
Mir würde das helfen, da mein (alter) Rollladenaktor nur so angesteuert werden kann. Eine Ansteuerung über Prozentwerte ist nicht möglich.

**Comment by fxpde** [comment]
Einmal das. Und man würde damit folgendes Problem lösen. 
Ausgangsposition: die Raffstore sind unten. Behang bei 100% und Lamellen bei 100% geschlossen. 
Aktion: ich tippe auf den Raffstore in HomeKit und erwarte, dass er hoch fährt. 
Problem: der Behang fährt hoch auf 0%. Wenn er oben angekommen ist, fährt er aber wieder ein kleines Stück runter um die Lamellen auf 100% zu haben. Das möchte ich in dem Moment aber gar nicht. 
Gleiches Spiel auch andersrum. Da ist es sogar problematischer. Wenn ich von 0% Behang und 0% Lamellen drauftippe fährt er auf 100% Behang aber stellt dann die Lamellen auf offen mit 0%. Ich würde aber hier erwarten, dass sie schließen. 
Aktuell ist die Steuerung der Lamellen eh recht schlecht umgesetzt in HomeKit. Hatte bereits überlegt die Lamellen als separates Objekt stattdessen anzulegen.

**Comment by frankschneider** [comment]
Ich habe tatsächlich auch nur ältere ABB Aktoren verbaut, die bei Rolläden nur ein 1Bit Objekt für "Auf/Ab" und ein weiteren 1Bit Objekt für "Stop" können. Auf Position fahren kann der leider noch nicht. 

Kanal A-D jeweils Rolläden:
![grafik](https://user-images.githubusercontent.com/11604126/84173439-94a9a080-aa7d-11ea-8f74-caeec0462092.png)

Bei Jallousien habe ich nur ein 1Bit Objekt für Auf/Ab und 1 weiteres 1Bit Objekt für Lammelenverstellung Auf/Ab und Stop.

Kanal A = Rolladen, Kanal B-D Jallousien
![grafik](https://user-images.githubusercontent.com/11604126/84174288-b48d9400-aa7e-11ea-991e-3ad65caf23fd.png)

Somit kann ich die Rolläden heute über HomeKit noch nicht wie gewohnt steueren bzw. vorallem nicht stoppen.

**Comment by brutella** [comment]
> Mir würde das helfen, da mein (alter) Rollladenaktor nur so angesteuert werden kann. Eine Ansteuerung über Prozentwerte ist nicht möglich.

Da sehe ich das Problem, da bei HomeKit die Rollläden auf bestimmte Positionen gefahren werden können. Die UI lässt also das Öffnen der Rollladen auf zB 50% zu – wie soll sich da die Bridge verhalten, wenn das ja eigentlich nicht möglich ist?

> Aktuell ist die Steuerung der Lamellen eh recht schlecht umgesetzt in HomeKit

Da gebe ich dir Recht, aber wie sollte sich die Bridge in dem Falle verhalten? Wenn der Rolladen komplett geöffnet werden soll, sollen dann auch die Lamellen ganz geöffnet werden? Wie wird das bei anderen Visualisierungen gemacht?

> Somit kann ich die Rolläden heute über HomeKit noch nicht wie gewohnt steueren bzw. vorallem nicht stoppen.

Das sehe ich genauso Problematisch wie oben erwähnt. Bei HomeKit wird halt vorausgesetzt, dass Rollläden an bestimmte Positionen gefahren werden können. Ich finde es gibt da keinen guten Workaround, wenn das der Rollladen einfach nicht hergibt.

**Comment by OliverS79** [comment]
Kann ich nachvollziehen...

Eine - aber wahrscheinlich sehr komplexe - Lösung wäre in der Bridge die Fahrzeit für eine komplette Fahrt zu hinterlegen und den Prozentwert, dann in Zeit umrechnen und nach Ablauf der Zeit ein Stop Telegram senden. 

Aber wie gesagt sehr komplex, da man ja auch auf den Bus hören müsste um mitzubekommen, wenn außerhalb der Bridge ein Fahrbefehl kommt.

Daher wahrscheinlich nicht gerade eine einfache Lösung.

**Comment by fxpde** [comment]
> Eine - aber wahrscheinlich sehr komplexe - Lösung wäre in der Bridge die Fahrzeit für eine komplette Fahrt zu hinterlegen und den Prozentwert, dann in Zeit umrechnen und nach Ablauf der Zeit ein Stop Telegram senden.

Dies hatte ich so ähnlich in einem anderen Forum schonmal gelesen und hatte auch eher Bedenken gesehen da das Timing echt sehr genau sein muss.

> Da gebe ich dir Recht, aber wie sollte sich die Bridge in dem Falle verhalten? Wenn der Rolladen komplett geöffnet werden soll, sollen dann auch die Lamellen ganz geöffnet werden? Wie wird das bei anderen Visualisierungen gemacht?

Ja genau wie du es beschreibst. Wenn ich auf öffnen klicke soll Behang und Lamelle geöffnet werden. Wenn ich auf schließen klicke sollen Behang und Lamelle geschlossen werden. Die müsste sich doch als Option auch abbilden lassen und dann in der Bridge entsprechend entweder Auf/Ab verwenden oder die absolute Position wie oben beschrieben. Fand ich wirklich super

**Comment by ize86** [comment]
Ich steh gerade vor dem gleichen Problem, gibts hierfür irgendwelche Neuigkeiten?
