### ISSUE TITLE
HomeKit light button to trigger KNX-scenes

### ISSUE THREAD

**Issue by petnau** [brutella/hkknx-public#44]
In quite a few installations KNX-scenes are used to set "light scenarios" especially when you want to control multiple different light sources, that are preconfigured with specific light levels, with one physical or virtual light switch/button. Is this something that would be possible to implement into hkknx in the future?

**Comment by brutella** [comment]
Do I understand that correctly that you would like to have to a switch in HomeKit, which sends a scene id to KNX when it is turned on/off?

**Comment by BugRoger** [comment]
Yes. It would also be cool if the switch could send different scene IDs for ON and OFF.

**Comment by petnau** [comment]
For example, I would like to be able to tell Siri, “Hey Siri please turn on the lights”, when I come home and that would trigger a specific KNX-scene which has been predefined with the correct light sources and light levels for that action.

**Comment by rw71** [comment]
Why don't you create this scene in Home App? It could do the same that you have defined in you KNX-scene.

**Comment by petnau** [comment]
Hi,

I have some 20-25 KNX-scenes that are used around the buildning. Majority are different light scenarios that are triggered with hard-buttons around the house. The KNX-scenes are quite regularly adjusted depending on different lighting situations. We use the ”Button long press store current light values to KNX scene memory" function for easy adjustments of the scenarios, so basically anyone can adjust the scenarios. For me it would make a lot of sense to be able the re-use the same KNX-scenes and also be able to call them with HomeKit, instead of creating duplicates in HomeKit.

/Petri

**Comment by brutella** [comment]
Controlling KNX scenes via an accessory in HomeKit doesn't feel right to me, because HomeKit also has the concept of scenes. Meaning that KNX scenes should appear as HomeKit scenes to the user. Because HomeKit scenes can only be created by an iOS app, we could use the [Configurator app](https://hochgatterer.me/de/hkknx/docs/accessories/#home-configurator-app) to do that.

**Comment by chef76** [comment]
In my opinion a "Bridge" can be used in both directions. On the KNX Side Scenes are from the beginning an important feature. Only because on the HomeKit Side, there's another way to create scenes, the present KNX scenes shouldn't be excluded from use in the bridge.

**Comment by brutella** [comment]
The only problem is that the HomeKit Accessory Protocol (that's the communication protocol between the bridge and HomeKit) doesn't include information about scenes. HomeKit scenes can only be created by an iOS app.

**Comment by chef76** [comment]
I'm not sure we're talking about the same thing. To trigger an existing KNX scene the bridge only has to send a scene-ID on the bus. So there only has to be a way to tell a button which ID to send on push and release. Whether or not, that's possible I don't know.

**Comment by brutella** [comment]
Yeah, but this means that you have a button for every KNX scene.

**Comment by chef76** [comment]
Exactly!

**Comment by feanmg** [comment]
(Hallo Brutella, nur mein kurzes Feedback: deine Idee mit dem Anlegen von "Szenen-Buttons" in der Home-Configurator-App wäre ein prima Workaround, um Szenen oder andere Aktionen anzutriggern. Über eine solche Umsetzung würde ich mich freuen.)

**Comment by feanmg** [comment]
(Hallo Brutella, nur mein kurzes Feedback: deine Idee mit dem Anlegen von "Szenen-Buttons" in der Home-Configurator-App wäre ein prima Workaround, um Szenen oder andere Aktionen anzutriggern. Über eine solche Umsetzung würde ich mich freuen.)

**Comment by feanmg** [comment]
(Hallo Brutella, nur mein kurzes Feedback: deine Idee mit dem Anlegen von "Szenen-Buttons" in der Home-Configurator-App wäre ein prima Workaround, um Szenen oder andere Aktionen anzutriggern. Über eine solche Umsetzung würde ich mich freuen.)

**Comment by feanmg** [comment]
(Hallo Brutella, nur mein kurzes Feedback: deine Idee mit dem Anlegen von "Szenen-Buttons" in der Home-Configurator-App wäre ein prima Workaround, um Szenen oder andere Aktionen anzutriggern. Über eine solche Umsetzung würde ich mich freuen.)

**Comment by Superwuzy** [comment]
Ich schließe mich an. Ich nutze in meinem Haus auch diverse KNX-Szenen. Ich hätte einen großen Bedarf, mittels eines HomeKit-Schalters (oder eines Objekt, was besser passt, quasi ein Push-Button) eine KNX-Szenen-ID triggern zu können.

**Comment by Superwuzy** [comment]
@brutella Ohne die Möglichkeit, von HomeKit aus KNX-Szenen triggern bzw. alternativ feste numerische Werte an KNX-GAs senden zu können, ist in meinen Augen die hkknx-Unterstützung noch lückenhaft. KNX-Szenen gehören von Anfang an zur DNA von KNX. Sie über HomeKit noch nicht auslösen zu können, empfinde ich wirklich als großes Defizit.

**Comment by brutella** [comment]
@Superwuzy HomeKit hat ein eigenes Konzept hinsichtlich Szenen und die Vermischung von HomeKit Szenen und KNX Szenen ist nicht so ohne weiteres möglich. Besonders da alles was in HKKNX konfiguriert wird, mit der Standard Apple Home App funktionieren soll.

Ich habe mir aber dahingehend schon etwas Gedanken gemacht.

**Comment by Superwuzy** [comment]
@brutella Mir ist bekannt, dass HomeKit eine eigene Szenenunterstützung hat und dass man Konzepte nicht vermischen soll. Daher hatte ich geschrieben, dass es reichen würde, den Nutzern eine Art PushButton-Lösung anzubieten (es gibt ja auch HomeKit-fähige PushButtons), deren Typ gar nicht den Namen "Szene" tragen muss. Es würde hier völlig reichen, Objekte vom Typ "PushButton" anzulegen. In hkknx definiert der Nutzer dann die Gruppenadresse und numerischen Wert einzugeben, der für die GA gesetzt wird. Bei KNX-Szenennummern werden aufgrund des DPT-Typs bekanntlich um den numerischen Wert 1 niedriger auf den KNX-Bus gesendet. So kann ein hkknx-User beispielsweise für eine Szene mit der Nummer "6" den Wert "5" hinterlegen - fertig. Man benötigt für diesen Button weder eine Rückmeldung noch einen Initialisierungswert. Wenn Du das so integrieren könntest, wären Dir schätzungsweise alle hkknx-User dankbar, die viele KNX-Szenen im Haus einsetzen. Und das würde in meinen Augen auch nicht dem HomeKit-Konzept entgegenstehen, weil PushButtons offiziell von HomeKit unterstützt werden. Könntest Du eine derartige Lösung zur Verfügung stellen? Danke im voraus!

**Comment by brutella** [comment]
> Man benötigt für diesen Button weder eine Rückmeldung noch einen Initialisierungswert.

Genau so etwas gibt es eben in HomeKit nicht. Das heißt nicht, dass es nicht möglich ist so etwas in HomeKit abzubilden, aber die Apple Home App wird das nicht richtig angezeigt bekommen.

> Und das würde in meinen Augen auch nicht dem HomeKit-Konzept entgegenstehen, weil PushButtons offiziell von HomeKit unterstützt werden.

Push-Buttons werden unterstützt, aber in die andere Richtung. Ein Push-Button in HomeKit kann nicht über die Home App gedrückt werden. Es wird die Art des Drucks (Kurz Gedrückt, Lange Gedrückt, Doppelt Gedrückt) an HomeKit gesendet, damit auf diese Ereignisse reagiert werde kann.

**Comment by Superwuzy** [comment]
@brutella Danke für die Erläuterung. Jetzt habe ich es verstanden. In diesem Fall würde es in meinen Augen reichen, wenn man einem gewöhnlichen Schalter die Möglichkeit geben könnte, optional einen festen KNX-Wert setzen zu können, der immer auf den KNX-Bus gesendet wird, ganz egal, ob der Schalter ein- oder ausgeschaltet wird. In der HomeKit-App würde dann der Schalter quasi immer "Ein" anzeigen, ganz egal, wie oft man drückt. Bei jedem Druck würde der feste Wert gesendet.

**Comment by brutella** [comment]
Ja, das wäre eine Möglichkeit. Ist aber meiner Meinung nach nicht optimal.

Optimal wäre es, wenn man vorhandene Szenen auslesen (aus der ETS Projektdatei?) und als HomeKit Szenen anlegen könnte.

**Comment by Superwuzy** [comment]
Das wäre natürlich eine sehr elegante Lösung, die bei Dir den größten Implementierungsaufwand nach sich zöge. Die Schwierigkeit, die ich hier jedoch sehe, ist, dass die Ausprägungen einer Szene letztlich in der Applikation des jeweiligen Tasters (bei mir GIRA Tastsensor 3 oder MDT Glassensor) festgelegt werden. Man könnte dann zwar wohl aus der Projektdatei herauslesen, welche Szenen-GAs generell genutzt werden, aber wahrscheinlich nicht so einfach, welche Ausprägungen denn für die jeweilige GA auch real benötigt werden. Ich nutze beispielsweise für einen Raum wie "Wohnen" eine Szenen-GA, die die Ausprägungen "Aus", "Allgemein", "Abend", "TV" und "Nacht" einnehmen kann. Einige dieser Ausprägungen triggere ich dabei über den Tastsensor, andere dabei über den Glassensor.

**Comment by Superwuzy** [comment]
In der Visualisierung (bei mir der GIRA HomeServer) sind die Szenen dann für einen Raum beispielsweise so abgebildet:
![E752BDBE-CA6F-4A20-9D1E-005462873C71_1_105_c](https://user-images.githubusercontent.com/17985563/101145099-982b7800-3619-11eb-907b-b22fab5e51c2.jpeg)

**Comment by chef76** [comment]
andere Hersteller scheinen mit Szenen nicht solche Probleme zu haben:

![image](https://user-images.githubusercontent.com/69462419/101175177-22d59c80-3645-11eb-8ea5-b7c1ebfeb2c7.png)

Zeigt übrigends die ETS aktuell als Werbung an.

**Comment by chef76** [comment]
... und im Prinzip hast Du schon einen Push-Button umgesetzt: Garagentor.
Der sendet auch immer 1 oder immer null, je nachdem wie er konfiguriert ist.

Ich habe weiter oben schon mal versucht klar zu machen, dass das die HKKNX Bridge wirklich nach vorne bringen könnte undich verstehe ehrlich gesagt nicht, was Du für Probleme damit hast. Das in meinen Augen sinnlose Motorschloss hast Du sofort umgesetzt.

**Comment by chef76** [comment]
Unterstützt auch Szenetasten: https://www.xxter.com/voice/?gclid=Cj0KCQiA2af-BRDzARIsAIVQUOcx5W7Nwo172_Iw7RnyStoBHETwfwMysMQlMaT_RPcFqFSjURn0VEMaAvrpEALw_wcB

**Comment by brutella** [comment]
> [...] ich verstehe ehrlich gesagt nicht, was Du für Probleme damit hast.

Warum sollte ich Probleme damit haben?

> Unterstützt auch Szenetasten: https://www.xxter.com/voice/?gclid=Cj0KCQiA2af-BRDzARIsAIVQUOcx5W7Nwo172_Iw7RnyStoBHETwfwMysMQlMaT_RPcFqFSjURn0VEMaAvrpEALw_wcB

Stellt sich nur die Fragen, wie das umgesetzt wurde. Vermutlich wird für jede Szene ein Schalter angelegt – was ich aber für keine gute Lösung finde. 

Ich bleibe dabei, dass ich keine halbe Lösungen integrieren möchten. Ich bin mir sicher, dass eine "richtige" Umsetzung möglich ist.

**Comment by chef76** [comment]
ich unterstütze hier in jeder erdenklichen Weise gerne, egal ob mit Ideen oder zum Testen.

Wieso ist ein Schalter für jede Szene eine "halbe Lösung" für Dich? 
Wie soll das denn sonst gehen?

Als erstes müsstest Du generell mal Taster einführen, bei denen man vorgeben kann, welcher Wert beim Auslösen gesendet wird (1 oder 0). Taster sind Standard in KNX. Wie löst Du ohne Taster z.B. sauber eine Treppenhausautomatik aus? Da darf nur eine 1 gesendet werden. Eine 0 soll der Taster nie senden. 

Wie gesagt, ich steuere gerne alles bei, was nötig ist, aber dass man mit Deiner Brücke keine Szenen auslösen kann, ist schon ein großer Nachteil. Und etwas garnicht umzusetzen, weil man auf eine "richtige" Umsetzungsidee wartet bringt das Produkt nicht voran. Man kann Sachen auch im Nachhinein noch verbessern, wenn man eine gute Idee hat.

**Comment by brutella** [comment]
> Wieso ist ein Schalter für jede Szene eine "halbe Lösung" für Dich?

Ganz einfach, in HomeKit kann man einen Taster ein- und ausschalten.
Was soll passieren, wenn der Taster ausgeschaltet wird?

> Wie soll das denn sonst gehen?

Optimal wäre es, wenn eine KNX Szene als Szenen in HomeKit auftaucht.

Wie das genau umgesetzt werden kann, muss ich mir noch ansehen. Da ich aber zurzeit an einem großen Update for Home+ arbeite, kann ich das gerade nicht tun. Ich warte also nicht auf eine bessere Lösung, sondern kann mir erst Gedanken darüber machen, wenn ich Zeit dazu habe. 😉

**Comment by chef76** [comment]
einen Taster kann man nicht ausschalten, ein Taster schaltet sich "von selbst" aus. Oder ist das in Homekit nicht so?
Wenn man einen Taster ausschalten könnte wäre es kein Taster, sondern ein Schalter.

**Comment by chef76** [comment]
... und ich kann natürlich warten, bis Du Zeit dafür hast! :-)

**Comment by brutella** [comment]
> Wenn man einen Taster ausschalten könnte wäre es kein Taster, sondern ein Schalter.

Ok, das sag ich es so. Einen Taster, der von HomeKit aus (zB der Apple Home-App) gedrückt werden kann, gibt es nicht.

**Comment by willgf** [comment]
Hallo zusammen, 

für mich ist das auch ein großes Defizit und ich sehe es nicht als "halbe Lösung" wenn dafür ein Schalter in HK angelegt wird, der auf eine GA eine Szenennr schickt.

Thinka hat es gelöst - was für mich eine durchaus elegante Lösung zu dem Problem ist:

-In HK ist die KNX Szene als Schalter abgebildet
-Diesen Schalter kann man 2-fach parametrieren: also zb. Szene "1" auf eine bestimmte GA wenn der "Schalter" eingeschaltet wird, und Szene "2" auf eine GA wenn der Schalter "aus" ist
-Wenn man nur eine KNX Szene parametriert, wird der HK-Schalter nach einigen Sekunden von der Brücke wieder in den ausgangszustand gesetzt

**Comment by chef76** [comment]
> > Wenn man einen Taster ausschalten könnte wäre es kein Taster, sondern ein Schalter.
> 
> Ok, das sag ich es so. Einen Taster, der von HomeKit aus (zB der Apple Home-App) gedrückt werden kann, gibt es nicht.

Und wie hast Du das dann mit dem Garagentor gemacht? Das ist ein Taster im Sinne meiner Definition. Einmal Drücken wird eine 1 gesendet. Nochmal drücken wird wieder eine 1 gesendet. Der bleibt auch nicht gedrückt, sondern bekommt seinen Status über eine Rückmelde GA. Genauso sollte es sein, nur dass man nicht nur einstellen kann, dass 1-1-1 oder 1-0 gesendet wird, sondern immer eine beliebige Szenen-ID.

**Comment by chef76** [comment]
> Hallo zusammen,
> 
> für mich ist das auch ein großes Defizit und ich sehe es nicht als "halbe Lösung" wenn dafür ein Schalter in HK angelegt wird, der auf eine GA eine Szenennr schickt.
> 
> Thinka hat es gelöst - was für mich eine durchaus elegante Lösung zu dem Problem ist:
> 
> -In HK ist die KNX Szene als Schalter abgebildet
> -Diesen Schalter kann man 2-fach parametrieren: also zb. Szene "1" auf eine bestimmte GA wenn der "Schalter" eingeschaltet wird, und Szene "2" auf eine GA wenn der Schalter "aus" ist
> -Wenn man nur eine KNX Szene parametriert, wird der HK-Schalter nach einigen Sekunden von der Brücke wieder in den ausgangszustand gesetzt (quasi ein "stateless" Schalter)
> 
> -Rückmeldung etc. gibt es nicht und braucht es auch nicht - gibt es in KNX ja auch nicht

... stimmt, die Rückmeldung bräuchte es nicht. Zwei Szene-IDs für Ein- und Ausschalten würden es tun oder eben halt nur eine beim Einschalten und automatisches Rücksetzen in den Zustand aus ohne dass was gesendet wird.

**Comment by Superwuzy** [comment]
> > Hallo zusammen,
> > für mich ist das auch ein großes Defizit und ich sehe es nicht als "halbe Lösung" wenn dafür ein Schalter in HK angelegt wird, der auf eine GA eine Szenennr schickt.
> > Thinka hat es gelöst - was für mich eine durchaus elegante Lösung zu dem Problem ist:
> > -In HK ist die KNX Szene als Schalter abgebildet
> > -Diesen Schalter kann man 2-fach parametrieren: also zb. Szene "1" auf eine bestimmte GA wenn der "Schalter" eingeschaltet wird, und Szene "2" auf eine GA wenn der Schalter "aus" ist
> > -Wenn man nur eine KNX Szene parametriert, wird der HK-Schalter nach einigen Sekunden von der Brücke wieder in den ausgangszustand gesetzt (quasi ein "stateless" Schalter)
> > -Rückmeldung etc. gibt es nicht und braucht es auch nicht - gibt es in KNX ja auch nicht
> 
> ... stimmt, die Rückmeldung bräuchte es nicht. Zwei Szene-IDs für Ein- und Ausschalten würden es tun oder eben halt nur eine beim Einschalten und automatisches Rücksetzen in den Zustand aus ohne dass was gesendet wird.

Ich habe beispielsweise für den Raum "Wohnen" 7 Szenen (die "Aus"-Szene habe ich mitgerechnet). Ich würde mir daraus 7 Schalter basteln und jeden der Schalter für den Ein-Zustand mit einer der 7 Szene-IDs belegen. Den "Aus"-Zustand des Schalters würde ich in meinem Fall nicht mit einer eigenen Szene-ID belegen, da ich es gut finde, wenn der Schalter nach einigen Sekunden von der Bridge wieder auf "0" zurückgesetzt wird. 

Letztlich geht es nur darum, einem simplen Schalter die Möglichkeit zu bieten, eine oder zwei Szene-IDs auf den Bus zu legen und sich, je nach Parametrierung, nach kurzer Zeit wieder zurückzusetzen.

**Comment by Superwuzy** [comment]
@brutella Gibt es schon Neuerungen bzgl. der Szene-Unterstützung?

**Comment by traxanos** [comment]
Ich hätte es so implementiert, dass wenn man einen Schalter einschaltet, dieser so schnell wie möglich wieder ausgeht. Dabei verschickt es immer ein True an eine GA. Somit könnte man (ohne den Schalter zu öffnen) einen Taster simulieren. Was ich mit dem ein 1bit anstelle kann dann jeder selber überlegen. Ob ich es später auf eine Szene Mappe oder eine 1bit Szene aufruft kann ich dann in KNX lösen wie iches brauche.

Beim Ausschalten eine "Aus" Szene zu schalten halt ich für Schwachsinn, da da ja überhaupt keine Zustand bekannt ist.

@brutella wäre das nicht eine einfach und saubere Lösung.

**Comment by brutella** [comment]
Diese Funktion ist im Pre-Release Build für [Version 1.3.0](https://github.com/brutella/hkknx-public/releases/tag/1.3.0) verfügbar.

**Comment by BugRoger** [comment]
Tried it today. Works. Nice, thank you for implementing this feature.

**Comment by brutella** [comment]
Great. I will close the issue then.
