### ISSUE TITLE
Run webserver custom web path

### ISSUE THREAD

**Issue by wordtechnic** [brutella/hkknx-public#45]
Hello Matthias,
is possible add custom webserver path as start parameter?
I need run hkknx on the same port 80 with my existing webserver.
I tried proxy_pass in nginx but with problems.
Thank you.
Bořek

**Comment by brutella** [comment]
I don't know what those words mean.

**Comment by wordtechnic** [comment]
Example:
hkknx -port 80 -path homekitknx -db /data
= http://192.168.0.10/homekitknx

**Comment by brutella** [comment]
Got it. This is currently not possible. 
Why not use a different port, like `8081`?

**Comment by wordtechnic** [comment]
I am developing a container application for hkknx,
for KNX gateway Wiser for KNX.
The webserver is already running on port 80 on this hardware, and I need hkknx to be accessible on port 80 as well.

**Comment by brutella** [comment]
Is this still an issue?

**Comment by wordtechnic** [comment]
Yes, I run hkknx on Wiser for KNX hardware directly.
The device is already running an internal web server on port 80.
I would like to run Hhkknx also on port 80, I need a custom web path for that. 
Thank you.

______________________________________________________________

**Comment by brutella** [comment]
Any specific reason why running it at port, ex. 81, doesn't work for you?

**Comment by brutella** [comment]
Closed due to inactivity...
