### ISSUE TITLE
Evaluate windows package

### ISSUE THREAD

**Issue by brutella** [brutella/hkknx-public#47]
Let see if it is feasible to provide a Windows package...

**Comment by rw71** [comment]
No, this is not required. For my opinion Raspberry Pi support is enough.

**Comment by getcom** [comment]
Windows with its update & reboot policy is something unwanted from my perspective.

**Comment by brutella** [comment]
Closed because nobody likes Windows 😄

**Comment by getcom** [comment]
> Closed because nobody likes Windows smile

confirmed
