### ISSUE TITLE
Provide and support a docker image

### ISSUE THREAD

**Issue by brutella** [brutella/hkknx-public#52]

**Comment by BugRoger** [comment]
I'm running hkknx in Kubernetes and Docker. Feel free to help yourself here: https://github.com/BugRoger/dockerfiles/tree/master/hkknx
https://hub.docker.com/r/bugroger/hkknx/tags

It's a multi-arch image that works on both arm and amd64. It's quite minimal with being only 13mb big. 

There's a bit of magic to make the arguments configurable via ENV variables. That's easy enough to remove if you don't like that.

**Comment by Zinski** [comment]
So I am running this docker image now on my pi4 but I am not able to connect to my KNX-interface.
it just says that the gateway isn't reachable. 
The check for the bridge state gives "bridge not yet reachable".

@BugRoger maybe its possible that you add some documentation on how to deploy the image in docker? 
how to persist and how to enable the container to reach the gateway if there is any tweak for that

Any idea why?

**Comment by BugRoger** [comment]
> it just says that the gateway isn't reachable.
Sounds like have general network problems. First try that you can actually reach the gateway from your rpi. Something like: `telnet 192.168.0.185 3671`

If that works, check if rpi and gateway are they on the same subnet. If not the auto-discovery will not work. You then need to manually configure the IP of your gateway. Do you maybe have cable and wifi connected same time? I faintly remember a problem when HKKNX is bound to multiple interfaces. 

If that is all good, put the container in host network mode:
```
docker run --rm -d --network host --env VERBOSE=true --port 8080 --name hkknx bugroger/hkknx:latest
```

Do you use a MDT IP Router? I couldn't get mine to work.

> The check for the bridge state gives "bridge not yet reachable".
That is odd. Anything in the Docker log when VERBOSE is turned on?

**Comment by Zinski** [comment]
Thanks for the reply.

Telnet works from within the container.
Everything is wired and in the same subnet. the pi itself can ping and telnet into the gateway.

Indeed I am using an MDT Interface.
Is that the problem???

**Comment by BugRoger** [comment]
> Indeed I am using an MDT Interface.
> Is that the problem???
Could be. What does the log say? I had panics (crashes) like this:

```
2020/09/12 10:21:46 sequence number one less than expected
panic: send on closed channel

goroutine 53 [running]:
github.com/brutella/knx/knxnet.(*link).publishMsg(0xc0000fdc00, 0xffb900, 0xc000156180)
	/Users/mah/Source/Code/Go/src/github.com/brutella/knx/knxnet/link.go:221 +0x4d
created by github.com/brutella/knx/knxnet.(*link).GroupRead
	/Users/mah/Source/Code/Go/src/github.com/brutella/knx/knxnet/link.go:208 +0x149
panic: send on closed channel

goroutine 64 [running]:
github.com/brutella/knx/knxnet.(*link).publishMsg(0xc0000fdc00, 0xffb900, 0xc000156700)
	/Users/mah/Source/Code/Go/src/github.com/brutella/knx/knxnet/link.go:221 +0x4d
created by github.com/brutella/knx/knxnet.(*link).GroupRead
	/Users/mah/Source/Code/Go/src/github.com/brutella/knx/knxnet/link.go:208 +0x149
```

I think, this is due to some bug in the MDT gateway or the knxnet library. As I had another gateway that worked I didn't explorer that further. knxd could work.

> I am also not able to add the bridge in homekit. So this communication is also blocked.
> I am using portainer to maintain my containers on my pi, the container isn't reachable if I set the network to host. Maybe I am missing something here?
I'm not super familiar with Portainer. I would suppose that selecting the `host` network and publishing all ports will make hkknx available on port 8080 on the rpi's IP. Add `VERBOSE=true` in the ENV section and check the logs.

**Comment by Zinski** [comment]
```DEBUG 2020/11/19 12:46:57 main.go:147: app: dial gateway: no route to 192.168.178.9:3671; retrying in 5s,
DEBUG 2020/11/19 12:47:12 main.go:147: app: dial gateway: no route to 192.168.178.9:3671; retrying in 5s,
DEBUG 2020/11/19 12:47:27 main.go:147: app: dial gateway: no route to 192.168.178.9:3671; retrying in 5s,
DEBUG 2020/11/19 12:47:42 main.go:147: app: dial gateway: no route to 192.168.178.9:3671; retrying in 5s,
```

these are the logs on a bridge network,
on a host network the container isn't available, i cant reach it, neither with it's FQDN nor by ip

**Comment by Joeknx** [comment]
@BugRoger thanks for the Docker-Image. It is still on 1.1.0. Can I update within the Container? I heard, that this is not the best way.

**Comment by thorsten-gehrig** [comment]
Hi
i´m also looking vor 1.1.2 image... any chance to get an update?
Best
Thorsten

**Comment by BugRoger** [comment]
I pushed an the `burgoger:hkknx` in `1.1.2` and `1.2.0`. Thanks for the ping. I didn't notice the update. Enjoy!

**Comment by Joeknx** [comment]
Hey @BugRoger could you update your Docker image to the latest 1.2.0 final? It was beta before. Thanks a lot!

**Comment by thorsten-gehrig** [comment]
+1

**Comment by BugRoger** [comment]
I don't quite follow. The `bugroger/hkknx:1.2.0` image is using the latest release `1.2.0 (2021-01-29T13:13:41+01:00)`.

As far as I can see that corresponds to the latest release here in Github.

**Comment by brutella** [comment]
The latest build for version 1.2.0 is `1.2.0 (2021-03-10T12:54:28+01:00)`.

**Comment by BugRoger** [comment]
Ok, where do I get it from? The last release here in Github is from 2021-01-27.

**Comment by BugRoger** [comment]
Ah, you replaced the assets on the release. I just rebuilt the image. 

If you have been running that image before you need to do a `docker pull bugroger/hkknx:1.2.0` to bust the Docker cache. Better use `bugroger/hkknx:1.2.0-202103161235` to avoid confusion.

**Comment by brutella** [comment]
> Ah, you replaced the assets on the release. I just rebuilt the image.

Correct. As long as the version is marked as pre-release, I just upload new builds.
Once the version is final, the assets don't change anymore.

**Comment by Joeknx** [comment]
Perfect. Thx!

**Comment by BugRoger** [comment]
1.30-pre is available now

**Comment by Joeknx** [comment]
> 1.3.0(-pre) is available now

1.3.0 final is out now.
Thx in advance!

**Comment by Zinski** [comment]
> @BugRoger maybe its possible that you add some documentation on how to deploy the image in docker?
> how to persist and how to enable the container to reach the gateway if there is any tweak for that

@BugRoger is it possible to share some information about persistence?

**Comment by Joeknx** [comment]
push

**Comment by Joeknx** [comment]
@BugRoger 1.3.1 is out 😬

**Comment by BugRoger** [comment]
Pushed 1.3.1 and 2.0.0

> @BugRoger is it possible to share some information about persistence?

There's nothing much to it. `hkknx` writes to `/db` by default. You have to pass a volume from the host into the container `docker run -v /home/zinski/hkknx:/db ...`

See: https://hochgatterer.me/de/hkknx/docs/install/rpi-cli/#installation

**Comment by andreasgapsch** [comment]
Will there be an official support be panned, that we could run it on Synology or QNAP NAs?

**Comment by Joeknx** [comment]
I'd love to see the new releases. Thx!

**Comment by curana** [comment]
Is there a full description on how to set up hkknx with Docker? 

I found the image but it doesn't work for me on a RPi. Would be great if there would be a documentation somewhere on how to set it up, which ports to handle etc.

Could just be a comment on hub.docker.com. Would be great.

Thanks!

**Comment by curana** [comment]
Yes, using your image. I just followed the comments above and didnt provide any parameters. Thats why I thought you could maybe add like basic steps for your image.

**Comment by BugRoger** [comment]
Try `bugroger/hkknx:2.1.0` including the version. The `latest` image somehow is not including the ARM layers

**Comment by curana** [comment]
> Try `bugroger/hkknx:2.1.0` including the version. The `latest` image somehow is not including the ARM layers

That fixed it for me. Thanks.

**Comment by BugRoger** [comment]
Pushed `bugroger/hkknx:2.2.0`

**Comment by Joeknx** [comment]
2.3.1 is out.
Thanks in advance!

**Comment by mbrockeu** [comment]
If somebody needs the current versions, I provided them, based on the scripts above, on https://hub.docker.com/r/mbrockeu/hkknx/tags for arm64

**Comment by SvenBunge** [comment]
@mbrockeu : If you could also build for amd64 or @BugRoger update his docker image to 2.4 it would really help me to install the actual version on my synology nas. Thx alot!

**Comment by mbrockeu** [comment]
@SvenBunge in my package the following platforms are currently defined: 

--platform linux/amd64,linux/arm,linux/arm64

So it should work?

**Comment by BugRoger** [comment]
Pushed 2.4.1. It's time for a Github Action that automates this... I'll take a stab at it in the next days

**Comment by BugRoger** [comment]
There's now a Github Action that automated the release of the `bugroger:hkknx` Docker image. New releases will automatically be published once per day
 
https://github.com/BugRoger/dockerfiles/blob/master/.github/workflows/hkknx-image.yml

**Comment by Joeknx** [comment]
Great work! Thank you!

**Comment by mbrockeu** [comment]
> There's now a Github Action that automated the release of the `bugroger:hkknx` Docker image. New releases will automatically be published once per day
> 
> https://github.com/BugRoger/dockerfiles/blob/master/.github/workflows/hkknx-image.yml

Could you also provide an image for arm64v8? :-)

thanks

**Comment by BugRoger** [comment]
> Could you also provide an image for arm64v8? :-)
Yes. Just added `linux/arm/v8`. The `bugroger/hkknx:2.4.1` image comes with all 3 platforms now.

**Comment by SvenBunge** [comment]
> There's now a Github Action that automated the release of the bugroger:hkknx Docker image. New releases will automatically be published once per day

arm64: Thanks. I'll try it out!
Regarding github action: Perfect idea. Had the same today and just checked this thread before starting the configuration my myself.

**Comment by jhuber** [comment]
Any chance for an Unraid Docker Image? Would be fantastic to see hkknx integrated into the Unraid Community Apps.

**Comment by thorsten-gehrig** [comment]
Hi
it´s easy to add the existing docker image to unraid... i´m using this since >1 year!
Best
Thorsten

**Comment by mbrockeu** [comment]
> There's now a Github Action that automated the release of the `bugroger:hkknx` Docker image. New releases will automatically be published once per day
> 
> https://github.com/BugRoger/dockerfiles/blob/master/.github/workflows/hkknx-image.yml



> There's now a Github Action that automated the release of the `bugroger:hkknx` Docker image. New releases will automatically be published once per day
> 
> https://github.com/BugRoger/dockerfiles/blob/master/.github/workflows/hkknx-image.yml

Hi, maybe the action doesn't work? The latest image is still b4.

**Comment by coolbox13** [comment]
This compose.yaml works for me. Set the bridge port fixed to 51827.
[compose.yaml.zip](https://github.com/brutella/hkknx-public/files/10556923/compose.yaml.zip)

**Comment by mirkolenz** [comment]
After using a custom Dockerfile and local build pipeline for a while, I finally had the time to develop an automated pipeline for publishing a HKKNX docker image:

https://github.com/mirkolenz/hkknx-container

The image is built every night for the `latest` and `beta` releases of HKKNX. The containers are available for `arm64` and `amd64`. The image is built from scratch and thus only contains the required binaries, meaning the container has the same size as the HKKNX binary itself. The CLI parameters can be set by overriding the Docker command. Here is an exemplary compose definition:

```yaml
services:
  hkknx:
    image: ghcr.io/mirkolenz/hkknx-container:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./hkknx:/db
```

Please let me know if you run into any issues with this image.

**Comment by jalouxx** [comment]
I am using the Raspberry image of hkknx and that worked well. Due to some hardware consolidation I would love to migrate my setup to a container image. Luckily I've found the image from @BugRoger but it seems like I am holding it wrong since it cannot access the gateway `no route`.
```
INFO 2023/07/29 08:53:37 main.go:79: version 2.6.0 (built at 2023-03-20T12:16:05Z+0100)
INFO 2023/07/29 08:53:37 main.go:221: webpage available at port 8080
DEBUG 2023/07/29 08:53:47 app.go:340: dial gateway: no route to 192.168.137.196:3671
```

What I have checked so far:
- The IP and Port is correct. Same settings run on the standalone pi
- The container network has multicast enabled
- I can ping the IP within containers
- disconnect the pi in case only one hkknx instance could connect to the gateway at the same time

My container runtime is podman, running with ubuntu on an odroid M1.

@brutella is there any (linux) command I could run to troubleshoot the connection? Like whatever hkknx is using to verify that the gateway is accessible.

**Comment by brutella** [comment]
Please check if your network configuration meets the requirements → https://hochgatterer.me/de/hkknx/docs/config/knx-connection/

**Comment by brutella** [comment]
Based on some existing Dockerfiles for `hkknx`, I now provide an official image on https://hub.docker.com/repository/docker/brutella/hkknx.

**Comment by mirkolenz** [comment]
Great to hear @brutella 😊

Would you consider adding tags for major and minor versions as well (i.e., the current image would have the tags latest, 3, 3.0, and 3.0.0)? Then I could finally sunset my custom container.

**Comment by brutella** [comment]
There are now images for 
- major (e.g. `brutella/hkknx:3`)
- minor (e.g. `brutella/hkknx:3.0`)
- and patch (e.g. `brutella/hkknx:3.0.0`)

versions available as well.

@mirkolenz Thanks for reminding me.

**Comment by mirkolenz** [comment]
Great, thank you!

**Comment by thorsten-gehrig** [comment]
Hi
can you share when the docker container will be updated to 3.1?
Best
Thorsten

**Comment by brutella** [comment]
Ups, forgot to push the latest containers. 3.1.0 should be available now.

**Comment by pfeifix** [comment]
> I am using the Raspberry image of hkknx and that worked well. Due to some hardware consolidation I would love to migrate my setup to a container image. Luckily I've found the image from [@BugRoger](https://github.com/BugRoger) but it seems like I am holding it wrong since it cannot access the gateway `no route`.
> 
> ```
> INFO 2023/07/29 08:53:37 main.go:79: version 2.6.0 (built at 2023-03-20T12:16:05Z+0100)
> INFO 2023/07/29 08:53:37 main.go:221: webpage available at port 8080
> DEBUG 2023/07/29 08:53:47 app.go:340: dial gateway: no route to 192.168.137.196:3671
> ```
> 
> What I have checked so far:
> 
> * The IP and Port is correct. Same settings run on the standalone pi
> * The container network has multicast enabled
> * I can ping the IP within containers
> * disconnect the pi in case only one hkknx instance could connect to the gateway at the same time
> 
> My container runtime is podman, running with ubuntu on an odroid M1.
> 
> [@brutella](https://github.com/brutella) is there any (linux) command I could run to troubleshoot the connection? Like whatever hkknx is using to verify that the gateway is accessible.

Just wanted to ask if and how you got this resolved? I am currently trying to move hkknx from a Hyper-V VM into a docker container running on Docker Desktop (Windows) via WSL2.

I have the same problem: hkknx cannot find my IP gateway. The system log says "dial gateway: no route to 192.168.0.25:3671" although I can ping this from within the container.

Repetitive outputs on the docker environment command line are as follow:

x  | goroutine 896 [running]:
hkknx  | net/http.(*conn).serve.func1()
hkknx  |        net/http/server.go:1947 +0xbe
hkknx  | panic({0xf368a0?, 0x25acc50?})
hkknx  |        runtime/panic.go:785 +0x132
hkknx  | github.com/brutella/hkknx/html.(*Html).WsKnxBusloadChart(0xc00018e1b0, {0x7f3b2f4752b8, 0xc0000f1c00}, 0xc000ef4780)
hkknx  |        github.com/brutella/hkknx/html/status.go:197 +0xe56
hkknx  | net/http.HandlerFunc.ServeHTTP(0xf27040?, {0x7f3b2f4752b8?, 0xc0000f1c00?}, 0xc000600180?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc00064b5c0, {0x7f3b2f4752b8, 0xc0000f1c00}, 0xc000ef4780)
hkknx  |        github.com/go-chi/chi/v5@v5.0.11/mux.go:443 +0x2b4
hkknx  | net/http.HandlerFunc.ServeHTTP(0xc000b2f4e8?, {0x7f3b2f4752b8?, 0xc0000f1c00?}, 0x0?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | github.com/brutella/hkknx/html.(*Html).Router.func4.ValidateToken.7.1({0x7f3b2f4752b8, 0xc0000f1c00}, 0xc000ef4780)
hkknx  |        github.com/brutella/hkknx/html/html.go:440 +0xe4
hkknx  | net/http.HandlerFunc.ServeHTTP(0xc000d750e0?, {0x7f3b2f4752b8?, 0xc0000f1c00?}, 0xc000b2f6a0?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc00064b5c0, {0x7f3b2f4752b8, 0xc0000f1c00}, 0xc000ef4780)
hkknx  |        github.com/go-chi/chi/v5@v5.0.11/mux.go:73 +0x32f
hkknx  | github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x7f3b2f4752b8, 0xc0000f1c00}, 0xc000ef4780)
hkknx  |        github.com/go-chi/chi/v5@v5.0.11/mux.go:315 +0x1bb
hkknx  | net/http.HandlerFunc.ServeHTTP(0xf27040?, {0x7f3b2f4752b8?, 0xc0000f1c00?}, 0xc0012206c0?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc00064b560, {0x7f3b2f4752b8, 0xc0000f1c00}, 0xc000ef4780)
hkknx  |        github.com/go-chi/chi/v5@v5.0.11/mux.go:443 +0x2b4
hkknx  | net/http.HandlerFunc.ServeHTTP(0x25b0d00?, {0x7f3b2f4752b8?, 0xc0000f1c00?}, 0x0?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | github.com/brutella/hkknx/html.(*Html).Router.Synchronizer.func5.1({0x1e640d0?, 0xc00096c1c0?}, 0xc000ef4780)
hkknx  |        github.com/brutella/hkknx/html/html.go:468 +0x138
hkknx  | net/http.HandlerFunc.ServeHTTP(0xc000d750e0?, {0x1e640d0?, 0xc00096c1c0?}, 0xc0009ea920?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc00064b560, {0x1e640d0, 0xc00096c1c0}, 0xc000ef4780)
hkknx  |        github.com/go-chi/chi/v5@v5.0.11/mux.go:73 +0x32f
hkknx  | github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x1e640d0, 0xc00096c1c0}, 0xc000ef4780)
hkknx  |        github.com/go-chi/chi/v5@v5.0.11/mux.go:315 +0x1bb
hkknx  | net/http.HandlerFunc.ServeHTTP(0xf27040?, {0x1e640d0?, 0xc00096c1c0?}, 0xc000ab02d4?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0001188a0, {0x1e640d0, 0xc00096c1c0}, 0xc000ef4780)
hkknx  |        github.com/go-chi/chi/v5@v5.0.11/mux.go:443 +0x2b4
hkknx  | net/http.HandlerFunc.ServeHTTP(0xc000ef4780?, {0x1e640d0?, 0xc00096c1c0?}, 0xc000ef4780?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | main.main.AlwaysHttp.func10.1({0x1e640d0?, 0xc00096c1c0?}, 0x25ac301?)
hkknx  |        github.com/brutella/hkknx/middleware/http.go:12 +0x5c
hkknx  | net/http.HandlerFunc.ServeHTTP(0x1e66708?, {0x1e640d0?, 0xc00096c1c0?}, 0x25ac310?)
hkknx  |        net/http/server.go:2220 +0x29
hkknx  | github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0001188a0, {0x1e640d0, 0xc00096c1c0}, 0xc000ef4640)
hkknx  |        github.com/go-chi/chi/v5@v5.0.11/mux.go:90 +0x2ee
hkknx  | net/http.serverHandler.ServeHTTP({0xc000d74fc0?}, {0x1e640d0?, 0xc00096c1c0?}, 0x6?)
hkknx  |        net/http/server.go:3210 +0x8e
hkknx  | net/http.(*conn).serve(0xc000be4bd0, {0x1e666d0, 0xc00069a210})
hkknx  |        net/http/server.go:2092 +0x5d0
hkknx  | created by net/http.(*Server).Serve in goroutine 34
hkknx  |        net/http/server.go:3360 +0x485
hkknx  | 2025/05/21 15:47:19 http: panic serving [::1]:34946: runtime error: invalid memory address or nil pointer dereference
