### ISSUE TITLE
Error while searching for an update

### ISSUE THREAD

**Issue by alexanderbjelos** [brutella/hkknx-public#53]
Hello Matthias,

when I click "searching for new updates" in the webinterface, I received the following error message:

Get "https://api.github.com/repos/brutella/hkknx-public/releases": x509: certificate has expired or is not yet valid: current time 2020-05-29T12:15:34+01:00 is before 2020-06-22T00:00:00Z

Alex

**Comment by brutella** [comment]
The date and time on your computer is too far in the past.
