### ISSUE TITLE
No connection to ip-gateway

### ISSUE THREAD

**Issue by Rollonat** [brutella/hkknx-public#56]
on the raspberry i can ping the MDT IP-Interface IP000.01, but i got no connection with direct ip nor with automatic search
the log says main.go:147: app: dial gateway: no route to 192.168.178.150:3671; retrying in 5s
what can i do?
both are connected to fritzbox

**Comment by brutella** [comment]
This looks like a network issue. Does your firewall block port 3671?

**Comment by Rollonat** [comment]
The switch is unmanaged, i dont see any port blocking in the fritzbox. hmm

**Comment by brutella** [comment]
Can you please double-check that pinging `192.168.178.150` from your Raspberry Pi does work.
Is your Raspberry Pi connected via Ethernet or WiFi to your local network?

**Comment by Rollonat** [comment]
Pinging from Raspi works. The Raspberry Pi is on Ethernet

**Comment by brutella** [comment]
Is multicast allowed on your network?

**Comment by brutella** [comment]
Closed due to inactivity

**Comment by Rollonat** [comment]
Now i have connection to the ip-gateway. I did a factory reset by turning off the device. Turning it on while holding down the button for 10 seconds. Thank you!
