### ISSUE TITLE
Rollladen Steuerung

### ISSUE THREAD

**Issue by darkangel72F** [brutella/hkknx-public#57]
Folgendes Problem. Um einen Rollladen anlegen zu können, für eine Kurz bzw. Langfahrt, wird ein Datentyp 5 verlangt? In der ETS wird dafür jedoch nur ein Datentyp 1.008 bzw. 1.007 verwendet. Wie bekomme ich dies nun übertragen, bzw. wie gelingt eine Anlage eines Rollladen? Danke

**Comment by brutella** [comment]
Für einen Rollladen in HomeKit werden Soll- und Ist-Position benötigt. Eine Steuerung des Rollladens ohne diese Informationen ist zurzeit nicht möglich.

Theoretisch wäre es möglich die Soll- und Ist-Positionen anhand der Fahrtdauer zu bestimmen. Dazu müsste die Brücke wissen, wie lange der Rollladen für eine komplette Fahrt benötigt.

**Comment by darkangel72F** [comment]
Hallo, sorry, da habe ich mich wahrscheinlich falsch ausgedrückt. Ich habe in KNX Soll und Ist Positionen DP, jedoch mit anderem Datentypen. Lediglich die Position an sich hat den korrekten Datentypen, aber ich kann diesen ja nicht für das Schreiben Lesen und Initialisieren verwenden? 
Ich bräuchte doch wenigstens 2 GAs, aber meine Schreibadressen sind immer nur vom Datentypen 1.008 und dieser lässt sich nicht zuordnen. Mit der Version 0.18 lief meine Anlage noch perfekt. Danke

**Comment by brutella** [comment]
Die Zielposition des Rollladens wird über die Soll-Position gesteuert. Zum Beispiel für **50% Offen** wird der Wert **50%** an den Aktor gesendet. Mit dem Datentyp 1.008 kann der Rollladen nur komplett geschloßen oder geöffnet werden – das verwendet HKKNX nicht.

Bei einem Garagentor ist das anders. Da in HomeKit ein Garagentor nur komplett geöffnet oder geschloßen werden kann, wird da auch ein 1.xxx Datentyp verwendet.

**Comment by darkangel72F** [comment]
Danke, Groschen ist gefallen. Funktioniert nun.
