### ISSUE TITLE
Gateway nicht erreichbar

### ISSUE THREAD

**Issue by feanmg** [brutella/hkknx-public#6]
Hallo,

die Anwendung sieht sehr vielversprechend aus!!

Leider bekomme ich sie nicht zum laufen. Bei direkter Angabe der IP-Adresse des KNX-Gateways kommt die Meldung "Gateway nicht erreichbar". Bei Suche nach Gateway stürzt das Programm ab. (write udp4 192.168.x.x:44253->0.0.0.0:0: sendto: invalid argument)

Installiert habe ich es auf einem jungfräulichen Raspbian-Image. Von dem Raspy kann ich das Gateway anpingen.

Über eine Hilfe würde ich mich sehr freuen!

Viele Grüße!

**Comment by brutella** [comment]
Welche Version verwendest du?

**Comment by feanmg** [comment]
Oh, das ging ja schnell :)
0.0.9

**Comment by brutella** [comment]
Was, wenn du die Automatische Suche verwendest?

Was für einen Browser verwendest du?

Könntest du mal in die `server.json` Datei in dem "database" Ordner nach dem Feld **ip** suchen.  (Ist unter projects.knx.ip) Welcher Wert ist hier angegeben?

**Comment by feanmg** [comment]
aktuell: "knx":{"discovery-type":1,"ip":"192.168.0.44"

Klicke ich auf "Automatische Suche" -> Speichern und Suche dann mit "Verbindung prüfen", stürzt das Programm ab (s.o.)

Browser: FF 72 (Mac). Chrome 80 gleiches Verhalten.

**Comment by brutella** [comment]
An was für einem Netzwerk hängt der Raspberry Pi?
Ist Multicast in diesem Netzwerk erlaubt?

**Comment by feanmg** [comment]
Beide Geräte (Raspi + KNX-Gateway) hängen am LAN im gleichen Subnetz.
mDNS (auf UniFi USG) war deaktiviert, ein testweises aktivieren brachte leider keine Verbesserung.

**Comment by brutella** [comment]
Versuch mal die gerade hochgeladene [Pre-Release Version 0.0.10](https://github.com/brutella/hkknx-public/releases/tag/0.0.10).

**Comment by feanmg** [comment]
Danke! Das Programm stürzt nun nicht mehr ab, aber die Fehlermeldung "Gateway nicht erreichbar" bleibt (sowohl bei automatischer Suche, als auch bei vorgegebener IP).

Im Switch (Netgear GS724T) habe ich noch folgende Multicast-Einstellungen (MFDB, IGMP Snooping, MLD Snooping). Alle sind per Factory-Default (ich kenn mich da nicht sehr aus) deaktiviert.

**Comment by brutella** [comment]
Sind bestimmte Port-Bereiche gesperrt?
Port 3671 muss auf jeden Fall offen sein.

**Comment by feanmg** [comment]
Nein, Netzwerktechnisch nicht dass ich wüsste. Auch der EDOMI-"Server" greift via diesen Port auf das Gateway zu.

Kann ich das auf dem (neuen) Raspberry irgendwie testen?

**Comment by brutella** [comment]
Habe gerade noch einen Fehler gefunden und einen neuen Build hochgeladen. Download-Link bleibt der selbe. Bitte nochmal runterladen und ausprobieren.

**Comment by feanmg** [comment]
Vielen Dank für dein Engagement.

Leider brachte auch die neue Version keine Verbesserung
(version 0.0.10 (built at 2020-02-18T14:20:22Z+0100))

**Comment by brutella** [comment]
Hm, jetzt gehen mir langsam die Ideen aus.

Überprüf mal mit dem `nmap` Befehl ob das Gateway über den Pot 3671 erreichbar ist.
```shell
nmap -p 3671 192.168.0.44
```

**Comment by feanmg** [comment]
hmmmm....

`pi@raspberrypi:~ $ nmap -p 3671 192.168.0.44 -Pn
Starting Nmap 7.40 ( https://nmap.org ) at 2020-02-18 13:41 UTC
Nmap scan report for KNXIPInterface731.localdomain (192.168.0.44)
Host is up.
PORT     STATE    SERVICE
3671/tcp filtered efcp`

(...auf dem EDOMI-Rechner zeigt nmap ähnliches an)

**Comment by brutella** [comment]
Einen letzten Versuch hab ich noch unternommen. Hab einen neun Build hochgeladen – Link bleibt gleich.

**Comment by feanmg** [comment]
Hat leider nicht funktioniert. Sehr schade, trotzdem danke!
(Die Verbindungssuche fühlt sich aber jetzt an, als würde er suchen (kurze Verzögerung).
Muss jetzt zum Arzt, ich schaue nachher nochmal rein.
Viele Grüße!

**Comment by feanmg** [comment]
So, wieder zurück!

Also, vielen Dank für deinen Einsatz - ich würde jetzt selbst noch versuchen, den "Fehler" zu finden.

Sollte irgendeine Multicast-Einstellung aktiviert sein (MFDB, IGMP Snooping, MLD Snooping)?

Wenn du jemanden zum Testen brauchst, stehe ich gerne zur Verfügung! Ich werde dein Projekt weiter verfolgen.

Viele Grüße!

**Comment by brutella** [comment]
Bei der direkten Verbindung über eine IP Adresse hab ich vermutlich einen Bug – den versuche ich gerade zu fixen.

Die Automatische Gateway Suche sollte dennoch funktionieren, solange Multicast erlaubt und der Port 3671 nicht blockiert ist.

**Comment by brutella** [comment]
So, mit dem aktuellsten Build wurde etwas Grundlegendes geändert.

Bei der Angabe einer fixen IP-Adresse (und jetzt auch Port) des Gateways, wird direkt eine Tunnel Verbindung aufgebaut – vorher gab es noch eine Suchanfrage, welche ohne Multicast nicht funktionierte.

Bitte ausprobieren.

**Comment by feanmg** [comment]
Das sieht doch schon mal nicht schlecht aus:
`Gateway erreichbar unter 192.168.0.44:3671`
:)

_(Ich habe im Vorfeld auch schon versucht, den Port anzugeben, hat aber damals nicht funktioniert)_

((Beim aktivieren des IGMP-Snooping im Switch bin ich gestern übrigens grandios gescheitert))

Ich teste weiter!

**Comment by feanmg** [comment]
Wirklich toll, herzlichen Dank! Ich schließe dann das Ticket.
Am Wochende bringe ich das ganze in Produktion (rel. umfangreiche KNX-Installation).

**Wenn alles klappt, wird dein Gateway richtig cool! Ich bleibe dran!**

_(Ein Feature-Request habe ich noch: Könntest du (zB. im Hilfetext) erläutern, wie das ganze als Dämon immer automatisch mit Systemstart gestartet werden kann?)_

**Comment by brutella** [comment]
Das mit dem Daemon ist alles [hier](https://hochgatterer.me/hkknx/diy/) erklärt.
