### ISSUE TITLE
Rolladen offen/geschlossen

### ISSUE THREAD

**Issue by chef76** [brutella/hkknx-public#61]
Ist eine Jalousie geschlossen, wird auf Button und im Detailscreen geschlossen angezeigt:

![image](https://user-images.githubusercontent.com/69462419/89780486-d30d1b80-db11-11ea-9954-c7840530e149.jpeg)

Ist die Jalousie offen, wird aber nicht offen oder geöffnet angezeigt, sondern öffnen:

![image](https://user-images.githubusercontent.com/69462419/89780600-0f407c00-db12-11ea-933d-4c948ad54af5.jpeg)

hab ich eben erst gesehen:

https://github.com/brutella/hkknx-public/issues/24

Weiteres Problem:
Ist die Jalousie zu 100% geschlossen, die Lamelle aber nicht (z.B. 40%), dann zeigt der Knopf immer Schließen und working an:

![image](https://user-images.githubusercontent.com/69462419/89780786-621a3380-db12-11ea-803c-84135d86447d.jpeg)

**Comment by chef76** [comment]
Vermutlich liegt es daran, dass die Ist-Position des Behangs bei der Lamellenverstellung von 100% auf 99% geht.

**Comment by brutella** [comment]
Ist das so?

**Comment by chef76** [comment]
Ja, wenn der Behang zu 100% geschlossen ist, und die Lamelle wird um mehr als 50% verstellt, geht die Position auf 99%. 

![image](https://user-images.githubusercontent.com/69462419/89908973-dc1fea80-dbee-11ea-98eb-deb434a2e084.jpeg)

Das wird auch auf dem Bus so gemeldet. Der Screenshot ist aus der eibPort Visu.

Wenn Du Logs aus der Konsole brauchst, sag Bescheid.

**Comment by brutella** [comment]
Wird dabei auch die neue Soll-Position von 99% auf den KNX Bus gesendet?

**Comment by chef76** [comment]
Nein. Ich vermute, das ist auch der Grund, dass dann Ist- und Sollwert voneinander abweichen und er deshalb denkt die Jaousie fährt noch:

![image](https://user-images.githubusercontent.com/69462419/90008335-72f6b080-dc9c-11ea-950d-533e5eb572ed.png)

Ich hab mal versucht das über das senden von falschen Ist-Positionen zu provozieren, dann schmiert aber anscheinend die Brücke ab, da sie danach keine Positionsmeldungen mehr verarbeitet hat und sich erst durch einen Neustart wieder dazu überreden lies. Es ist aber zu 100 % reproduzierbar: Jalousie zu 100 % schliessen und dann die Lamelle auf 40% stellen, dann kreiselt der Button munter vor sich hin und zeigt schliessen an.
