### ISSUE TITLE
No route to gateway

### ISSUE THREAD

**Issue by c-14-n** [brutella/hkknx-public#68]
Facing problem with KNX gateway access since update to v1.1.1.

HKKNX is running on a Pi4/4G, tried to change from using fixed IP for gateway to multicast. Once I re-test the connection, following error appears:
`unpack [6 16 2 6 0 8 0 36]: unexpected EOF`

Debug console reports the following:
`DEBUG 2020/10/24 knx.go:63: dial tunnel: dial gateway: no route to 192.168.1.3:3671`

KNX gateway is definitively available on port 3671 from Pi4.

Can you read the error message?

**Comment by brutella** [comment]
The response from the IP gateway to a connect request is invalid. What IP gateway are you using?

**Comment by c-14-n** [comment]
I'm using the ABB IPR/S 2.1 gateway, which supports tunneling as well as routing.
Currently,  gateway still reports as "not available" (knx.go:63: dial tunnel: dial gateway: no route to 192.168.1.3:3671), though actual control commands get to the gateway.

**Comment by brutella** [comment]
I just uploaded a pre-release version [1.1.2](https://github.com/brutella/hkknx-public/releases/tag/1.1.2) which provides a better error description when the connection to the IP gateway cannot be established. 

In your case the problem is that the maximum number of IP connections to your gateway are already reached – meaning that no more connections are accepted.

**Comment by c-14-n** [comment]
Thanks, additional log is very helpful. The issue was caused by exceeding maximum number of allowed connections (ABB IPR/S 2.1 supports one tunnel only).

Any plan to allow KNX/IP communication through multicast (224.0.23.12)?

**Comment by brutella** [comment]
> Any plan to allow KNX/IP communication through multicast (224.0.23.12)?

How should that work?

**Comment by c-14-n** [comment]
It would work using KNX/IP Router functionality, whereby communication with the gateway goes through mulitcast instead of tunneling. Same way as e.g. the Gira Homeserver does:
![Screenshot 2020-10-27 at 18 33 29](https://user-images.githubusercontent.com/73139890/97339524-faf35c00-1882-11eb-8fe7-5667b376a6aa.png)

As such no point-to-point connection is required. If the KNX/IP gateway only support one simultaneous connection, which is "occupied" by HKKNX, programming through ETS is not possible using unicast.

**Comment by c-14-n** [comment]
Good overview on IP tunnelling vs IP routing.
https://www.ivoryegg.co.uk/essential_guides/a-guide-to-using-knx-over-ip

**Comment by brutella** [comment]
Have you tried to set the multicast address and port in hkknx Settings to connect via KNXnet/IP routing?

**Comment by brutella** [comment]
@c-14-n Are you able to get a tunnel connection in hkknx by setting the multicast address for the connection to the KNX gateway?

**Comment by brutella** [comment]
Closed due to inactivity...
