### ISSUE TITLE
Verhalten beim Upload einer aktualisierten knxproj

### ISSUE THREAD

**Issue by feanmg** [brutella/hkknx-public#7]
Wie verhält sich dein Gateway beim Upload einer aktualisierten knxproj, wenn

1, neue Gruppenadressen hinzugefügt wurden
2, bestehende GA verändert wurden (neue Beschreibung, Datentyp, ..)
3, vormals bestehende GA gelöscht wurden

?

_(Meine Erwartung bzgl. des Verhalten wäre:
1, vorhandene Verknüpfungen bleiben bestehen, neue GA können verknüpft werden
2 und 3, nicht betroffene GA bleiben bestehen, Verknüpfung bei betroffenen GA werden gelöst (Deutliche Hinweise bei Import und Geräteübersicht!))_

**Comment by brutella** [comment]
Beim jedem Import eines ETS Projektes, werden Gruppenadressen, Kommunikationsobjekte und Geräte erstellt und gespeichert. Wenn ein Projekt gelöscht wird, werden alle Gruppenadressen, Kommunikationsobjekte und Geräte von diesem Projekt gelöscht.

Wenn ich ein Projekt 2x importiere, bekomme ich für jedes Objekt ein Duplikat – zB eine Gruppenadresse taucht zweimal auf. Wenn ich eines von den zwei Projekten wieder lösche, bleiben die Gruppenadressen von dem anderen Projekt bestehen.

Die HomeKit Geräte werden beim Löschen eines Projektes nicht verändert – alle Referenzen zu den Gruppenadressen bleibt bestehen.

**Comment by feanmg** [comment]
Okay, vielen Dank für die Info. Dann eignet sich dein Gateway am besten für bereits abgeschlossene KNX-Projekte (sonst wird alles schnell unübersichtlich)

Wenn du mal Zeit hast, fände ich es gut, wenn du meine Anregung als Verbesserungsvorschlag prüfst:
Beim Import eines neuen ETS-Projektes sollen nur neue Gruppenadressen hinzugefügt werden. Verknüpfungen von veränderte oder gelöschte GAs können/sollten entfernt werden und ein Hinweis erscheinen.

**Comment by brutella** [comment]
> Beim Import eines neuen ETS-Projektes sollen nur neue Gruppenadressen hinzugefügt werden. Verknüpfungen von veränderte oder gelöschte GAs können/sollten entfernt werden und ein Hinweis erscheinen.

Wenn du ein bestehendes Projekt löscht und ein Neues importierst, kommt das selbe dabei raus.

**Comment by feanmg** [comment]
Danke!
<< alle Referenzen zu den Gruppenadressen bleibt bestehen. >> war die wichtigte Info, welche ich überlesen habe.
