### ISSUE TITLE
RGB control

### ISSUE THREAD

**Issue by Job-Hoogeboom** [brutella/hkknx-public#70]
I have a 24v RGB dimmer from the manufacturer Meanwell. But it only has separate RGB values. Can you make an extra profile to add support for separate group addresses?

**Comment by brutella** [comment]
What data type does your dimmer use to represent RGB values?

**Comment by Job-Hoogeboom** [comment]
![image](https://user-images.githubusercontent.com/61543367/98366298-02a9c200-2034-11eb-849c-ceab4219e7f9.png)

**Comment by brutella** [comment]
Ok, so every color channel (red, green, blue) is represented by 1 byte. Got it.

**Comment by Job-Hoogeboom** [comment]
Yes, Exactly. :)

**Comment by brutella** [comment]
Should be fixed in version 1.2.0
