### ISSUE TITLE
Security system sending wrong value

### ISSUE THREAD

**Issue by Graefer** [brutella/hkknx-public#71]
Switching the security system off with Homekit sends a ‚false‘ to the attached KNX group address. 
On the other hand, sending a ‚false’ to the above group address does not switch the securities status to off, as HomeKit is expecting a ‚true’.
This is obviously a bug! 
The bridge should rather send the original HomeKit status to the group address.

**Comment by brutella** [comment]
Just to clarify things.

- Your security system expects a **false** when turning it off.
- You set the data type of the the *Off* characteristic to DPST-1-3, right?
- When you turn off the security system through HomeKit (ex. Home app), HKKNX sends **false** to the group address.
- But when you turn off the security system through KNX, meaning that **false** is sent to the group address, HKKNX doesn't correctly turns the security system off.

**Comment by Graefer** [comment]
My security system (ABB SCM/S) has a group address (DPT1.001) for each, external and internal security which can independently switched on and off (expecting true for on and vice versa). There is no explicit group address to switch off the security system. 
But there are so many different security systems each with a different implementation which will make it necessary to use an external logic (e.g. NodeRed) in many cases.  
The point is exactly what you described in 3) and 4), that HomeKit/HKKNX sends a false if security system is switched off. But if a false is send to the group address, the security system is not switched off in Home app. You need to send a true to the group address to switch off the security system in Home app. 
I think HKKKNX should send HomeKit’s original value, which is a true.

**Comment by brutella** [comment]
Which values is sent from HKKNX depends on the datapoint type of the **Off** characteristic. 

If you set that to 
- DPT-1, then the value **1**
- DPST-1-3, then the value **0**

is sent when the security system is turned off.

**Comment by Graefer** [comment]
Nein, Home.app sendet beim Ausschalten der Alarmanlage _immer_ false, egal ob in Hkknx DPT-1 oder DPST1-3 eingestellt ist. 
Vielleicht sollte ich in der Hkknx mal ein neues Objekt für Alarmanlage anlegen?

Tobias

**Comment by brutella** [comment]
Should be fixed in [1.1.2](https://github.com/brutella/hkknx-public/releases/tag/1.1.2)

**Comment by mbrockeu** [comment]
> 

Hi, ich versuche auch gerade den ABB zum laufen zu bekommen. Kannst du mir ggfs. mal sagen, wie du das Problem gelöst hast, dass er die Werte korrekt setzt. Bzw. was du zum Beispiel bei Nacht gesetzt hast?

Der ABB hat ja kein Nacht, wäre daher auch interessant, ob man bestimmte Punkte auch deaktivieren kann.

Aktuell habe ich bei Aus jedenfalls den Alarm EXTERN als GA dran hängen. Hat den Nachteil, wenn ich auf "Zuhause" also INTERN SCHARF war, bekomme ich den Status so nicht weg. Ich vermute, dass ist dann der Hinweis mit der Logik. 

Wenn das nicht anders zu lösen geht muss ich mir wohl im X1 was bauen.
