### ISSUE TITLE
Support DPT 3.007 for Tunable White and relative Brightness

### ISSUE THREAD

**Issue by Zinski** [brutella/hkknx-public#72]
Support the DPT 3.007 type for Lightbulbs to dim their brightness relatively. The same datatype is used for relative temperature.
This a Dim step.

**Comment by brutella** [comment]
There is currently no plan to support that because the initial dim value is not defined when using the relative dimming function. See https://github.com/brutella/hkknx-public/issues/27#issuecomment-604962595

**Comment by Zinski** [comment]
But why?
isn't there a solution to this? I mean it should be defined somewhere what a "Dimmerschritt" means. and you are able to query the current percentage from the bus.
