### ISSUE TITLE
Neu angelegte Geräte werden nicht mehr in Homekit angezeigt

### ISSUE THREAD

**Issue by Peyto79** [brutella/hkknx-public#74]
Guten Abend,

ich bin Momentan fleißig am anlegen meiner KNX Geräte. Bisher alles einwandfrei. Funktioniert super. Aber:

Plötzlich tauchen neue Geräte nicht mehr in Homekit auf. Gelöschte Geräte verschwinden aber. 
(Habe ich gestestet, aber nun fehlt es mir und ich bekomme es nicht mehr rein)

Ich habe derzeit 119 Geräte angelegt. 

Ich habe die Bridge auch schon neu gestartet (vom Strom getrennt und auch über die UI probiert.)
Ergebnis bleibt leider. Neue Geräte tauchen nicht mehr auf.

Woran kann das liegen?

Viele Grüße
Christian

PS: Ich würde noch gerne meine letzten Thermostate anlegen und dann wäre ich fertig gewesen...

**Comment by Peyto79** [comment]
Ich glaube ich habe den Bug gefunden.

In der JSON sind die Objekte durchnummeriert. Ein gelöschtes Objekt gibt seine alte Nummer aber nicht mehr frei. Somit bin ich mit meinen neuen Objekten > 150 und diese werden wohl nicht mehr in Homekit geladen.

Ich habe 119 Geräte (zeigt HKKNX auch so an) aber in der JSON Datei haben diese neuen Objekte die nicht mehr in Homekit angezeigt werden eine ID größer als 150. Und weil dies das Limit von HKNX ist, vermute ich, dass sie deshalb nicht mehr in Homekit publiziert werden.

Könntest du zur Prüfung nicht die interne ID des JSON heranziehen sondern den Zähler der auch für die UI verwendet wird?

Vielen Dank und Grüße
Christian

**Comment by Peyto79** [comment]
Ich habe nun versucht die Server.json in einem Backup "aufzuräumen" und habe alle "archived=true" gelöscht.
Beim importieren des modifizierten Backups, wird es allerdings komplett ignoriert.

Ergebnis: Der Workaround funktioniert auch nicht.

Ich brauche ziemlich dringend eine Lösung dafür, da ich aktuell nicht weitermachen kann und blockiert bin.

Viele Dank und Grüße
Christian

**Comment by brutella** [comment]
Das Problem sollte in der aktuellsten Version [1.1.2](https://github.com/brutella/hkknx-public/releases/tag/1.1.2) von behoben sein.

**Comment by Peyto79** [comment]
Vielen Dank, mit 1.1.2 funktioniert es wieder.
