### ISSUE TITLE
Bool'sche Werte: Möglichkeit, sie beim Lesen und Schreiben zu negieren

### ISSUE THREAD

**Issue by Superwuzy** [brutella/hkknx-public#75]
Ich verfüge in meinem Haus über die Möglichkeit, Heizkreise zu öffnen und zu schließen. Zum Öffnen eines Heizkreises wird an den jeweiligen Aktorausgang eine 1 (Heizkreis wird unterbrochen) oder eine 0 (Heizkreis wird geöffnet) gesendet.

In der HKKNX-Konfigurationsoberfläche wird für einen Temperaturregler optional die Steuerung eines Heizungsventils angeboten. Die Unterstützung dort verhält sich jedoch genau umgekehrt zur Logik, die ich benötige (Heizkreis wird unterbrochen: AUS, Heizkreis wird geöffnet: EIN)  

Da es sicherlich des Öfteren vorkommt, dass sich Boolsche Zustände in der KNX-Welt genau umgekehrt zur HomeKit-Welt verhalten, wäre es gut, wenn man für Bool'sche Werte (Heizungsventil, Schalter usw.) für das Schaltobjekt ein negiertes Schaltverhalten aktivieren könnte (z.B. Checkbox "Negiertes Schaltverhalten"), so dass die KNX-Schreib- und Lesevorgänge jeweils negiert erfolgen: Bei zu lesenden GAs würde somit der Wert, von KNX kommend, in Richtung HomeKit negiert, bei schreibenden GAs, von HomeKit aus in Richtung KNX gehend, ebenfalls negiert.

**Comment by brutella** [comment]
Ups, da gab es wohl einen Fehler in der Programmierung. In der aktuellsten Pre-Release Version [1.1.2](https://github.com/brutella/hkknx-public/releases/tag/1.1.2) kannst du für das Heizungsventil als Datentyp **DPT-1** und **DPST-1-9** einstellen. Je nach Datentyp wird eine 1 oder 0 zum Öffnen des Ventils gesendet.

**Comment by Superwuzy** [comment]
@brutella In Version 1.2 habe ich bei einem Temperaturregler unter "Heizungsventil" in der Dropdown-Liste nur "DPST-1-9" zur Auswahl. 

Aktuelles Verhalten:
 
HomeKit: Heizung "Aus"         = KNX: 0 (Heizungsventil geschlossen)
HomeKit: Heizung "Heizung" = KNX: 1 (Heizungsventil offen)

Der Infotext in der Admin-Oberfläche passt nicht zu diesem Regelverhalten: "Öffnet (0) und schließt (1) das Heizungsventil".

---

Bei meiner Installation bräuchte ich jedoch das umgekehrte Verhalten - so wie es der Infotext eigentlich beschreibt:

HomeKit: Heizung "Aus"         = KNX: 1 (Heizungsventil geschlossen)
HomeKit: Heizung "Heizung" = KNX: 0 (Heizungsventil offen)

**Comment by Superwuzy** [comment]
Ich schaue mir mal die Pre-Release an.
