### ISSUE TITLE
Vorschlag: Geräte für Windmesser und Regensensoren (low prio)

### ISSUE THREAD

**Issue by Peyto79** [brutella/hkknx-public#76]
Hallo Matthias,

gibt es in Homekit Gerätetypen für Wind und Regen?
Aktuell behelfe ich mit mit Gerätetyp "Leckage Sensor" für Regen und einem "Lichtsensor" für Wind.

Regen wird deshalb in Homekit immer etwas übertrieben als "Leck entdeckt" gemeldet :-) 
und der Wind (m/s) wird in Lux ausgegeben.

Grundsätzlich habe ich also einen funktionierenden Workaround weshalb dieses Ticket eine niedrige Prio hat.

Viele Grüße
Christian

**Comment by brutella** [comment]
Nein, leider gibt es keine Wind- und Regensensoren in HomeKit.
Technisch wäre es einfach umsetzbar, nur leider würden diese Sensoren nicht richtig in der Apple Home-App auftauchen.

Sobald es Unterstützung dafür in HomeKit gibt, werden diese Geräte in HKKNX eingebaut.
