### ISSUE TITLE
RGB-Steuerung läuft bei mir nicht

### ISSUE THREAD

**Issue by Superwuzy** [brutella/hkknx-public#77]
@brutella 

ich habe seit Längerem einen MDT LED-Controller im Einsatz. 

Unter hkknx habe ich eine Lampe angelegt und zuerst nur die Eigenschaften "Schalten" und "Helligkeit" verbunden. Das klappt problemlos.

Nun habe ich die "Farbe"-Objekte verbunden (der LED-Controller liefert für die relative und absolute Farbtemperatur nicht die passenden DPST-Werte (DPST-5-1 sowie DPTS-7-6)).

Ich denke, mit Farbe sind RGB-Werte gemeint (RGB, DPST-232-600). Leider funktioniert das nicht. Egal, welche Farbe man in HomeKit auswählt: Die Bridge überträgt stets 2 Byte, die nicht dem eingestellten RGB-Farbwert entsprechen:

![image](https://user-images.githubusercontent.com/17985563/101978591-60928080-3c56-11eb-9848-82431620be40.jpeg)

Gebe ich über meinen Gira HomeServer einen RGB-Farbwert vor, sieht das so aus (korrekt):
![image](https://user-images.githubusercontent.com/17985563/101978614-8cae0180-3c56-11eb-9ce9-b6531809e28a.jpeg)

Die Konfiguration des Schalters:
![image](https://user-images.githubusercontent.com/17985563/101978633-ae0eed80-3c56-11eb-91cb-9662a837d66e.jpeg)

Im übrigen ist mir aufgefallen, dass auf den Bus kein Helligkeitswert mehr gesendet wird, sobald das Farb-Objekt verbunden ist - sobald man an der Helligkeit dreht, wird ausschließlich die RGB-GA adressiert.

Ich bitte um Unterstützung!

**Comment by Superwuzy** [comment]
Bekomme ich gar keine Unterstützung?

**Comment by brutella** [comment]
Leider konnte ich das Problem bei mir noch nicht reproduzieren. Ausserdem hab ich gerade Probleme mein Windows 10 über die VM zum Laufen zu bringen. Daher verzögert sich das alles. Sorry.

**Comment by brutella** [comment]
Die RGB-Steuerung sollte im aktuellsten Build von [1.2.0](https://github.com/brutella/hkknx-public/releases/tag/1.2.0) behoben sein.
