### ISSUE TITLE
Plan to support Energy Meters

### ISSUE THREAD

**Issue by petnau** [brutella/hkknx-public#78]
Hi,

Would it possbile to support KNX Energy Meters and Actuators that have energy measuring capabilities?

To start with just as a display to read the current consumtion/usage values?

Best regards, 
Petri Naumanen

**Comment by brutella** [comment]
The HomeKit protocol doesn't include characteristics for voltage and consumption measurements.
This means that the Apple Home app does not show this kind of values.

(Technically it would be possible to add them, but it would require a third-party HomeKit app to inspect those values on iOS.)
