### ISSUE TITLE
Fan Control

### ISSUE THREAD

**Issue by charlez79** [brutella/hkknx-public#79]
Would be nice if i could control my ventilation with the bridge.

**Comment by brutella** [comment]
What settings does your ventilation system offer?

**Comment by charlez79** [comment]
I have multiple options (presets or levels are possible)  I'm using the Comfo Logic module of MatthiasS.
I don't know what is possible with homekit. Levels 0,1,2,3 should be already nice to have.

**Comment by ring-um** [comment]
Dear brutella,
I definitely support the wish of charlez79. I have the same problem, I want to add my ventilation system which is not possible at the moment.

Most of the KNX-ventilation systems are working very similar:

Link description is a example (often used for Lunos or Viessmann controlled Fans - Dezentrale Wohnraumlüftung)
https://www.lunos.de/files/Downloads/Einbauanleitungen/Einbauanleitung_KNX-CONTROL-4.pdf

Important on that Topic is also the Locking-Funktion (Sperrobjekt) to ensure that the system is really OFF

Would be really nice if you could add that, if you need somebody to test please let me know.

**Comment by brutella** [comment]
HomeKit doesn't have a specific type of accessory for ventilation system. But we could use a fan to represent a ventilation system.

Which group addresses are used to change the levels?

**Comment by charlez79** [comment]
Using 8-bit DPT 5.010 , value 0,1,2,3

**Comment by charlez79** [comment]
Any update on this request?

**Comment by brutella** [comment]
Fan accessories are now available in the latest pre-release build for version [1.3.0](https://github.com/brutella/hkknx-public/releases/tag/1.3.0).
