### ISSUE TITLE
Fehlermeldung: unexpected EOF / ..inbound of type <nil>

### ISSUE THREAD

**Issue by feanmg** [brutella/hkknx-public#8]
Hallo,
ich habe jetzt weitere Geräte hinzugefügt (momentan 47), aber jetzt klappt die Verbindung nicht mehr richtig (Gateway nicht gefunden). Die Konfigurationsoberfläche kann ich nutzen. Bin auf v12.

Die Home-App selbst scheint "einigermaßen" zu funktionieren (?)

Zuletzt habe ich Fenstersensoren hinzugefügt (KNX DPT 1.005), konfiguriert in hkknx ebenfalls als Typ DPST-1-5, sowie eine Test-GA (DPT-1, 15/0/0).

_pi@raspberrypi:~ $ nmap -p 3671 192.168.0.44 -Pn

Starting Nmap 7.40 ( https://nmap.org ) at 2020-02-22 07:15 UTC
Nmap scan report for KNXIPInterface731.localdomain (192.168.0.44)
Host is up.
PORT     STATE    SERVICE
3671/tcp filtered efcp

Nmap done: 1 IP address (1 host up) scanned in 2.40 seconds
pi@raspberrypi:~ $ ./hkknx -db ./database -port 9090 -verbose
INFO 2020/02/22 07:15:23 main.go:54: version 0.0.12 (built at 2020-02-21T12:35:50Z+0100)
INFO 2020/02/22 07:15:23 main.go:162: webpage available at port 9090
2020/02/22 07:15:23 unpack: unexpected EOF
2020/02/22 07:15:23 connect: unexpected inbound of type <nil>
DEBUG 2020/02/22 07:15:33 main.go:126: app: dial gateway: no route to 192.168.0.44:3671; retrying in 5s
2020/02/22 07:15:38 unpack: unexpected EOF
2020/02/22 07:15:38 connect: unexpected inbound of type <nil>
DEBUG 2020/02/22 07:15:48 main.go:126: app: dial gateway: no route to 192.168.0.44:3671; retrying in 5s
2020/02/22 07:15:53 unpack: unexpected EOF
2020/02/22 07:15:53 connect: unexpected inbound of type <nil>
^CINFO 2020/02/22 07:15:54 main.go:155: shutting down...
INFO 2020/02/22 07:15:54 main.go:158: good bye ;)
DEBUG 2020/02/22 07:16:03 main.go:126: app: dial gateway: no route to 192.168.0.44:3671; retrying in 5s
pi@raspberrypi:~ $_ 

Kannst du hieraus etwas lesen?
Wäre es möglich, die Fehlermeldungen zu erweitern, so dass der Nutzer besser nach dem Fehler suchen kann?

Für Tests stehe ich dir jederzeit zur Verfügung.

**Comment by feanmg** [comment]
Ich kann nicht ausschließen, dass der Fehler aufgetreten ist, weil ich versehentlich (SSH-Verbindung auf den Rapi von mehreren Rechnern) mehrere Instanzen von hkknx gestartet habe, kann das sein? Auf jeden Fall tritt der Fehler nach dem Neustart nicht mehr auf.

Kannst du beim Start der Bridge prüfen, ob bereits eine Instanz läuft und einen Hinweis ausgeben, bzw. den weiteren Start verhindern?

**Comment by brutella** [comment]
> Kannst du beim Start der Bridge prüfen, ob bereits eine Instanz läuft und einen Hinweis ausgeben, bzw. den weiteren Start verhindern?

Eine spezielle Überprüfung für diesen Fall ist nicht vorgesehen.

Bitte eröffne das Issue, wenn dein Problem wieder auftritt?
