### ISSUE TITLE
Garage door  impulse required

### ISSUE THREAD

**Issue by sbrock1977** [brutella/hkknx-public#80]
Hi Matthias

thanks for this great piece of work.

I do have a small issue with my garage door, it requires an impulse ("1" for say  1 sec, then "0" again). I could not figure out if and how to do this with the current version 1.1.1. 

Any guidance?

Regards
Sascha

**Comment by chef76** [comment]
Hi Sascha, 

configure your actuator as stairwell lightning for 1-2s in ETS. Works fine for me.

**Comment by sbrock1977** [comment]
Hi, 

that's unfortunately not an option - the garage door is controlled by a Siemens Logo which is connected to KNX via the Siemens CMK2k gateway. It only allows pass-thru, and resetting flags in Logo programming language is something I could not resolve after hours of testing.

What could work though - I do have a Gira X1, that would allow stairwell lighting. I would connect the group address that triggers the garage door to the input, set timer to one sec and connect the very same group address I used to trigger to the output...

**Comment by chef76** [comment]
... Sounds like a plan!👍

**Comment by sbrock1977** [comment]
Alright, I just realized there's a monoflop setting on the Siemens gateway. Similar to stairwell lighting, it creates the required impulse.  Thanks for pointing me to the right direction!

**Comment by sbrock1977** [comment]
Given this workaround, my issue has been solved. Not sure if considering as feature enhancement though.
