### ISSUE TITLE
Ist Temperatur ist falsch

### ISSUE THREAD

**Issue by ALG-KNX** [brutella/hkknx-public#84]
Obwohl die Gruppenadresse für die Isttemperatur richtig ist, wird diese in Homekit falsch angezeigt. Die Solltemperatur ist richtig. Es scheint, dass nach längerem Betrieb die Isttemperatur irgendwann richtig wird. Das ist speziell bei der Neuanlage eines Heizungssteurung nervig

**Comment by chef76** [comment]
... das hört sich so an, als ob bei der Initialisierung die Temperatur nicht vom Sensor gelesen werden kann und sie dann nach dem nächsten Telegramm passt. Schau mal in den Eigenschaften der Ist-Temperatur im Sensor, ob das Lesen-Flag gesetzt ist.

**Comment by ALG-KNX** [comment]
Danke, hat sich erledigt, es war ein Fehler auf dem Bus

**Comment by ALG-KNX** [comment]
Erledigt
