### ISSUE TITLE
RGBW color Control

### ISSUE THREAD

**Issue by charlez79** [brutella/hkknx-public#87]
Hi will a rgbw control also be available using DPT 5.001 (0-100%) per channel
R    DPT 5.001 (0-100%)
G   DPT 5.001 (0-100%)
B   DPT 5.001 (0-100%)
W DPT 5.001 (0-100%)

**Comment by brutella** [comment]
Separate group addresses for red, green and blue are now supported in version 1.2.0

**Comment by charlez79** [comment]
OK, thanks for the feedback, the seperate white channel will this be added in the future or is it not supported in homekit
