### ISSUE TITLE
Mixed Content Error for Log Websocket in Console

### ISSUE THREAD

**Issue by BugRoger** [brutella/hkknx-public#89]
The console log assumes the hkknx API is being called using a insecure connection. 

![image](https://user-images.githubusercontent.com/147369/115144015-9e5f4580-a04a-11eb-8620-f948dadac7c2.png)

Something like this should do the trick:

```
        function createSocket() {
            var connectionEstablished = false;
            if (window["WebSocket"]) {
                socket = new WebSocket((window.location.protocol === "https:") ? "wss://" : "ws://") + document.location.host +"/api/system/log");
```

**Comment by brutella** [comment]
This should be fixed in the latest pre-release build for version 1.3.0.
