### ISSUE TITLE
Verbesserungsvorschlag: Erweiterung Webfrontend (Log, Konfiguration, Backup)

### ISSUE THREAD

**Issue by feanmg** [brutella/hkknx-public#9]
(1) Zur Erleichterung der Fehlersuche bei nicht-so-versierten Nutzern wäre es wünschenswert, wenn ein auführliches Logfile auf der Weboberfläche dargestellt werden könnte. (Wenn möglich, auch mit konkreteren Angaben)

(2) Desweiteren könnte ich auf der Seite gut vorstellen, einen Schalter einzubinden, dass auch Beta-Releases direkt in der Oberfläche geupdated werden können und den Dienst (und/oder den ganzen Rechner) herunterzufahren / neu zu starten.

(3) Desweiteren würde ich mir wünschen, ein Backup der Einstellungen als ZIP-File herunterladen zu können.

(4) Gut fände ich es auch, auf der Übersichtsseite der GA die geutzten GAs zu markieren, für eine bessere Übersicht, welche Verknüpfungen ggf. noch fehlen.

(5) Auf der Seite "Einstellungen" ist ein Rechtschreibfehler: "Hinweis: Die IP-Adresse des Gateways darf sich nicht änderT."

Gerade in dem Zuge, dass lt. https://hochgatterer.me/hkknx/ geplant ist, zukünfig ein fertiges Rasperry-Pi-Image anzubieten, fände ich es gut, weg von der Kommandozeile und hin zur kompletten Weboberfläche zu gehen.

**Comment by brutella** [comment]
> (1) Zur Erleichterung der Fehlersuche bei nicht-so-versierten Nutzern wäre es wünschenswert, wenn ein auführliches Logfile auf der Weboberfläche dargestellt werden könnte. (Wenn möglich, auch mit konkreteren Angaben)

Gute Idee → #12 

> (2) Desweiteren könnte ich auf der Seite gut vorstellen, einen Schalter einzubinden, dass auch Beta-Releases direkt in der Oberfläche geupdated werden können und den Dienst (und/oder den ganzen Rechner) herunterzufahren / neu zu starten.

Einen Mechanismus zum Neustarten des Prozesses gibt es schon. Muss ich nur noch über die Oberfläche zur Verfügung stellen. → #13
Das mit Beta-Releases sehe ich auch als wichtiges Feature. → #14

> (3) Desweiteren würde ich mir wünschen, ein Backup der Einstellungen als ZIP-File herunterladen zu können.

#17

> (4) Gut fände ich es auch, auf der Übersichtsseite der GA die geutzten GAs zu markieren, für eine bessere Übersicht, welche Verknüpfungen ggf. noch fehlen.

#16

> (5) Auf der Seite "Einstellungen" ist ein Rechtschreibfehler: "Hinweis: Die IP-Adresse des Gateways darf sich nicht änderT."

Danke, wird geändert. → #15

> Gerade in dem Zuge, dass lt. https://hochgatterer.me/hkknx/ geplant ist, zukünfig ein fertiges Rasperry-Pi-Image anzubieten, fände ich es gut, weg von der Kommandozeile und hin zur kompletten Weboberfläche zu gehen.

Ja, bei einem fertigen Image muss noch mehr über die Weboberfläche zur Verfügung stehen.
