### ISSUE TITLE
Tunable White Spots verursachen Bridge-Absturz

### ISSUE THREAD

**Issue by HollaTheWoodFairy** [brutella/hkknx-public#90]
Ich hoffe ich bin hier richtig mit einem Problem.
### Ablauf:
Ich habe vor zwei Wochen Dali Spots in meine KNX Installation eingebunden und war in der Lage, über HKKNX als Bridge die Spots zu Dimmen und die Farbwärme einzustellen. Das funktioniert auch nach wie vor.
Weil mir das so gut gefallen hat habe ich eine Lizenz erworben um weitere Geräte zu integrieren.
Nun habe ich heute weitere Spots (identisch zu den ersten) hinzugefügt und sowohl in der ETS als auch in HKKNX angelegt.

### Dabei habe ich ein Problem festgestellt:
Wenn ich in HKKNX die Adressen für die Farbtemperatur einstelle und speichere stürzt allem Anschein nach die Bridge ab. Ich bekomme kein Verbindung zum HomeKit Server und zum KNX Gateway mehr. Das KNX Gateway wird nun auch dauerhaft blockiert und ich kann keine Verbindung durch die ETS mehr aufbauen. Die ETS sagt, dass die Verbindung blockiert ist.
Dieses Verhalten bleibt so lange bestehen bis ich die Farbtemperatur in dem entsprechenden Spot wieder herausnehme.

Ich würde auch Logs zur Verfügung stellen wenn mir jemand sagt wie ;)

_Versionen:
hkknx: 1.3.0
ETS: 5.7.5 1373_

**Comment by brutella** [comment]
Wie man auf die Log-Ausgaben zugreift, erfährst du im [Online Handbuch](https://hochgatterer.me/de/hkknx/docs/help/access-log/).

**Comment by brutella** [comment]
Ich bin guter Dinge, dass ich das Problem gelöst habe.
Bitte lade dir den aktuellsten Build für Version 1.3.0 nochmal herunter und versuche es noch einmal.

**Comment by HollaTheWoodFairy** [comment]
Danke, da warst du ja schneller als ich. Ich teste das heut Abend und gebe Feedback.

**Comment by HollaTheWoodFairy** [comment]
@brutella 
War leider nicht von Erfolg gekrönt. Anbei der Log:
[20210427_16_11_hkknx_log.txt](https://github.com/brutella/hkknx-public/files/6385173/20210427_16_11_hkknx_log.txt)

**Comment by brutella** [comment]
Welche Eigenschaft hast du in hkknx für die Farbtemperatur aktiviert?

**Comment by brutella** [comment]
Habe den Fehler gefunden. Bitte nochmal mit der aktuellsten Version versuchen.

**Comment by HollaTheWoodFairy** [comment]
Danke dir - funktioniert jetzt. Mach weiter so. Ist ein tolles Tool 👍
