### ISSUE TITLE
FAN in KNX has value from 0 to 255 dec, but  hkknx only has value from 0 to 100 available.

### ISSUE THREAD

**Issue by hahasagined** [brutella/hkknx-public#91]

**Comment by hahasagined** [comment]
Hello,
I am using a fan that where I have to write values from 0 to 255 - hkknx only gives me 0 to 100, so the fan never goes to 100% (=255). Is there something that I can configure here or is that a missing feature?
Thank you!

**Comment by brutella** [comment]
I've added the option in the latest pre-release build for version 1.3.0.
Please download it again.

**Comment by hahasagined** [comment]
Thank you for the fast response @brutella 
I downloaded the latest version form github (hkknx-1.3.0_linux_amd64.tar.gz) and started it and can't find the option, what am I doing wrong? 

this is what I downloaded:
wget https://github.com/brutella/hkknx-public/releases/download/1.3.0/hkknx-1.3.0_linux_amd64.tar.gz

![Bildschirmfoto 2021-04-26 um 09 24 02](https://user-images.githubusercontent.com/3049408/116044466-3d022c80-a671-11eb-999e-d5659f1badde.png)

**Comment by brutella** [comment]
Did you download it just now? I've uploaded a new build just some minutes ago.

**Comment by hahasagined** [comment]
works like a charm, thank you :)
just bought the license, your product and your quick responses are appreciated.

**Comment by hahasagined** [comment]
ok - something that I have seen, maybe that is a bug or expected by design:
the Fan is not showing any data, until I have manually changed the value via HomeKit or ETS. 
it seems like HomeKit does not "read" the initial value of the fan when the server is starting.

When I start HK-KNX, I see in the verbose logs:
DEBUG 2021/04/26 17:54:25 io.go:12: read: 3/0/14
but, still the current value is not seen.

Is that expected?

**Comment by chef76** [comment]
You have to set the read-flag on your actuator for the value that sends to your group adress 3/0/14. Without the flag, the actuator does not respond to the initial read-request. You should see a timeout in the logs.

**Comment by hahasagined** [comment]
thank you for your response.
Here is the screenshot of my fan device:
![image](https://user-images.githubusercontent.com/3049408/116130327-6059c580-a6cb-11eb-8a95-a71e5b5b9a8a.png)

If I go to ETS and do a "read" for that group address, I see that I get a response with the current value:
![image](https://user-images.githubusercontent.com/3049408/116130571-ad3d9c00-a6cb-11eb-9eb6-b511a93d6a07.png)

so from the KNX side it is working as expected, not sure if there is a way to debug this on HK-KNX.

**Comment by chef76** [comment]
There shouldn't be wrong data-type in HKKNX. What data-type is set in ETS for your group adresses?

**Comment by hahasagined** [comment]
both are 5.0001 Percent:
![image](https://user-images.githubusercontent.com/3049408/116132988-7cab3180-a6ce-11eb-9e8a-45993afa8830.png)

In the Group Address Page, the type seems to be right?
![image](https://user-images.githubusercontent.com/3049408/116133156-ab290c80-a6ce-11eb-880c-d0ea1298f877.png)

**Comment by brutella** [comment]
Ok, then you would need the datatype `DPST-5-1` (5.001) instead of `DPST-5-10` (5.010). I can add that.

**Comment by hahasagined** [comment]
that would be great, I missed the detail about DPST-5-1 and DPST-5-10. Thanks!

**Comment by brutella** [comment]
The datatype DPST-5-1 is now available.

**Comment by hahasagined** [comment]
Now the error in the GUI is gone:
![image](https://user-images.githubusercontent.com/3049408/116229721-233b1500-a757-11eb-9d9f-055ca83fd40c.png)

But still, if I open the Home App or restart HKKNX I don't see that the fan is online.
From what I can see, if the HKKNX is starting, it is reading all initializing GAs, that is working and I see a reply from KNX in the KNX Bus:
![image](https://user-images.githubusercontent.com/3049408/116230403-e4598f00-a757-11eb-9ab0-c579ca848ce0.png)

Still in the Home App, the fan is off - even though it is on 75%. 
![image](https://user-images.githubusercontent.com/3049408/116230515-06eba800-a758-11eb-9eab-4b197f49317d.png)

should I open another issue for that?

**Comment by brutella** [comment]
Hab den Fehler beim Initialisieren entdeckt. Bitte nochmals updaten. 😄

**Comment by hahasagined** [comment]
😍
![image](https://user-images.githubusercontent.com/3049408/116269940-f4389980-a77e-11eb-8e2a-13ed347bd28f.png)
