### ISSUE TITLE
Switch (Schalter) vs Push Button switch (Taster)

### ISSUE THREAD

**Issue by hahasagined** [brutella/hkknx-public#92]
Hey,
I have a Group address in KNX that switches all lights off - currently I can't find a way to call this via HomeKit. If I configure it as a "Schalter" it first enables stuff, then I have to click it again to switch everything off.
I would love to use a "Taster" where whenever I click it, HomeKit would send a "0" (off) to a group address).
 
 Thank you,
Martin

**Comment by chef76** [comment]
Hi,
you have to use the the "Szene" option. There you can select the datapoint-type DPT-1(0) or DPT-1(1) whether you want to turn your lights off or on.

**Comment by hahasagined** [comment]
That worked, thank you!!
