### ISSUE TITLE
Dashboard für Statuseinträge

### ISSUE THREAD

**Issue by HollaTheWoodFairy** [brutella/hkknx-public#95]
Evtl. als Erweiterung:
Wenn ich es richtig verstanden habe, dass bekomme ich aktuell keine Status-Zustände in HomeKit abgebildet.
Mich würden allerdings Fehlermeldungen interessieren die über den KNX Bussen kommen (z.b. ob die Heizung im Sommer oder Wintermodus ist oder ob ein Fehler im Dali Netzwerk aufgetreten ist etc.).
Evtl. kann so etwas als HKKNX Dashboard/Visualisierung integriert werden.
Ist etwas in die Richtung angedacht oder evtl. sogar schon möglich? Oder bleibt mir dann nur der Weg über einen der anderen Visualisierungen am Markt?
Viele Grüße.

**Comment by brutella** [comment]
Könntest du bitte mal Beispiele nenne welche Daten für welche Zustand verarbeitet werden müssen.
Also wie werden Dali Fehler über den KNX Bus gesendet? Und wie sollte das in einer Visualisierung dargestellt werden?

(Ich arbeite gerade an etwas Neuem, mit dem das vermutlich möglich sein wird. Mehr kann ich zurzeit noch nicht verraten.)

**Comment by HollaTheWoodFairy** [comment]
Ich bin noch blutiger Anfänger was das Thema angeht und weiß nicht ob ich dir die "richtigen" Infos geben kann. Für Dali kann ich in dem KNX/Dali Gateway einen Fehlerstatus-Typ über 1bit oder 1byte setzen. Ich hab allerdings keine Ahnung was dort ausgegeben wird.
Die Idee das Dashboards wäre in meinen Augen eine Art erweiterte Home+ App die Entsprechend auch eigene "Kacheln" mit individuellen Werten zulässt. So, dass man z. B. sich auf einer Kachel alle Raumtemperaturen anzeigen lassen kann. Oder ob irgendwo Fenster offen sind. Oder wenn irgendwo Fehler auflaufen, dass man diese Visualisiert bekommt. Vielleicht wäre das ja noch eine Erweiterung für die Home+ iPad Version um sich ein "altes" iPad als Steuerzentrale an die Wand zu hängen.

Im Prinzip gibt es das ja auch schon für HomeBridge, FHEM und wie sie nicht alle heißen - allerdings sind sie aus meiner sicht nicht so Benutzerfreundlich wie das was du mit HKKNX gebaut hast da du dich damit ja auf die Apple Welt spezialisiert hast.

Falls du Hilfe benötigst stehe ich gern mit Rat und Tat zur Verfügung. Mein Steckenpferd ist ehr das Thema UI/UX.

**Comment by brutella** [comment]
<img width="553" alt="Screenshot 2021-05-19 at 11 21 52" src="https://user-images.githubusercontent.com/125641/118788792-6be87880-b894-11eb-95db-01f9f65729a8.png">

Wie man so etwas mit einem [Skript](https://hochgatterer.me/de/hkknx/docs/scripts/) erstellt, erfährst du [hier](https://hochgatterer.me/de/hkknx/docs/scripts/dashboard/).

**Comment by willgf** [comment]
Very cool! 

Maybe this could be built into the Home+ app?
