### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by willgf** [brutella/hkknx-public#96]
A feature that the Apple Home app really misses for me is a visual scheduler, e.g. something like this:

![image](https://user-images.githubusercontent.com/48946125/118964887-eaf6b300-b95f-11eb-9ddb-dd4eafc9cd67.png)

I'd love to be able to schedule heating/temperatures for example, rather than relying on automations which quickly become cluttered. 

Ideally, something visual like Eve with options to add logic to active schedules based on presence, or holidays. 

Maybe this can be integrated into HKKNX or maybe your Home+ App?

**Comment by brutella** [comment]
Please take a look at #88 where this kind of automations are discussed.
